<?php if ( $profile['userGroupSlug'] === 'teacher' ): ?>
<link href="<?php echo $this->basePath(); ?>/css/bootstrap.datetimepicker.min.css" media="screen" rel="stylesheet" type="text/css">
<ul class="nav nav-tabs">
    <li class="dropdown active">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">我开设的课程 <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li class="active"><a href="#courses" data-toggle="tab">我开设的课程</a></li>
            <li><a href="#lectures" data-toggle="tab">我开设的培训</a></li>
        </ul>
    </li>
    <li><a href="#attendance" data-toggle="tab">我参加的课程</a></li>
</ul>
<div class="tab-content">
    <div id="courses" class="active tab-pane">
        <p class="no-opening-courses">您暂未开设课程. <a href="#course">开设新课程</a></p>
        <ul id="opening-courses" class="courses"></ul>
        <ul id="courses-pagination" class="inline pagination"></ul>
        <!-- Java Script -->
        <script type="text/javascript">
            function getOpeningCourses(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getOpeningCourses?&page=' + pageNumber,
                    dataType: 'JSON',
                    success: function(result) {
                        $('#opening-courses').empty();
                        if ( result['isSuccessful'] ) {
                            $('.no-opening-courses').addClass('hide');
                            displayOpeningCourses(result['courses']);
                        } else {
                            $('.no-opening-courses').removeClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            function displayOpeningCourses(courses) {
                var numberOfCourses = courses.length;
                for ( var i = 0; i < numberOfCourses; ++ i ) {
                    $('#opening-courses').append('<li id="course-' + courses[i]['courseId'] + '" class="course row-fluid">' 
                                               + '    <div class="span3">'
                                               + '        <img src="<?php echo $this->basePath(); ?>/img/categories/' + courses[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                               + '    </div>'
                                               + '    <div class="span9">'
                                               + '        <h4>'
                                               + '            <a href="<?php echo $this->basePath(); ?>/training/course?courseId=' + courses[i]['courseId'] + '">' + courses[i]['courseName'] + '</a>'
                                               + '        </h4>'
                                               + '        <p class="brief">' + courses[i]['brief'] + '</p>'
                                               + '        <ul class="inline meta">'
                                               + '            <li><a href="#course?courseId=' + courses[i]['courseId'] + '"><i class="icon-plus"></i> 编辑课程信息</a></li>'
                                               + '            <li><a href="javascript:void(0)" class="new-lecture"><i class="icon-pencil"></i> 创建新培训</a></li>'
                                               + '        </ul>'
                                               + '    </div>'
                                               + '</li>');
                }
            }
        </script>
        <script type="text/javascript">
            function getOpeningCourseTotalPages(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getOpeningCourseTotalPages',
                    dataType: 'JSON',
                    success: function(result) {
                        var paginationObject = $('#courses-pagination');

                        $(paginationObject).empty();
                        if ( result['isSuccessful'] ) {
                            $(paginationObject).removeClass('hide');
                            displayPagination(pageNumber, result['totalPages'], paginationObject);
                        } else {
                            $(paginationObject).addClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            $('#courses-pagination').delegate('li', 'click', function() {
                var currentPage = parseInt($('li.active > a', '#courses-pagination').html(), 10),
                    pageNumber  = $('a', this).html();
                
                if ( pageNumber === '&lt;' ) {
                    pageNumber  = currentPage - 1;
                } else if ( pageNumber === '&gt;' ) {
                    pageNumber  = currentPage + 1;
                }
                getOpeningCourses(pageNumber);
                getOpeningCourseTotalPages(pageNumber);
            });
        </script>
        <script type="text/javascript">
            $('#opening-courses').delegate('a.new-lecture', 'click', function() {
                var courseObject = $(this).parent().parent().parent().parent(),
                    courseId     = $(courseObject).attr('id').substring(7);
                    courseName   = $('h4 > a', courseObject).html();

                $('#new-lecture-modal-step-1 input').val('');
                $('#new-lecture-modal-step-1 #course-id').val(courseId);
                $('#new-lecture-modal-step-1 #course-name').val(courseName);
                $('#new-lecture-modal-step-1').modal();
            });
        </script>
    </div> <!-- #opening-courses -->
    <div id="lectures" class="tab-pane">
        <p class="no-opening-lectures">您暂未开设培训课. <a href="javascript:void(0)">您可以在[我开设的课程]页面创建培训课</a></p>
        <ul id="opening-lectures" class="courses"></ul>
        <ul id="lectures-pagination" class="inline pagination"></ul>
        <!-- Java Script -->
        <script type="text/javascript">
            function getOpeningLectures(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getOpeningLectures?&page=' + pageNumber,
                    dataType: 'JSON',
                    success: function(result) {
                        $('#opening-lectures').empty();
                        if ( result['isSuccessful'] ) {
                            $('.no-opening-lectures').addClass('hide');
                            displayOpeningLectures(result['lectures']);
                        } else {
                            $('.no-opening-lectures').removeClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            function displayOpeningLectures(lectures) {
                var numberOfLectures = lectures.length;
                for ( var i = 0; i < numberOfLectures; ++ i ) {
                    $('#opening-lectures').append('<li id="lectures-' + lectures[i]['lectureId'] + '" class="course row-fluid">' 
                                                + '    <div class="span3">'
                                                + '        <img src="<?php echo $this->basePath(); ?>/img/categories/' + lectures[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                                + '    </div>'
                                                + '    <div class="span9">'
                                                + '        <h4>'
                                                + '            <a href="<?php echo $this->basePath(); ?>/training/lecture?lectureId=' + lectures[i]['lectureId'] + '">' + lectures[i]['courseName'] + '</a>'
                                                + '        </h4>'
                                                + '        <ul class="inline meta">'
                                                + '            <li><i class="icon-calendar"></i> '+ getDateTime(lectures[i]['startTime']) + '~' + getDateTime(lectures[i]['endTime']) + '</li>'
                                                + '            <li><i class="icon-map-marker"></i> ' + lectures[i]['lectureProvince'] + (lectures[i]['lectureCity'] || '') + lectures[i]['lectureAddress'] + '</li>'
                                                + '            <li><i class="icon-user"></i> ' + (lectures[i]['participants'] || '0') + '/' + lectures[i]['maxCapcity'] + ' 人</li>'
                                                + '            <li><i class="icon-jpy"></i> ' + lectures[i]['expense'] + ' 元</li>'
                                                + '            <li></li>'
                                                + '        </ul>'
                                                + '    </div>'
                                                + '</li>');
                }
            }
        </script>
        <script type="text/javascript">
            function getOpeningLectureTotalPages(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getOpeningLectureTotalPages',
                    dataType: 'JSON',
                    success: function(result) {
                        var paginationObject = $('#lectures-pagination');

                        $(paginationObject).empty();
                        if ( result['isSuccessful'] ) {
                            $(paginationObject).removeClass('hide');
                            displayPagination(pageNumber, result['totalPages'], paginationObject);
                        } else {
                            $(paginationObject).addClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            $('.no-opening-lectures > a').click(function() {
                $('.nav-tabs a[href=#courses]').tab('show');
            });
        </script>
        <script type="text/javascript">
            $('#lectures-pagination').delegate('li', 'click', function() {
                var currentPage = parseInt($('li.active > a', '#lectures-pagination').html(), 10),
                    pageNumber  = $('a', this).html();
                
                if ( pageNumber === '&lt;' ) {
                    pageNumber  = currentPage - 1;
                } else if ( pageNumber === '&gt;' ) {
                    pageNumber  = currentPage + 1;
                }
                getOpeningLectures(pageNumber);
                getOpeningLectureTotalPages(pageNumber);
            });
        </script>
    </div> <!-- #opening-lectures -->
    <div id="attendance" class="tab-pane">
<?php else: ?>
        <h4>我的培训课</h4>
<?php endif; ?>
        <p class="no-courses">您暂未参加培训课. <a href="<?php echo $this->basePath(); ?>/training/lectures">查看近期开课</a></p>
        <ul id="attendance-records" class="courses"></ul>
        <ul id="attendance-pagination" class="inline pagination"></ul>
        <!-- Java Script -->
        <script type="text/javascript">
            function getLectureAttendance(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getLectureAttendance?&page=' + pageNumber,
                    dataType: 'JSON',
                    success: function(result) {
                        $('#attendance-records').empty();
                        if ( result['isSuccessful'] ) {
                            $('.no-courses').addClass('hide');
                            displayLectureAttendance(result['records']);
                        } else {
                            $('.no-courses').removeClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            function displayLectureAttendance(records) {
                var numberOfRecords = records.length;
                for ( var i = 0; i < numberOfRecords; ++ i ) {
                    var lectureString   = '',
                        commentString   = '';

                    lectureString   = '<li class="course row-fluid">'
                                    + '    <div class="span3">'
                                    + '        <img src="<?php echo $this->basePath(); ?>/img/categories/' + records[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                    + '    </div>'
                                    + '    <div class="span9">'
                                    + '        <h4>'
                                    + '            <a href="<?php echo $this->basePath(); ?>/training/lecture?lectureId=' + records[i]['lectureId'] + '">' + records[i]['courseName'] + '</a>'
                                    + '            <span class="extra">(报名序列号:' + records[i]['serialCode'] + ', 剩余次数: ' + (records[i]['remainTimes'] || '0') + '次)</span>'
                                    + '        </h4>'
                                    + '        <ul class="inline meta">'
                                    + '            <li><i class="icon-user"></i> <a href="<?php echo $this->basePath(); ?>/training/teacher?teacherId=' + records[i]['lectureTeacherId'] + '">' + records[i]['lectureTeacherName'] + '</a></li>'
                                    + '            <li><i class="icon-calendar"></i> ' + getDateTime(records[i]['lectureStartTime']) + '~' + getDateTime(records[i]['lectureEndTime']) + '</li>'
                                    + '            <li><i class="icon-map-marker"></i> ' + records[i]['lectureProvince'] + ( records[i]['lectureCity'] || '' ) + records[i]['lectureAddress'] + '</li>'
                                    + '        </ul>'
                                    + '    </div>'
                                    + '</li>';
                    $('#attendance-records').append(lectureString);
                    
                    if ( records[i]['lectureEndTime'] < '<?php echo date("Y-m-d H:i:s"); ?>' ) {
                        if ( records[i]['commentDetail'] != null ) {
                            commentString = getCommentString(records[i]['commentRanking'], records[i]['commentDetail']);
                        } else {
                            commentString = '<li id="comment-' + records[i]['lectureId'] + '" class="comment row-fluid">'
                                          + '    <div class="span3">'
                                          + '        发表评论<br />'
                                          + '        <span class="ranking-editable">' + getRankingString(0) + '</span>'
                                          + '    </div>'
                                          + '    <div class="span9">'
                                          + '        <textarea rows="2" placeholder="请在此填写评论"></textarea>'
                                          + '        <button class="btn btn-success btn-submit">提交</button>'
                                          + '    </div>'
                                          + '</li>';
                        }
                    } else {
                        commentString = '<li class="comment row-fluid"></li>';
                    }
                    $('#attendance-records').append(commentString);
                }
            }
        </script>
        <script type="text/javascript">
            function getCommentString(commentRanking, commentDetail) {
                commentString = '<li class="comment row-fluid">'
                              + '    <div class="span3">'
                              + '        我的评价<br />'
                              + '        <span class="ranking">' + getRankingString(parseInt(commentRanking, 10)) + '</span>'
                              + '    </div>'
                              + '    <div class="span9">'
                              + '        <p>' + commentDetail + '</p>'
                              + '    </div>'
                              + '</li>';
                return commentString;
            }
        </script>
        <script type="text/javascript">
            function getRankingString(rankingLevel) {
                var rankingImageString  = '';
                for ( var i = 0; i < rankingLevel; ++ i ) {
                    rankingImageString += '<img src="<?php echo $this->basePath(); ?>/img/ranking/full-star.png" alt="Star" />';
                }
                for ( var i = rankingLevel; i < 5; ++ i ) {
                    rankingImageString += '<img src="<?php echo $this->basePath(); ?>/img/ranking/empty-star.png" alt="Star" />';
                }
                return rankingImageString;
            }
        </script>
        <script type="text/javascript">
            function getRankingLevel(rankingObject, currentObject) {
                if ( typeof(currentObject) === 'undefined' ) {
                    return countRankingFullStars(rankingObject);
                } else {
                    return $(currentObject, rankingObject).index() + 1;
                }
            }
        </script>
        <script type="text/javascript">
            function countRankingFullStars(rankingObject) {
                var fullStars = 0;
                $('img', rankingObject).each(function() {
                    if ( $(this).attr('src').indexOf('full-star') > -1 ) {
                        ++ fullStars;
                    }
                });
                return fullStars;
            }
        </script>
        <script type="text/javascript">
            function getLectureAttendanceTotalPages(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getLectureAttendanceTotalPages',
                    dataType: 'JSON',
                    success: function(result) {
                        var paginationObject = $('#attendance-pagination');

                        $(paginationObject).empty();
                        if ( result['isSuccessful'] ) {
                            $(paginationObject).removeClass('hide');
                            displayPagination(pageNumber, result['totalPages'], paginationObject);
                        } else {
                            $(paginationObject).addClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            $('#attendance-pagination').delegate('li', 'click', function() {
                var currentPage = parseInt($('li.active > a', '#attendance-pagination').html(), 10),
                    pageNumber  = $('a', this).html();
                
                if ( pageNumber === '&lt;' ) {
                    pageNumber  = currentPage - 1;
                } else if ( pageNumber === '&gt;' ) {
                    pageNumber  = currentPage + 1;
                }
                getLectureAttendance(pageNumber);
                getLectureAttendanceTotalPages(pageNumber);
            });
        </script>
        <script type="text/javascript">
            $('ul#attendance-records').delegate('span.ranking-editable > img', 'click', function(event) {
                var rankingObject = $(this).parent('span'),
                    currentObject = $(this);
                $(rankingObject).html(getRankingString(getRankingLevel(rankingObject, currentObject)));
            });
        </script>
        <script type="text/javascript">
            $('ul#attendance-records').delegate('button.btn-submit', 'click', function() {
                var buttonObject        = $(this),
                    commentObject       = $(this).parent().parent(),
                    lectureId           = $(commentObject).attr('id').substring(8);
                    rankingObject       = $('span.ranking-editable', commentObject),
                    commentRanking      = getRankingLevel(rankingObject),
                    commentTextObject   = $('textarea', commentObject),
                    commentDetail       = $(commentTextObject).val();

                if ( commentRanking == 0 ) {
                    alert('请对课程进行评级.');
                    return;
                } else if ( commentDetail === '' ) {
                    alert('请填写对课程的评价');
                    return;
                }
                return addComment(lectureId, commentRanking, commentDetail, commentObject, buttonObject);
            });
        </script>
        <script type="text/javascript">
            function addComment(lectureId, commentRanking, commentDetail, commentObject, buttonObject) {
                $(buttonObject).attr('disabled', 'disabled');
                
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/addComment?lectureId=' + lectureId + 
                         '&commentRanking=' + commentRanking + '&commentDetail=' + commentDetail,
                    dataType: 'JSON',
                    success: function(result) {
                        if ( result['isSuccessful'] ) {
                            var commentRanking = result['commentRanking'],
                                commentDetail  = result['commentDetail'];
                            $(commentObject).html(getCommentString(commentRanking, commentDetail));
                        } else {
                            alert('发生了未知错误, 请稍后再试.');
                        }
                        $(buttonObject).removeAttr('disabled');
                    }
                });
            }
        </script>
<?php if ( $profile['userGroupSlug'] === 'teacher' ): ?>
        </div> <!-- #tab-attendance -->
    </div> <!-- .tab-content -->
    <!-- Modals -->
    <div id="new-lecture-modal-step-1" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-header">
            <h4>创建新培训: 培训概要</h4>
        </div> <!-- .modal-header -->
        <div class="modal-body">
            <div class="row-fluid">
                <div class="span6">
                    <label for="course-name">课程名称</label>
                    <input id="course-name" type="text" disabled="disabled" />
                    <input id="course-id" type="hidden" />
                </div> <!-- .span6 -->
                <div class="span6">
                    <label for="expense">培训费用</label>
                    <div class="input-append">
                        <input class="span12" id="expense" type="text">
                        <span class="add-on">元</span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="city-picker row-fluid">
                <div class="span6">
                    <label for="lecture-address">开课地点</label>
                    <select class="region"></select>
                    <select class="city"></select>
                </div> <!-- .span6 -->
                <div class="span6">
                    <label>&nbsp;</label>
                    <select class="province"></select>
                    <input id="address" type="text" placeholder="详细地址" />
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="row-fluid">
                <div class="span6">
                    <label for="min-capcity">最小开班人数</label>
                    <div class="input-append">
                        <input class="span12" id="min-capcity" type="text">
                        <span class="add-on">人</span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
                <div class="span6">
                    <label for="max-capcity">课程最大容量</label>
                    <div class="input-append">
                        <input class="span12" id="max-capcity" type="text">
                        <span class="add-on">人</span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="row-fluid">
                <div class="control-group span6">
                    <label class="start-time">课程开始时间</label>
                    <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">
                        <input id="start-time" class="span12" type="text" value="" readonly>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
                <div class="control-group span6">
                    <label class="end-time">课程结束时间</label>
                    <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">
                        <input id="end-time" class="span12" type="text" value="" readonly>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="row-fluid">
                <div class="span12">
                    <label for="precautions">注意事项</label>
                    <textarea id="precautions" rows="4"></textarea>
                </div> <!-- .span12 -->
            </div> <!-- .row-fluid -->
        </div> <!-- .modal-body -->
        <div class="modal-footer">
            <button id="new-lecture-next-step" class="btn btn-primary">下一步</button>
            <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
        </div> <!-- .modal-footer -->
    </div> <!-- #new-lecture-modal-step-1 -->
    <div id="new-lecture-modal-step-2" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-header">
            <h4>创建新培训: 课程计划</h4>
        </div> <!-- .modal-header -->
        <div class="modal-body">
            <div class="loading">
                <img src="<?php echo $this->basePath(); ?>/img/loading.gif" alt="Loading">
            </div> <!-- .loading -->
        </div> <!-- .modal-body -->
        <div class="modal-footer">
            <button id="new-lecture-complete" class="btn btn-primary">完成</button>
            <button class="btn" disabled="disabled">取消</button>
        </div> <!-- .modal-footer -->
    </div> <!-- #new-lecture-modal-step-2 -->
    <!-- JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.citypicker.js"></script>
    <script type="text/javascript">
        $('.city-picker').cityPicker();
    </script>
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/bootstrap.datetimepicker.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/bootstrap.datetimepicker.zh-CN.js"></script>
    <script type="text/javascript">
        $('.form_datetime').datetimepicker({
            language:  'zh-CN',
            weekStart: 1,
            todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            startDate: '<?php echo date('Y-m-d'); ?>',
            forceParse: 0,
            showMeridian: 1
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function() {
            var pageNumber  = 1;
            getOpeningLectures(pageNumber);
            getOpeningLectureTotalPages(pageNumber);
            getOpeningCourses(pageNumber);
            getOpeningCourseTotalPages(pageNumber);
            getLectureAttendance(pageNumber);
            getLectureAttendanceTotalPages(pageNumber);
        });
    </script>
    <script type="text/javascript">
        $('#new-lecture-next-step').click(function() {
            $('#new-lecture-modal-step-1').modal('hide');
            $('#new-lecture-modal-step-2').modal({
                'backdrop': 'static',
            });
        });
    </script>
    <script type="text/javascript">
        $('#new-lecture-complete').click(function() {
            $('#new-lecture-modal-step-2').modal('hide');
        });
    </script>
<?php else: ?>
    <script type="text/javascript">
        $(document).ready(function() {
            var pageNumber  = 1;
            getLectureAttendance(pageNumber);
            getLectureAttendanceTotalPages(pageNumber);
        });
    </script>
<?php endif; ?>
    <script type="text/javascript">
        function getDateTime(dateTimeString) {
            var year    = dateTimeString.substring(0, 4),
                month   = dateTimeString.substring(5, 7),
                day     = dateTimeString.substring(8, 10),
                time    = dateTimeString.substring(11, 16);

            return year + '年' + month + '月' + day + '日 ' + time;
        }
    </script>
    <script type="text/javascript">
        function displayPagination(currentPage, totalPages, paginationObject) {
            var lowerBound = ( currentPage - 3 > 0 ? currentPage - 3 : 1 ),
                upperBound = ( currentPage + 3 < totalPages ? currentPage + 3 : totalPages );
            var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="javascript:void(0)">&lt;</a></li>';

            for ( var i = lowerBound; i <= upperBound; ++ i ) {
                paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="javascript:void(0)">' + i + '</a></li>';
            }
            paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="javascript:void(0)">&gt;</a></li>';
            $(paginationObject).append(paginationString);
        }
    </script>