<h4>我的培训课</h4>
<p class="no-courses">您暂未参加培训课. <a href="<?php echo $this->basePath(); ?>/training/lectures">查看近期开课</a></p>
<ul id="attendance-records" class="courses"></ul>
<ul class="inline pagination"></ul>

<script type="text/javascript">
    function getLectureAttendance(pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/accounts/getLectureAttendance?&page=' + pageNumber,
            dataType: 'JSON',
            success: function(result) {
                console.log(result);
                $('#attendance-records').empty();
                if ( result['isSuccessful'] ) {
                    $('.no-courses').addClass('hide');
                    displayLectureAttendance(result['records']);
                } else {
                    $('.no-courses').removeClass('hide');
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function displayLectureAttendance(records) {
        var numberOfRecords = records.length;
        for ( var i = 0; i < numberOfRecords; ++ i ) {
            $('#attendance-records').append('<li class="course row-fluid">'
                                          + '    <div class="span3">'
                                          + '        <img src="<?php echo $this->basePath(); ?>/img/categories/' + records[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                          + '    </div>'
                                          + '    <div class="span9">'
                                          + '        <h4>'
                                          + '            <a href="<?php echo $this->basePath(); ?>/training/lecture?lectureId=' + records[i]['lectureId'] + '">' + records[i]['courseName'] + '</a>'
                                          + '            <span class="extra">(报名序列号:' + records[i]['serialCode'] + ', 剩余次数: ' + (records[i]['remainTimes'] || '0') + '次)</span>'
                                          + '        </h4>'
                                          + '        <ul class="inline meta">'
                                          + '            <li><i class="icon-user"></i> <a href="<?php echo $this->basePath(); ?>/training/teacher?teacherId=' + records[i]['lectureTeacherId'] + '">' + records[i]['lectureTeacherName'] + '</a></li>'
                                          + '            <li><i class="icon-calendar"></i> ' + getDateTime(records[i]['lectureStartTime']) + '~' + getDateTime(records[i]['lectureEndTime']) + '</li>'
                                          + '            <li><i class="icon-map-marker"></i> ' + records[i]['lectureProvince'] + ( records[i]['lectureCity'] || '' ) + records[i]['lectureAddress'] + '</li>'
                                          + '        </ul>'

                                          + '    </div>'
                                          + '</li>');
        }
    }
</script>
<script type="text/javascript">
    function getDateTime(dateTimeString) {
        var year    = dateTimeString.substring(0, 4),
            month   = dateTimeString.substring(5, 7),
            day     = dateTimeString.substring(8, 10),
            time    = dateTimeString.substring(11, 16);

        return year + '年' + month + '月' + day + '日 ' + time;
    }
</script>
<script type="text/javascript">
    function getLectureAttendanceTotalPages(pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/accounts/getLectureAttendanceTotalPages',
            dataType: 'JSON',
            success: function(result) {
                $('ul.pagination').empty();
                if ( result['isSuccessful'] ) {
                    $('ul.pagination').removeClass('hide');
                    displayPagination(pageNumber, result['totalPages']);
                } else {
                    $('ul.pagination').addClass('hide');
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function displayPagination(currentPage, totalPages) {
        var lowerBound = ( currentPage - 3 > 0 ? currentPage - 3 : 1 ),
            upperBound = ( currentPage + 3 < totalPages ? currentPage + 3 : totalPages );
        var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="javascript:void(0)">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="javascript:void(0)">' + i + '</a></li>';
        }
        paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="javascript:void(0)">&gt;</a></li>';
        $('ul.pagination').append(paginationString);
    }
</script>
<script type="text/javascript">
    $(document).ready(function() {
        var pageNumber  = 1;
        getLectureAttendance(pageNumber);
        getLectureAttendanceTotalPages(pageNumber);
    });
</script>
<script type="text/javascript">
    $('ul.pagination').delegate('li', 'click', function() {
        var currentPage = parseInt($('li.active > a', 'ul.pagination').html(), 10),
            pageNumber  = $('a', this).html();
        
        if ( pageNumber === '&lt;' ) {
            pageNumber  = currentPage - 1;
        } else if ( pageNumber === '&gt;' ) {
            pageNumber  = currentPage + 1;
        }
        getLectureAttendance(pageNumber);
        getLectureAttendanceTotalPages(pageNumber);
    });
</script>

<?php if ( $profile['userGroupSlug'] === 'teacher' ): ?>

<?php else: ?>

<?php endif; ?>