<?php if ( $profile['userGroupSlug'] === 'teacher' ): ?>
<link href="<?php echo $this->basePath(); ?>/css/bootstrap.datetimepicker.min.css" media="screen" rel="stylesheet" type="text/css">
<ul class="nav nav-tabs">
    <li class="dropdown active">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">我开设的课程/培训 <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li class="active"><a href="#courses" data-toggle="tab">我开设的课程</a></li>
            <li><a href="#lectures" data-toggle="tab">我开设的培训</a></li>
        </ul>
    </li>
    <li><a href="#attendance" data-toggle="tab">我参加的课程</a></li>
</ul>
<div class="tab-content">
    <div id="courses" class="active tab-pane">
        <p class="no-opening-courses">您暂未开设课程. <a href="#course">开设新课程</a></p>
        <ul id="opening-courses" class="courses"></ul>
        <ul id="courses-pagination" class="inline pagination"></ul>
        <!-- Java Script -->
        <script type="text/javascript">
            function getOpeningCourses(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getOpeningCourses?&page=' + pageNumber,
                    dataType: 'JSON',
                    success: function(result) {
                        $('#opening-courses').empty();
                        if ( result['isSuccessful'] ) {
                            $('.no-opening-courses').addClass('hide');
                            displayOpeningCourses(result['courses']);
                        } else {
                            $('.no-opening-courses').removeClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            function displayOpeningCourses(courses) {
                var numberOfCourses = courses.length;
                for ( var i = 0; i < numberOfCourses; ++ i ) {
                    $('#opening-courses').append('<li id="course-' + courses[i]['courseId'] + '" class="course row-fluid">' 
                                               + '    <div class="span3">'
                                               + '        <img src="<?php echo $this->basePath(); ?>/img/categories/' + courses[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                               + '    </div>'
                                               + '    <div class="span9">'
                                               + '        <h4>'
                                               + '            <a href="<?php echo $this->basePath(); ?>/training/course?courseId=' + courses[i]['courseId'] + '">' + courses[i]['courseName'] + '</a>'
                                               + '        </h4>'
                                               + '        <p class="brief">' + courses[i]['brief'] + '</p>'
                                               + '        <ul class="inline meta">'
                                               + '            <li><a href="#course?courseId=' + courses[i]['courseId'] + '"><i class="icon-plus"></i> 编辑课程信息</a></li>'
                                               + '            <li><a href="javascript:void(0)" class="new-lecture"><i class="icon-pencil"></i> 创建新培训</a></li>'
                                               + '        </ul>'
                                               + '    </div>'
                                               + '</li>');
                }
            }
        </script>
        <script type="text/javascript">
            function getOpeningCourseTotalPages(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getOpeningCourseTotalPages',
                    dataType: 'JSON',
                    success: function(result) {
                        var paginationObject = $('#courses-pagination');

                        $(paginationObject).empty();
                        if ( result['isSuccessful'] ) {
                            $(paginationObject).removeClass('hide');
                            displayPagination(pageNumber, result['totalPages'], paginationObject);
                        } else {
                            $(paginationObject).addClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            $('#courses-pagination').delegate('li', 'click', function() {
                var currentPage = parseInt($('li.active > a', '#courses-pagination').html(), 10),
                    pageNumber  = $('a', this).html();
                
                if ( pageNumber === '&lt;' ) {
                    pageNumber  = currentPage - 1;
                } else if ( pageNumber === '&gt;' ) {
                    pageNumber  = currentPage + 1;
                }
                getOpeningCourses(pageNumber);
                getOpeningCourseTotalPages(pageNumber);
            });
        </script>
        <script type="text/javascript">
            $('#opening-courses').delegate('a.new-lecture', 'click', function() {
                var courseObject = $(this).parent().parent().parent().parent(),
                    courseId     = $(courseObject).attr('id').substring(7);
                    courseName   = $('h4 > a', courseObject).html();

                $('#new-lecture-modal-step-1 input').val('');
                $('#new-lecture-modal-step-1 #course-id').val(courseId);
                $('#new-lecture-modal-step-1 #course-name').val(courseName);
                $('#new-lecture-modal-step-1').modal();
            });
        </script>
    </div> <!-- #opening-courses -->
    <div id="lectures" class="tab-pane">
        <p class="no-opening-lectures">您暂未开设培训课. <a href="javascript:void(0)">您可以在[我开设的课程]页面创建培训课</a></p>
        <ul id="opening-lectures" class="courses"></ul>
        <ul id="lectures-pagination" class="inline pagination"></ul>
        <!-- Java Script -->
        <script type="text/javascript">
            function getOpeningLectures(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getOpeningLectures?&page=' + pageNumber,
                    dataType: 'JSON',
                    success: function(result) {
                        $('#opening-lectures').empty();
                        if ( result['isSuccessful'] ) {
                            $('.no-opening-lectures').addClass('hide');
                            displayOpeningLectures(result['lectures']);
                        } else {
                            $('.no-opening-lectures').removeClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            function displayOpeningLectures(lectures) {
                var numberOfLectures = lectures.length;
                for ( var i = 0; i < numberOfLectures; ++ i ) {
                    $('#opening-lectures').append('<li id="lectures-' + lectures[i]['lectureId'] + '" class="course row-fluid">' 
                                                + '    <div class="span3">'
                                                + '        <img src="<?php echo $this->basePath(); ?>/img/categories/' + lectures[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                                + '    </div>'
                                                + '    <div class="span9">'
                                                + '        <h4>'
                                                + '            <a href="<?php echo $this->basePath(); ?>/training/lecture?lectureId=' + lectures[i]['lectureId'] + '">' + lectures[i]['courseName'] + '</a>'
                                                + '        </h4>'
                                                + '        <ul class="inline meta">'
                                                + '            <li><i class="icon-calendar"></i> '+ formatDateTime(lectures[i]['startTime']) + '~' + formatDateTime(lectures[i]['endTime']) + '</li>'
                                                + '            <li><i class="icon-map-marker"></i> ' + lectures[i]['lectureProvince'] + (lectures[i]['lectureCity'] || '') + lectures[i]['lectureAddress'] + '</li>'
                                                + '            <li><i class="icon-user"></i> ' + (lectures[i]['participants'] || '0') + '/' + lectures[i]['maxCapcity'] + ' 人</li>'
                                                + '            <li><i class="icon-jpy"></i> ' + lectures[i]['expense'] + ' 元</li>'
                                                + '            <li></li>'
                                                + '        </ul>'
                                                + '    </div>'
                                                + '</li>');
                }
            }
        </script>
        <script type="text/javascript">
            function getOpeningLectureTotalPages(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getOpeningLectureTotalPages',
                    dataType: 'JSON',
                    success: function(result) {
                        var paginationObject = $('#lectures-pagination');

                        $(paginationObject).empty();
                        if ( result['isSuccessful'] ) {
                            $(paginationObject).removeClass('hide');
                            displayPagination(pageNumber, result['totalPages'], paginationObject);
                        } else {
                            $(paginationObject).addClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            $('.no-opening-lectures > a').click(function() {
                $('.nav-tabs a[href=#courses]').tab('show');
            });
        </script>
        <script type="text/javascript">
            $('#lectures-pagination').delegate('li', 'click', function() {
                var currentPage = parseInt($('li.active > a', '#lectures-pagination').html(), 10),
                    pageNumber  = $('a', this).html();
                
                if ( pageNumber === '&lt;' ) {
                    pageNumber  = currentPage - 1;
                } else if ( pageNumber === '&gt;' ) {
                    pageNumber  = currentPage + 1;
                }
                getOpeningLectures(pageNumber);
                getOpeningLectureTotalPages(pageNumber);
            });
        </script>
    </div> <!-- #opening-lectures -->
    <div id="attendance" class="tab-pane">
<?php else: ?>
        <h4>我的培训课</h4>
<?php endif; ?>
        <p class="no-courses">您暂未参加培训课. <a href="<?php echo $this->basePath(); ?>/training/lectures">查看近期开课</a></p>
        <ul id="attendance-records" class="courses"></ul>
        <ul id="attendance-pagination" class="inline pagination"></ul>
        <!-- Java Script -->
        <script type="text/javascript">
            function getLectureAttendance(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getLectureAttendance?&page=' + pageNumber,
                    dataType: 'JSON',
                    success: function(result) {
                        $('#attendance-records').empty();
                        if ( result['isSuccessful'] ) {
                            $('.no-courses').addClass('hide');
                            displayLectureAttendance(result['records']);
                        } else {
                            $('.no-courses').removeClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            function displayLectureAttendance(records) {
                var numberOfRecords = records.length;
                for ( var i = 0; i < numberOfRecords; ++ i ) {
                    var lectureString   = '',
                        commentString   = '';

                    lectureString   = '<li class="course row-fluid">'
                                    + '    <div class="span3">'
                                    + '        <img src="<?php echo $this->basePath(); ?>/img/categories/' + records[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                    + '    </div>'
                                    + '    <div class="span9">'
                                    + '        <h4>'
                                    + '            <a href="<?php echo $this->basePath(); ?>/training/lecture?lectureId=' + records[i]['lectureId'] + '">' + records[i]['courseName'] + '</a>'
                                    + '            <span class="extra">(报名序列号:' + records[i]['serialCode'] + ', 剩余次数: ' + (records[i]['remainTimes'] || '0') + '次)</span>'
                                    + '        </h4>'
                                    + '        <ul class="inline meta">'
                                    + '            <li><i class="icon-user"></i> <a href="<?php echo $this->basePath(); ?>/training/teacher?teacherId=' + records[i]['lectureTeacherId'] + '">' + records[i]['lectureTeacherName'] + '</a></li>'
                                    + '            <li><i class="icon-calendar"></i> ' + formatDateTime(records[i]['lectureStartTime']) + '~' + formatDateTime(records[i]['lectureEndTime']) + '</li>'
                                    + '            <li><i class="icon-map-marker"></i> ' + records[i]['lectureProvince'] + ( records[i]['lectureCity'] || '' ) + records[i]['lectureAddress'] + '</li>'
                                    + '        </ul>'
                                    + '    </div>'
                                    + '</li>';
                    $('#attendance-records').append(lectureString);
                    
                    if ( records[i]['lectureEndTime'] < '<?php echo date("Y-m-d H:i:s"); ?>' && records[i]['remainTimes'] != records[i]['totalTimes'] ) {
                        if ( records[i]['commentDetail'] != null ) {
                            commentString = getCommentString(records[i]['commentRanking'], records[i]['commentDetail']);
                        } else {
                            commentString = '<li id="comment-' + records[i]['lectureId'] + '" class="comment row-fluid">'
                                          + '    <div class="span3">'
                                          + '        发表评论<br />'
                                          + '        <span class="ranking-editable">' + getRankingString(0) + '</span>'
                                          + '    </div>'
                                          + '    <div class="span9">'
                                          + '        <textarea rows="2" placeholder="请在此填写评论"></textarea>'
                                          + '        <button class="btn btn-success btn-submit">提交</button>'
                                          + '    </div>'
                                          + '</li>';
                        }
                    } else {
                        commentString = '<li class="comment row-fluid"></li>';
                    }
                    $('#attendance-records').append(commentString);
                }
            }
        </script>
        <script type="text/javascript">
            function getCommentString(commentRanking, commentDetail) {
                commentString = '<li class="comment row-fluid">'
                              + '    <div class="span3">'
                              + '        我的评价<br />'
                              + '        <span class="ranking">' + getRankingString(parseInt(commentRanking, 10)) + '</span>'
                              + '    </div>'
                              + '    <div class="span9">'
                              + '        <p>' + commentDetail + '</p>'
                              + '    </div>'
                              + '</li>';
                return commentString;
            }
        </script>
        <script type="text/javascript">
            function getRankingString(rankingLevel) {
                var rankingImageString  = '';
                for ( var i = 0; i < rankingLevel; ++ i ) {
                    rankingImageString += '<img src="<?php echo $this->basePath(); ?>/img/ranking/full-star.png" alt="Star" />';
                }
                for ( var i = rankingLevel; i < 5; ++ i ) {
                    rankingImageString += '<img src="<?php echo $this->basePath(); ?>/img/ranking/empty-star.png" alt="Star" />';
                }
                return rankingImageString;
            }
        </script>
        <script type="text/javascript">
            function getRankingLevel(rankingObject, currentObject) {
                if ( typeof(currentObject) === 'undefined' ) {
                    return countRankingFullStars(rankingObject);
                } else {
                    return $(currentObject, rankingObject).index() + 1;
                }
            }
        </script>
        <script type="text/javascript">
            function countRankingFullStars(rankingObject) {
                var fullStars = 0;
                $('img', rankingObject).each(function() {
                    if ( $(this).attr('src').indexOf('full-star') > -1 ) {
                        ++ fullStars;
                    }
                });
                return fullStars;
            }
        </script>
        <script type="text/javascript">
            function getLectureAttendanceTotalPages(pageNumber) {
                $.ajax({
                    type: 'GET',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/getLectureAttendanceTotalPages',
                    dataType: 'JSON',
                    success: function(result) {
                        var paginationObject = $('#attendance-pagination');

                        $(paginationObject).empty();
                        if ( result['isSuccessful'] ) {
                            $(paginationObject).removeClass('hide');
                            displayPagination(pageNumber, result['totalPages'], paginationObject);
                        } else {
                            $(paginationObject).addClass('hide');
                        }
                    }
                });
            }
        </script>
        <script type="text/javascript">
            $('#attendance-pagination').delegate('li', 'click', function() {
                var currentPage = parseInt($('li.active > a', '#attendance-pagination').html(), 10),
                    pageNumber  = $('a', this).html();
                
                if ( pageNumber === '&lt;' ) {
                    pageNumber  = currentPage - 1;
                } else if ( pageNumber === '&gt;' ) {
                    pageNumber  = currentPage + 1;
                }
                getLectureAttendance(pageNumber);
                getLectureAttendanceTotalPages(pageNumber);
            });
        </script>
        <script type="text/javascript">
            $('ul#attendance-records').delegate('span.ranking-editable > img', 'click', function(event) {
                var rankingObject = $(this).parent('span'),
                    currentObject = $(this);
                $(rankingObject).html(getRankingString(getRankingLevel(rankingObject, currentObject)));
            });
        </script>
        <script type="text/javascript">
            $('ul#attendance-records').delegate('button.btn-submit', 'click', function() {
                var buttonObject        = $(this),
                    commentObject       = $(this).parent().parent(),
                    lectureId           = $(commentObject).attr('id').substring(8);
                    rankingObject       = $('span.ranking-editable', commentObject),
                    commentRanking      = getRankingLevel(rankingObject),
                    commentTextObject   = $('textarea', commentObject),
                    commentDetail       = $(commentTextObject).val();

                if ( commentRanking == 0 ) {
                    alert('请对课程进行评级.');
                    return;
                } else if ( commentDetail === '' ) {
                    alert('请填写对课程的评价');
                    return;
                }
                return createComment(lectureId, commentRanking, commentDetail, commentObject, buttonObject);
            });
        </script>
        <script type="text/javascript">
            function createComment(lectureId, commentRanking, commentDetail, commentObject, buttonObject) {
                $(buttonObject).attr('disabled', 'disabled');
                
                var postData = 'lectureId=' + lectureId + '&commentRanking=' + commentRanking + '&commentDetail=' + commentDetail;
                $.ajax({
                    type: 'POST',
                    async: true,
                    url: '<?php echo $this->basePath(); ?>/accounts/createComment',
                    data: postData,
                    dataType: 'JSON',
                    success: function(result) {
                        if ( result['isSuccessful'] ) {
                            var commentRanking = result['commentRanking'],
                                commentDetail  = result['commentDetail'];
                            $(commentObject).html(getCommentString(commentRanking, commentDetail));
                        } else {
                            alert('发生了未知错误, 请稍后再试.');
                        }
                        $(buttonObject).removeAttr('disabled');
                    }
                });
            }
        </script>
<?php if ( $profile['userGroupSlug'] === 'teacher' ): ?>
        </div> <!-- #tab-attendance -->
    </div> <!-- .tab-content -->
    <!-- Modals -->
    <div id="new-lecture-modal-step-1" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-header">
            <h4>创建新培训: 培训概要</h4>
        </div> <!-- .modal-header -->
        <div class="modal-body">
            <div id="new-lecture-error" class="alert alert-error hide"></div> <!-- #new-lecture-error -->
            <div class="row-fluid">
                <div class="span6">
                    <label for="course-name">课程名称</label>
                    <input id="course-name" type="text" disabled="disabled" />
                    <input id="course-id" type="hidden" />
                </div> <!-- .span6 -->
                <div class="span6">
                    <label for="expense">培训费用</label>
                    <div class="input-append">
                        <input class="span12" id="expense" type="text">
                        <span class="add-on">元</span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="city-picker row-fluid">
                <div class="span6">
                    <label for="lecture-address">开课地点</label>
                    <select class="region"></select>
                    <select class="city"></select>
                </div> <!-- .span6 -->
                <div class="span6">
                    <label>&nbsp;</label>
                    <select class="province"></select>
                    <input id="address" type="text" placeholder="详细地址" />
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="row-fluid">
                <div class="span6">
                    <label for="min-capcity">最小开班人数</label>
                    <div class="input-append">
                        <input class="span12" id="min-capcity" type="text">
                        <span class="add-on">人</span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
                <div class="span6">
                    <label for="max-capcity">课程最大容量</label>
                    <div class="input-append">
                        <input class="span12" id="max-capcity" type="text">
                        <span class="add-on">人</span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="row-fluid">
                <div class="control-group span6">
                    <label for="start-time">课程开始时间</label>
                    <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">
                        <input id="start-time" class="span12" type="text" value="" readonly>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
                <div class="control-group span6">
                    <label for="end-time">课程结束时间</label>
                    <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">
                        <input id="end-time" class="span12" type="text" value="" readonly>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="row-fluid">
                <div class="span12">
                    <label for="precautions">注意事项</label>
                    <textarea id="precautions" rows="4"></textarea>
                </div> <!-- .span12 -->
            </div> <!-- .row-fluid -->
        </div> <!-- .modal-body -->
        <div class="modal-footer">
            <button id="new-lecture-next-step" class="btn btn-primary">下一步</button>
            <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
        </div> <!-- .modal-footer -->
    </div> <!-- #new-lecture-modal-step-1 -->
    <div id="new-lecture-modal-step-2" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-header">
            <h4>创建新培训: 课程计划</h4>
        </div> <!-- .modal-header -->
        <div class="modal-body">
            <div class="loading">
                <img src="<?php echo $this->basePath(); ?>/img/loading.gif" alt="Loading">
            </div> <!-- .loading -->
            <div id="schedule-error" class="alert alert-error hide"></div> <!-- #schedule-error -->
            <ul id="lecture-modules"></ul>
            <input id="lecture-id" type="hidden" />
        </div> <!-- .modal-body -->
        <div class="modal-footer">
            <button id="new-lecture-complete" class="btn btn-primary">完成</button>
            <button class="btn" disabled="disabled">取消</button>
        </div> <!-- .modal-footer -->
    </div> <!-- #new-lecture-modal-step-2 -->
    <!-- JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.citypicker.js"></script>
    <script type="text/javascript">
        $('.city-picker').cityPicker();
    </script>
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/bootstrap.datetimepicker.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/bootstrap.datetimepicker.zh-CN.js"></script>
    <script type="text/javascript">
        function initializeDateTimePicker(startTime, endTime) {
            if ( typeof(startTime) == 'undefined' ) {
                startTime = '<?php echo date('Y-m-d H:i'); ?>';
            }
            if ( typeof(startTime) == 'undefined' ) {
                endTime = '2099-12-31 23:59';
            }
            $('.form_datetime').datetimepicker({
                language:  'zh-CN',
                weekStart: 1,
                todayBtn:  1,
                autoclose: 1,
                todayHighlight: 1,
                startView: 2,
                startDate: startTime,
                endDate: endTime,
                forceParse: 0,
                showMeridian: 1
            });
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function() {
            var pageNumber  = 1;

            initializeDateTimePicker();
            getOpeningCourses(pageNumber);
            getOpeningCourseTotalPages(pageNumber);
            getLectureAttendance(pageNumber);
            getLectureAttendanceTotalPages(pageNumber);
        });
    </script>
    <script type="text/javascript">
        $('.nav a[href=#lectures]').click(function() {
            var pageNumber  = 1;

            getOpeningLectures(pageNumber);
            getOpeningLectureTotalPages(pageNumber);
        });
    </script>
    <script type="text/javascript">
        $('#new-lecture-next-step').click(function() {
            var courseId        = $('#course-id').val(),
                startTime       = $('#start-time').val(),
                endTime         = $('#end-time').val(),
                region          = $('.region').val(),
                province        = $('.province').val(),
                city            = $('.city').val(),
                address         = $('#address').val(),
                minCapcity      = $('#min-capcity').val(),
                maxCapcity      = $('#max-capcity').val(),
                expense         = $('#expense').val(),
                precautions     = $('#precautions').val();

            $('#new-lecture-error').addClass('hide');
            $(this).html('正在处理...');
            $(this).attr('disabled', 'disabled');
            return createLecture(courseId, startTime, endTime, region, province, city, 
                                 address, minCapcity, maxCapcity, expense, precautions);
        });
    </script>
    <script type="text/javascript">
        function createLecture(courseId, startTime, endTime, region, province, city, address, minCapcity, maxCapcity, expense, precautions) {
            var postData = 'courseId=' + courseId + '&startTime=' + startTime + '&endTime=' + endTime + '&region=' + region + 
                          '&province=' + province + '&city=' + city + '&address=' + address + '&minCapcity=' + minCapcity + 
                          '&maxCapcity=' + maxCapcity + '&expense=' + expense + '&precautions=' + precautions;
            $.ajax({
                type: 'POST',
                async: true,
                url: '<?php echo $this->basePath(); ?>/accounts/createLecture',
                data: postData,
                dataType: 'JSON',
                success: function(result) {
                    if ( result['isSuccessful'] ) {
                        getCourseModules(courseId, startTime, endTime);
                        $('#new-lecture-modal-step-1').modal('hide');
                        $('#new-lecture-modal-step-2 #lecture-id').val(result['lectureId']);
                        $('#new-lecture-modal-step-2').modal({
                            'backdrop': 'static',
                        });
                    } else {
                        var errorMessage  = '';
                        if ( !result['isCourseIdLegal'] ) {
                            errorMessage += '您没有权限创建本课程的培训课<br>'
                        }
                        if ( result['isExpenseEmpty'] ) {
                            errorMessage += '请填写您培训课的培训费用<br>';
                        } else if ( !result['isExpenseLegal'] ) {
                            errorMessage += '培训费用必须为大于0元的整数<br>';
                        }
                        if ( result['isRegionEmpty'] ) {
                            errorMessage += '请选择您培训课的开课地区<br>';
                        }
                        if ( result['isProvinceEmpty'] ) {
                            errorMessage += '请选择您培训课的开课省份<br>';
                        }
                        if ( result['isCityEmpty'] ) {
                            errorMessage += '请选择您培训课的开课城市<br>';
                        }
                        if ( result['isAddressEmpty'] ) {
                            errorMessage += '请填写您培训课的开课地点<br>';
                        }
                        if ( result['isMinCapcityEmpty'] ) {
                            errorMessage += '请填写您培训课的最小开班人数<br>';
                        } else if ( !result['isMinCapcityLegal'] ) {
                            errorMessage += '请填写合理的最小开班人数<br>';
                        }
                        if ( result['isMaxCapcityEmpty'] ) {
                            errorMessage += '请填写您培训课的最大容纳人数<br>';
                        } else if ( !result['isMaxCapcityLegal'] ) {
                            errorMessage += '请填写合理的最大容纳人数<br>';
                        }
                        if ( result['isStartTimeEmpty'] ) {
                            errorMessage += '请选择您培训课起始时间<br>'
                        } else if ( !result['isStartTimeLegal'] ) {
                            errorMessage += '您培训课起始时间不得早于当前时间<br>'
                        }
                        if ( result['isEndTimeEmpty'] ) {
                            errorMessage += '请选择您培训课结束时间<br>'
                        } else if ( !result['isEndTimeLegal'] ) {
                            errorMessage += '您培训课结束时间不得早于起始时间<br>'
                        }
                        if ( result['isPrecautionsEmpty'] ) {
                            errorMessage += '请填写参加本次培训课的注意事项<br>';
                        }
                        $('#new-lecture-error').html(errorMessage);
                        $('#new-lecture-error').removeClass('hide');
                    }
                    $('#new-lecture-next-step').html('确认');
                    $('#new-lecture-next-step').removeAttr('disabled');
                }
            });
        }
    </script>
    <script type="text/javascript">
        function getCourseModules(courseId, startTime, endTime) {
            $('#lecture-modules').empty();
            $.ajax({
                type: 'GET',
                async: true,
                url: '<?php echo $this->basePath(); ?>/accounts/getCourseModules?courseId=' + courseId,
                dataType: 'JSON',
                success: function(result) {
                    if ( result['isSuccessful'] ) {
                        $('#new-lecture-modal-step-2 .loading').addClass('hide');

                        var length = result['courseModules'].length;
                        for ( var i = 0; i < length; ++ i ) {
                            $('#lecture-modules').append('<li class="lecture-module">' +
                                                         '    <div class="row-fluid">' +
                                                         '        <div class="span6">' +
                                                         '            <span class="module-name"><strong>' + result['courseModules'][i]['courseModuleName'] + '</strong></span>' +
                                                         '            <span class="module-id hide">' + result['courseModules'][i]['courseModuleId'] + '</span>' +
                                                         '        </div>' +
                                                         '        <div class="span6">' +
                                                         '            培训时间: <span class="module-cycle">' + result['courseModules'][i]['courseModuleCycle'] + '</span> 分钟' +
                                                         '        </div>' +
                                                         '    </div>' +
                                                         '    <div class="row-fluid">' +
                                                                 formatDateTimePicker('module-start-time', '课程模块起始时间') +
                                                                 formatDateTimePicker('module-end-time', '课程模块结束时间') +
                                                         '    </div>' +
                                                         '</li>');
                        }
                        initializeDateTimePicker(startTime, endTime);
                    } else {
                        $('#new-lecture-modal-step-2 .loading').removeClass('hide');
                        alert('发生了未知错误, 请联系技术支持人员.');
                    }
                }
            });
        }
    </script>
    <script type="text/javascript">
        function formatDateTimePicker(controlClass, labelText) {
            return '<div class="control-group span6">' +
                   '    <label for="' + controlClass + '">' + labelText + '</label>' +
                   '    <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">' +
                   '        <input class="' + controlClass + ' span12" type="text" readonly>' +
                   '        <span class="add-on"><i class="icon-th"></i></span>' +
                   '    </div>' +
                   '</div>';
        }
    </script>
    <script type="text/javascript">
        $('#lecture-modules').delegate('.module-start-time', 'change', function() {
            var endTimeControl  = $('.module-end-time', $(this).parent().parent().parent().parent()),
                cycleControl    = $('.module-cycle', $(this).parent().parent().parent().parent().parent()),
                startTime       = new Date($(this).val()),
                cycle           = $(cycleControl).html();
                endTime         = new Date(startTime.getTime() + parseInt(cycle, 10) * 60000);
            $(endTimeControl).val(getDateTime(endTime));
        });
    </script>
    <script type="text/javascript">
        function getDateTime(dateTimeString) {
            var dateTime = 
                year     = dateTime.getFullYear(),
                month    = formatNumber(dateTime.getMonth() + 1),
                day      = formatNumber(dateTime.getDate()),
                hour     = formatNumber(dateTime.getHours()),
                minute   = formatNumber(dateTime.getMinutes());
            return year + '-' + month + '-' + day + ' ' + hour + ':' + minute;
        }
    </script>
    <script type="text/javascript">
        function formatNumber(number) {
            if ( number < 10 ) {
                return '0' + number;
            }
            return number;
        }
    </script>
    <script type="text/javascript">
        $('#new-lecture-complete').click(function() {
            $(this).html('正在处理...');
            $(this).attr('disabled', 'disabled');
            $('#schedule-error').addClass('hide');

            if ( errorMessage = isScheduleLegal() ) {
                $('#schedule-error').html(errorMessage);
                $('#schedule-error').removeClass('hide');
                
                $(this).html('确认');
                $(this).removeAttr('disabled');
            } else {
                return createLectureSchedule();
            }
        });
    </script>
    <script type="text/javascript">
        function createLectureSchedule() {
            var courseModules = $('li.lecture-module').length;
            $('li.lecture-module').each(function(index) {
                var lectureId       = $('#lecture-id').val(),
                    courseModuleId  = $('.module-id', $(this)).html(),
                    startTime       = $('.module-start-time', $(this)).val(),
                    endTime         = $('.module-end-time', $(this)).val(),
                    postData        = 'lectureId=' + lectureId + '&courseModuleId=' + courseModuleId + 
                                     '&startTime=' + startTime + '&endTime=' + endTime;
                $.ajax({
                    type: 'POST',
                    async: false,
                    url: '<?php echo $this->basePath(); ?>/accounts/createLectureSchedule',
                    data: postData,
                    dataType: 'JSON',
                    success: function(result) {
                        if ( result['isSuccessful'] ) {
                        } else {
                            alert('发生了未知错误, 请联系技术支持人员.')
                        }
                        if ( index == courseModules - 1 ) {
                            $('.btn-primary', '#new-lecture-modal-step-2').html('确认');
                            $('.btn-primary', '#new-lecture-modal-step-2').removeAttr('disabled');
                            $('#new-lecture-modal-step-2').modal('hide');
                        }
                    }
                });
            });
        }
    </script>
    <script type="text/javascript">
        function isScheduleLegal() {
            var errorMessage    = '';
            $('li.lecture-module').each(function() {
                var moduleName  = $('.module-name', $(this)).html(),
                    startTime   = $('.module-start-time', $(this)).val(),
                    endTime     = $('.module-end-time', $(this)).val();
                if ( startTime.length == 0 ) {
                    errorMessage += '请选择' + moduleName + '的培训起始时间<br>';
                }
                if ( endTime.length == 0 ) {
                    errorMessage += '请选择' + moduleName + '的培训结束时间<br>';
                }

                startTime   = new Date(startTime);
                endTime     = new Date(endTime);
                if ( startTime.getTime() > endTime.getTime() ) {
                    errorMessage += moduleName + '的培训结束时间不得早于起始时间<br>';
                }
            });
            return errorMessage;
        }
    </script>
<?php else: ?>
    <script type="text/javascript">
        $(document).ready(function() {
            var pageNumber  = 1;
            getLectureAttendance(pageNumber);
            getLectureAttendanceTotalPages(pageNumber);
        });
    </script>
<?php endif; ?>
    <script type="text/javascript">
        function formatDateTime(dateTimeString) {
            var year    = dateTimeString.substring(0, 4),
                month   = dateTimeString.substring(5, 7),
                day     = dateTimeString.substring(8, 10),
                time    = dateTimeString.substring(11, 16);
            return year + '年' + month + '月' + day + '日 ' + time;
        }
    </script>
    <script type="text/javascript">
        function displayPagination(currentPage, totalPages, paginationObject) {
            var lowerBound = ( currentPage - 3 > 0 ? currentPage - 3 : 1 ),
                upperBound = ( currentPage + 3 < totalPages ? currentPage + 3 : totalPages );
            var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="javascript:void(0)">&lt;</a></li>';

            for ( var i = lowerBound; i <= upperBound; ++ i ) {
                paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="javascript:void(0)">' + i + '</a></li>';
            }
            paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="javascript:void(0)">&gt;</a></li>';
            $(paginationObject).append(paginationString);
        }
    </script>