<?php if ( $profile['userGroupSlug'] === 'teacher' ): ?>
    <h4>我收到的需求</h4>
    <p class="no-requirements">暂无用户向您提出需求.</p>
    <ul id="requirements"></ul>
    <!-- JavaScript -->
    <script type="text/javascript">
        
    </script>
<?php else: ?>
    <h4>我的需求<span class="pull-right"><a id="new-requirement" href="javascript:void(0);"><i class="icon-plus"></i> 新需求</a></span></h4>
    <p class="no-requirements">暂无需求定制记录.</p>
    <ul id="requirements"></ul>
    <!-- Modals -->
    <div id="requirement-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-header">
            <h4>创建新需求</h4>
        </div> <!-- .modal-header -->
        <div class="modal-body">
        <?php if ( $profile['userGroupSlug'] === 'person' ): ?>
            <div class="alert alert-info">个人用户所提出的需求我们将在达到一定人数时受理.<a class="close" data-dismiss="alert" href="#">&times;</a></div>
        <?php endif; ?>
            <div id="requirement-error" class="alert alert-error hide"></div>
            <div class="row-fluid">
                <div class="span6">
                    <label for="teacher-name">讲师</label>
                    <input id="teacher-name" type="text" />
                    <table id="teacher-hint" class="hint"></table>
                    <input id="teacher-uid" type="hidden" />
                </div> <!-- .span6 -->
                <div class="span6">
                    <label for="course-name">课程</label>
                    <input id="course-name" type="text" />
                    <table id="course-hint" class="hint"></table>
                    <input id="course-id" type="hidden" />
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
            <div class="row-fluid">
                <div class="span6">
                    <label for="lecture-time">开课时间</label>
                    <select id="lecture-time">
                    <?php 
                        $year       = date('Y');
                        $month      = date('m');
                        $MIN_MONTH  = 1;
                        $MAX_MONTH  = 12;
                    ?>
                    <?php for ( $i = $month; $i <= $MAX_MONTH; ++ $i ): ?>
                        <option value="<?php echo $i; ?>"><?php echo $year; ?>年<?php echo sprintf('%02d', $i); ?>月</option>
                    <?php endfor; ?>
                    <?php for ( $i = $MIN_MONTH; $i < $month; ++ $i ): ?>
                        <option value="<?php echo $i; ?>"><?php echo $year + 1; ?>年<?php echo sprintf('%02d', $i); ?>月</option>
                    <?php endfor; ?>
                    </select>
                </div> <!-- .span6 -->
            <?php if ( $profile['userGroupSlug'] === 'company' ): ?>
                <div class="span6">
                    <label for="participants">参课人数</label>
                    <div class="input-append">
                        <input id="lecture-participants" class="span12" type="text" />
                        <span class="add-on">人</span>
                    </div> <!-- .input-append -->
                </div> <!-- .span6 -->
            <?php endif; ?>
            </div> <!-- .row-fluid -->
            <div class="city-picker row-fluid">
                <div class="span6">
                    <label for="lecture-place">开课地点</label>
                    <select class="region"></select>
                    <select class="city"></select>
                </div> <!-- .span6 -->
                <div class="span6">
                    <label>&nbsp;</label>
                    <select class="province"></select>
                <?php if ( $profile['userGroupSlug'] === 'company' ): ?>
                    <input id="address" type="text" placeholder="详细地址" />
                <?php endif; ?>
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
        <?php if ( $profile['userGroupSlug'] === 'company' ): ?>
            <div class="row-fluid">
                <div class="span12">
                    <label for="requirement-detail">详细需求</label>
                    <textarea id="requirement-detail" rows="6"></textarea>
                </div> <!-- .span6 -->
            </div> <!-- .row-fluid -->
        <?php endif; ?>
        </div> <!-- .modal-body -->
        <div class="modal-footer">
            <button class="btn btn-primary">确认</button>
            <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
        </div> <!-- .modal-footer -->
    </div> <!-- #requirement-modal -->
    <!-- Java Script -->
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.citypicker.js"></script>
    <script type="text/javascript">
        $('.city-picker').cityPicker();
    </script>
    <script type="text/javascript">
        $('#new-requirement').click(function() {
            $('#requirement-modal').modal();
        });
    </script>
    <script type="text/javascript">
        $('#requirement-modal button.btn-primary').click(function() {
            $('#requirement-modal').modal('hide');
        });
    </script>
    <script type="text/javascript">
        $('#teacher-name').keyup(function() {
            var keyword = $(this).val();
            $.ajax({
                type: 'GET',
                async: true,
                url: '<?php echo $this->basePath(); ?>/home/getSearchResult?keyword=' + keyword,
                dataType: 'JSON',
                success: function(result) {
                    $('#teacher-hint').empty();
                    if ( result['isSuccessful'] ) {
                        return displayTeacherHint(result['searchResult']['teachers']);
                    } else {
                        $('#teacher-hint').append('<tr><td>未找到相关的讲师.</td></tr>');
                    }
                }
            });
        });
    </script>
    <script type="text/javascript">
        function displayTeacherHint(result) {
            var numberOfTeachers = result.length;
            for ( var i = 0; i < numberOfTeachers; ++ i ) {
                $('#teacher-hint').append('<tr>' +
                                          '    <td class="span4"><img src="' + ( result[i]['avatar'] || '<?php echo $this->basePath(); ?>/img/avatars/avatar.jpg' ) + '" alt="avatar" /></td>' + 
                                          '    <td class="hide">' + result[i]['uid'] + '</td>' + 
                                          '    <td>' + result[i]['teacherName'] + '</td>' + 
                                          '</tr>');
            }
            $('#teacher-hint').css('display', 'table');
        }
    </script>
    <script type="text/javascript">
        $('#teacher-hint').delegate('tr', 'click', function() {
            var teacherId   = $('td:eq(1)', this).html(),
                teacherName = $('td:eq(2)', this).html();
            
            $('#teacher-uid').val(teacherId);
            $('#teacher-name').val(teacherName);
            $('#teacher-hint').css('display', 'none');
        });
    </script>
    <script type="text/javascript">
        $('#course-name').keyup(function() {
            var keyword = $(this).val();
            $.ajax({
                type: 'GET',
                async: true,
                url: '<?php echo $this->basePath(); ?>/home/getSearchResult?keyword=' + keyword,
                dataType: 'JSON',
                success: function(result) {
                    $('#course-hint').empty();
                    if ( result['isSuccessful'] ) {
                        return displayCourseHint(result['searchResult']['courses']);
                    } else {
                        $('#course-hint').append('<tr><td>未找到相关的课程.</td></tr>');
                    }
                }
            });
        });
    </script>
    <script type="text/javascript">
        function displayCourseHint(result) {
            var numberOfCourses = result.length;
            for ( var i = 0; i < numberOfCourses; ++ i ) {
                $('#course-hint').append('<tr>' +
                                         '    <td class="hide">' + result[i]['courseId'] + '</td>' +
                                         '    <td>' + result[i]['courseName'] + '</td>' +
                                         '    <td class="hide">' + result[i]['teacherId'] + '</td>' +
                                         '    <td class="hide">' + result[i]['teacherName'] + '</td>' +
                                         '</tr>');
            }
            $('#course-hint').css('display', 'table');
        }
    </script>
    <script type="text/javascript">
        $('#course-hint').delegate('tr', 'click', function() {
            var courseId    = $('td:eq(0)', this).html(),
                courseName  = $('td:eq(1)', this).html(),
                teacherId   = $('td:eq(2)', this).html(),
                teacherName = $('td:eq(3)', this).html();
            
            $('#course-id').val(courseId);
            $('#course-name').val(courseName);
            $('#teacher-id').val(teacherId);
            $('#teacher-name').val(teacherName);
            $('#course-hint').css('display', 'none');
        });
    </script>
<?php endif; ?>

<!-- JavaScript -->
<script type="text/javascript">
    function getTeacher(teacherId) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/training/getTeacher?teacherId=' + teacherId,
            dataType: 'JSON',
            success: function(result) {
                if ( result['isSuccessful'] ) {
                    $('#teacher-uid').val(result['teacher']['uid']);
                    $('#teacher-name').val(result['teacher']['teacherName']);
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function getCourse(courseId) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/training/getCourse?courseId=' + courseId,
            dataType: 'JSON',
            success: function(result) {
                if ( result['isSuccessful'] ) {
                    $('#course-id').val(result['course']['courseId']);
                    $('#course-name').val(result['course']['courseName']);
                    $('#teacher-id').val(result['teacher']['teacherId']);
                    $('#teacher-name').val(result['teacher']['teacherName']);
                }
            }
        });
    }
</script>
<script type="text/javascript">
    $(document).ready(function() {
        var parameter       = window.location.href.match(/\?.*$/);
        if ( parameter != null ) {
            var parameters  = parameter[0].substring(1).split('=');
                key         = parameters[0],
                value       = parameters[1];
            if ( key == 'courseId' ) {
                getCourse(value);
            } else if ( key == 'teacherUid' ) {
                getTeacher(value);
            }
            $('#requirement-modal').modal();
        }
    });
</script>