<?php 
    echo $this->headTitle($teacher['teacher_name'].' | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/courses/profile.css');
?>

<div id="content">
	<div id="introduction">
		<div class="section">
			<div id="avatar">
				<?php if ( $teacher['teacher_avatar'] == null ): ?>
					<img class="img-circle" src="<?php echo $this->basePath(); ?>/img/avatar.png" alt="Avatar" />
				<?php else: ?>
					<img class="img-circle" src="<?php echo $this->basePath($teacher['teacher_avatar']); ?>" alt="Avatar" />
				<?php endif; ?>
			</div> <!-- #avatr -->
			<div id="brief">
				<div id="name"><?php echo $teacher['teacher_name']; ?></div>
				<div id="company"><?php echo $teacher['teacher_company']; ?></div>
			</div> <!-- #brief -->
			<div id="reserve">
				<button class="btn btn-danger">预约讲师</button>
			</div> <!-- #reserve -->
		</div> <!-- .section -->
		<div class="section">
			<h2>讲师简介</h2>
			<p><?php echo $teacher['teacher_brief']; ?></p>
		</div> <!-- .section -->
		<div class="section">
			<h2>擅长领域</h2>
			<p><?php echo $teacher['teacher_field']; ?></p>
		</div> <!-- .section -->
		<div class="section">
			<h2>开设课程</h2>
			<?php if ( $courses == null ): ?>
				<p>暂无开设课程</p>
			<?php else: ?>
			<ul>
				<?php foreach ( $courses as $course ) { ?>
				<li><a href="<?php echo $this->basePath('/courses/course/detail/'.$course['course_id']); ?>" target="_blank"><?php echo $course['course_name']; ?></a></li>
				<?php } ?>
			</ul>
			<?php endif; ?>
		</div> <!-- .section -->
	</div> <!-- .section -->
</div> <!-- #content -->