<?php 
    echo $this->headTitle('页面未找到 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/training/style.css')
                          ->appendStylesheet($this->basePath().'/css/404.css');
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath('/'); ?>">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
            </a>
        </div>
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath(); ?>/training/lectures">近期培训</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/courses">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/teachers">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#requirements">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/posts">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/accounts/register'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?php echo $this->basePath(); ?>/home/search">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container row-fluid">
        <div class="span6">
            <img src="<?php echo $this->basePath(); ?>/img/404.png" alt="Header Image">
        </div> <!-- .span6 -->
        <div class="span6">
            <h2>页面未找到</h2>
            <p>很抱歉, 我们无法为您加载您所请求的页面..</p>
            <button class="btn btn-orange" onclick="history.go(-1);">返回</button>
        </div> <!-- .span6 -->
    </div> <!-- .container -->
    <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
    <div id="debug" class="container row-fluid">
        <h4><?php echo $this->translate('An error occurred') ?></h4>
        <h5><?php echo $this->message ?></h5>
        <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
            <hr/>
            <h5><?php echo $this->translate('Additional information') ?>:</h5>
            <h6><?php echo get_class($this->exception); ?></h6>
            <dl>
                <dt><?php echo $this->translate('File') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                </dd>
                <dt><?php echo $this->translate('Message') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getMessage()) ?></pre>
                </dd>
                <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
                </dd>
            </dl>
            <?php
                $e = $this->exception->getPrevious();
                if ($e) :
            ?>
                <hr/>
                <h5><?php echo $this->translate('Previous exceptions') ?>:</h5>
                <ul class="unstyled">
                    <?php while($e) : ?>
                    <li>
                        <h6><?php echo get_class($e); ?></h6>
                        <dl>
                            <dt><?php echo $this->translate('File') ?>:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                            </dd>
                            <dt><?php echo $this->translate('Message') ?>:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getMessage()) ?></pre>
                            </dd>
                            <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getTraceAsString()) ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php
                        $e = $e->getPrevious();
                        endwhile;
                    ?>
                </ul>
            <?php endif; ?>
        <?php else: ?>
            <h6><?php echo $this->translate('No Exception available') ?></h6>
        <?php endif ?>
    </div> <!-- #debug -->
    <?php endif ?>
</div> <!-- #container -->
