<?php 
    echo $this->headTitle('开放平台 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/about/api.css')
                          ->appendStylesheet($this->basePath().'/css/about/highlight.css');
    echo $this->headScript()->appendFile($this->basePath().'/js/highlight.js');
?>

<div id="header" class="container">
    <div class="row-fluid">
        <div id="logo" class="span3">
            <a href="<?php echo $this->basePath(); ?>">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div class="span9">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath(); ?>/training/lectures">近期培训</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/courses">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/teachers">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#requirement">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/posts">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('itp_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/accounts/register'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
                <?php endif; ?>
            </ul>
        </div> <!-- .span9 -->
    </div> <!-- #container -->
</div> <!-- #header -->
<div id="hero">
    <div class="container">
        <h1>API文档</h1>
        <p>所有的API仅供内部开发使用.</p>
    </div> <!-- #container -->
</div> <!-- #hero -->
<div id="container" class="container">
    <div class="row-fluid">
        <div id="sidebar" class="span3">
            <ul class="nav nav-list affix">
                <li><a href="#models">基础数据结构</a></li>
                <li><a href="#lectures">培训课API</a></li>
                <li><a href="#courses">课程API</a></li>
                <li><a href="#teacher">讲师API</a></li>
                <li><a href="#posts">培训动态API</a></li>
                <li><a href="#accounts">用户API</a></li>
                <li><a href="#other">其他API</a></li>
            </ul>
        </div> <!-- .span3 -->
        <div id="content" class="span9">
            <section id="models">
                <h1 class="page-header">基础数据结构</h1>
                <h2>课程类别/授课领域(Course Types)</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>名称</th>
                            <th>类型</th>
                            <th>描述</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tbody>
                </table>
                <h2>培训课(Lecture)</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>名称</th>
                            <th>类型</th>
                            <th>描述</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tbody>
                </table>
                <h2>课程(Course)</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>名称</th>
                            <th>类型</th>
                            <th>描述</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tbody>
                </table>
                <h2>课程模块(Course Module)</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>名称</th>
                            <th>类型</th>
                            <th>描述</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tbody>
                </table>
                <h2>讲师(Teacher)</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>名称</th>
                            <th>类型</th>
                            <th>描述</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tbody>
                </table>
                <h2>培训动态(Post)</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>名称</th>
                            <th>类型</th>
                            <th>描述</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tbody>
                </table>
            </section> <!-- #models -->
            <section id="lectures">
                <h1 class="page-header">培训课API</h1>
            </section> <!-- #lectures -->
            <section id="courses">
                <h1 class="page-header">课程API</h1>
            </section>
            <section id="teacher">
                <h1 class="page-header">讲师API</h1>
            </section>
            <section id="posts">
                <h1 class="page-header">培训动态API</h1>
            </section>
            <section id="accounts">
                <h1 class="page-header">用户API</h1>
            </section>
            <section id="other">
                <h1 class="page-header">其他API</h1>
            </section>
        </div> <!-- .span9 -->
    </div> <!-- .row-fluid -->
</div> <!-- #container -->

<script type="text/javascript">
    $(document).ready(function() {
        // Initialize Sidebar
        $('.nav').affix({
            'offset': 200
        });
        // Register Scroll Event
        $('body').attr('data-spy', 'scroll');
        $('body').attr('data-target', '#sidebar');

        // Highlight.js
        $('pre').each(function(i, bloc ) {
            hljs.highlightBlock(block);
        });
    });
</script>