<?= $this->headTitle('合作伙伴 | '); ?>
<?= $this->headLink()->appendStylesheet($this->cdn('/css/about/style.css'))
                     ->appendStylesheet($this->cdn('/css/about/partner.css')); ?>

<div id="header" class="container">
    <div class="row-fluid">
        <div id="logo" class="span3">
            <a href="<?= $this->basePath('/'); ?>">
                <img src="<?= $this->cdn('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div class="span9">
            <ul class="inline">
                <li><a href="<?= $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?= $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?= $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?= $this->basePath('/accounts/dashboard#requirements'); ?>">需求定制</a></li>
                <li><a href="<?= $this->basePath('/training/posts'); ?>">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?= $this->basePath('/accounts/login'); ?>"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?= $this->basePath('/accounts/register'); ?>'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?= $this->basePath('/accounts/dashboard'); ?>"><?= $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?= $this->basePath('/accounts/logout'); ?>">注销</a></li>
                <?php endif; ?>
            </ul>
        </div> <!-- .span9 -->
    </div> <!-- #container -->
</div> <!-- #header -->
<div id="hero">
    <div class="container">
        <h1>合作伙伴</h1>
        <p>同心协力, 一起共建美好未来.</p>
    </div> <!-- #container -->
</div> <!-- #hero -->
<div id="container" class="container">
    <div class="row-fluid">
        <div id="sidebar" class="span3">
            <ul class="nav nav-list">
                <li><a href="<?= $this->basePath('/about'); ?>">关于我们</a></li>
                <li class="active"><a href="<?= $this->basePath('/about/partner'); ?>">合作伙伴</a></li>
                <li><a href="<?= $this->basePath('/about/join'); ?>">诚招英才</a></li>
                <li><a href="<?= $this->basePath('/about/support'); ?>">帮助中心</a></li>
                <li><a href="<?= $this->basePath('/about/feedback'); ?>">意见反馈</a></li>
                <li><a href="<?= $this->basePath('/about/term'); ?>">服务条款</a></li>
                <li><a href="<?= $this->basePath('/about/api'); ?>">开放平台</a></li>
            </ul>
        </div> <!-- .span3 -->
        <div id="content" class="span9">
            <h2>开发者服务战略合作伙伴</h2>
            <ul class="inline">
                <li><a href="https://www.aliyun.com"><img src="<?= $this->cdn('/img/about/partners/aliyun.png'); ?>" alt="Aliyun"></a></li>
                <li><a href="https://github.com"><img src="<?= $this->cdn('/img/about/partners/github.png'); ?>" alt="GitHub"></a></li>
                <li><a href="https://travis-ci.org"><img src="<?= $this->cdn('/img/about/partners/travis-ci.png'); ?>" alt="TravisCI"></a></li>
                <li><a href="https://www.alipay.com"><img src="<?= $this->cdn('/img/about/partners/alipay.png'); ?>" alt="Alipay"></a></li>
                <li><a href="https://www.coding.net"><img src="<?= $this->cdn('/img/about/partners/coding-net.png'); ?>" alt="Coding.net"></a></li>
                <li><a href="https://www.upyun.com"><img src="<?= $this->cdn('/img/about/partners/upyun.png'); ?>" alt="UPYun"></a></li>
            </ul>
            <h2>社区媒体合作伙伴</h2>
            <div class="row-fluid">
                <div class="span4">
                </div> <!-- .span4 -->
                <div class="span4">
                </div> <!-- .span4 -->
                <div class="span4">
                </div> <!-- .span4 -->
            </div> <!-- .row-fluid -->
        </div> <!-- .span9 -->
    </div> <!-- .row-fluid -->
</div> <!-- #container -->