<?php 
    echo $this->headTitle('讲师团队 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/solutions/style.css');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/solutions/teachers.css');
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath(); ?>/solutions/lecture">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/solutions/teacher">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard/requirement">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/solutions/news">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('itp_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/accounts/register'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?php echo $this->basePath(); ?>/solutions/search">
                <input type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div id="sub-header">
            <h2>讲师团队</h2>
            <p>卓越的讲师团队! 选择适合您的培训讲师.</p>
            <button class="btn btn-orange">创建账户</button>
            <img src="<?php echo $this->basePath(); ?>/img/solutions/course-header.jpg" alt="Header Image">
            <div class="border-bottom"></div> <!-- .border-bottom -->
        </div> <!-- #sub-header -->
        <div id="content" class="row-fluid">
            <div class="span3">
                <h4>筛选讲师</h4>
                <h5>授课领域</h5>
                <ul id="course-types" class="inline">
                    <li class="active"><a href="#">全部领域</a></li>
                    <?php foreach ( $courseTypes as $courseType ): ?>
                    <li><a href="#"><?php echo $courseType->course_type_name; ?></a></li>
                    <?php endforeach; ?>
                </ul>
                <button class="btn btn-success">筛选</button>
            </div> <!-- .span3 -->
            <div class="span9">
                <ul id="teachers" class="thumbnails">
                    <?php foreach ( $teachers as $teacher ): ?>
                    <li class="teacher span2">
                        <div class="thumbnail">
                            <div class="avatar" style="background-color: #427fed">
                                <img data-src="holder.js/150x150" src="<?php echo $this->basePath(); ?>/img/avatars/silhouette.png" alt="Avatar" />
                            </div>
                            <a href="<?php echo $this->basePath(); ?>/solutions/teacher/detail/<?php echo $teacher->uid; ?>"><h5><?php echo $teacher->teacher_name; ?></h5></a>
                            <div class="company"><?echo $teacher->teacher_company; ?></div>
                            <div class="field"><?echo $teacher->teacher_field; ?></div>
                            <div class="reserve"><button class="btn btn-orange btn-block">预约</button></div>
                        </div> <!-- .thumbnail -->
                    </li> <!-- .span2 -->
                    <?php endforeach; ?>
                </ul> <!-- .thumbnails -->
                <div id="pagination" class="pagination pagination-centered">
                <ul>
                <?php
                    $basePath = $this->basePath().'/solutions/teacher/page/';
                ?>
                <?php if ( $currentPageNumber > 1 ): ?>
                    <li><a href="<?php echo $basePath.($currentPageNumber - 1); ?>">&lt;</a></li>
                <?php else: ?>
                    <li class="disabled"><a>&lt;</a></li>
                <?php endif; ?>
                <?php
                    $lowerBound     = $currentPageNumber - 5;
                    $lowerBound     = ( $lowerBound > 0 ) ? $lowerBound : 1;
                    $upperBound     = $currentPageNumber + 4;
                    $upperBound     = ( $upperBound <= $numberOfPages ) ? $upperBound : $numberOfPages;
                    $catelogySlug   = $catelogySlug;

                    for ( $i = $lowerBound; $i <= $upperBound; ++ $i ) {
                        if ( $i == $currentPageNumber ) {
                            echo "<li class=\"active\"><a>$i</a></li>";
                        } else {
                            if ( $catelogySlug == null ) {
                                echo "<li><a href=\"$basePath$i\">$i</a></li>";
                            } else {
                                echo "<li><a href=\"$basePath$i?catelogySlug=$catelogySlug\">$i</a></li>";
                            }
                        }
                    }
                ?>
                <?php if ( $currentPageNumber < $numberOfPages ): ?>
                    <li><a href="<?php echo $basePath.($currentPageNumber + 1); ?>">&gt;</a></li>
                <?php else: ?>
                    <li class="disabled"><a>&gt;</a></li>
                <?php endif; ?>
                </ul>
            </div> <!-- #pagination-->
            </div> <!-- .span9 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #container -->