<?php 
	echo $this->headTitle('课程库 | ');
	echo $this->headLink()->appendStylesheet($this->basePath().'/css/courses/course.css');
    echo $this->headScript()->appendFile($this->basePath().'/js/stick-up.min.js');
?>

<div id="content">
    <div id="banner">
        <div id="banner-content">
            <div id="slogan">
                <h2>课程库</h2>
                <h4>提供最适合您的培训</h4>
            </div> <!-- #slogan -->
            <form id="search" class="navbar-search pull-right">
                <input type="text" class="search-query" />
                <button type="submit" class="btn btn-success">搜索</button>
            </form>
        </div> <!-- #banner-content -->
    </div> <!-- #banner -->
    <div id="main-container">
        <div id="main-content">
            <div id="sidebar">
                <h4>高级搜索</h4>
                <div class="section">
                    <label for="course-type"><strong>课程类别</strong></label>
                    <select name="course-type" id="course-type">
                        <option value="">所有课程类别</option>
                        <?php foreach ( $courseTypes as $courseType ) { ?>
                        <option value="<?php echo $courseType->course_type_slug; ?>"><?php echo $courseType->course_type_name; ?></option>
                        <?php } ?>
                    </select>
                </div> <!-- .section -->
                <div class="section">
                    <label for="keyword"><strong>关键字</strong></label>
                    <input id="keyword" name="keyword" type="text" />
                </div> <!-- .section -->
                <div class="section">
                    <input type="submit" class="btn btn-success" value="搜索" />
                </div> <!-- .section -->
            </div> <!-- #sidebar -->
            <div id="course-content">
                <?php foreach ( $courses as $course ) { ?>
                <div class="block">
                    <div class="icon">
                    <?php if ( strtotime($course->course_create_time) > strtotime('-7 day', time()) ):?>
                        <span class="label label-success">NEW</span>
                    <?php endif; ?>
                    </div> <!-- .icon -->
                    <a href="<?php echo $this->basePath(); ?>/courses/course/detail/<?php echo $course->course_id; ?>">
                        <div class="content">
                            <h4><?php echo $course->course_name; ?></h4>
                            <div class="meta">
                                <span><i class="icon-th-list"></i><strong>课程类别: </strong><?php echo $course->course_type_name; ?></span>
                                <span><i class="icon-time"></i><strong>培训周期: </strong><?php echo $course->course_cycle; ?>天</span>
                                <span><i class="icon-user"></i><strong>讲师: </strong><?php echo $course->teacher_name; ?></span><br />
                                <span><i class="icon-eye-open"></i><strong>听众范围: </strong><?php echo $course->course_audience; ?></span>
                            </div> <!-- .meta -->
                            <p><?php echo mb_substr( $course->course_brief, 0, 120, "utf-8" ); ?>...</p>
                        </div> <!-- .content -->
                    </a>
                </div> <!-- .block -->
                <?php } ?>
                <div id="pagination" class="pagination pagination-centered">
                    <ul>
                    <?php
                        $basePath = $this->basePath().'/courses/course/page/';
                    ?>
                    <?php if ( $currentPageNumber > 1 ): ?>
                        <li><a href="<?php echo $basePath.($currentPageNumber - 1); ?>">&lt;</a></li>
                    <?php else: ?>
                        <li class="disabled"><a>&lt;</a></li>
                    <?php endif; ?>
                    <?php
                        $lowerBound = $currentPageNumber - 5;
                        $lowerBound = ( $lowerBound > 0 ) ? $lowerBound : 1;
                        $upperBound = $currentPageNumber + 4;
                        $upperBound = ( $upperBound <= $numberOfPages ) ? $upperBound : $numberOfPages;

                        for ( $i = $lowerBound; $i <= $upperBound; ++ $i ) {
                            if ( $i == $currentPageNumber ) {
                                echo "<li class=\"active\"><a>$i</a></li>";
                            } else {
                                echo "<li><a href=\"$basePath$i\">$i</a></li>";
                            }
                        }
                    ?>
                    <?php if ( $currentPageNumber < $numberOfPages ): ?>
                        <li><a href="<?php echo $basePath.($currentPageNumber + 1); ?>">&gt;</a></li>
                    <?php else: ?>
                        <li class="disabled"><a>&gt;</a></li>
                    <?php endif; ?>
                    </ul>
                </div> <!-- #pagination-->
            </div> <!-- #course-content -->
        </div> <!-- #main-content -->
    </div> <!-- #main-container -->
</div> <!-- #content -->

<?php $this->inlineScript()->captureStart(); ?>
    jQuery(function($) {
        $(document).ready( function() {
            $('#sidebar').stickUp();
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(window).scroll(function() {
        setSidebarVisibility();
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setSidebarVisibility() {
        var sidebarHeight   = $('#sidebar').outerHeight(),
            headerHeight    = $('#header').outerHeight(),
            footerOffsetTop = $('#footer').offset().top - $(window).scrollTop() - headerHeight,
            offset          = footerOffsetTop - sidebarHeight - headerHeight;
        console.log( 'OffsetTop = ' + footerOffsetTop + "\n" + 'sidebarHeight = ' + sidebarHeight );
        if ( footerOffsetTop < sidebarHeight ) {
            $('#sidebar').css('top', offset);
        } else {
            if ( $('#sidebar').hasClass('isStuck') ) {
                $('#sidebar').css('top', 96);
            } else {
                $('#sidebar').css('top', 0);
            }
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>