<?php 
	echo $this->headTitle('课程库 | ');
	echo $this->headLink()->appendStylesheet($this->basePath().'/css/courses/course.css');
?>

<div id="content">
	<div id="banner">
		<div id="title">
			<h1>课程库</h1>
			<h2>提供最适合您的培训</h2>
		</div> <!-- #title -->
	</div> <!-- #banner -->
	<div id="filter">
		<select name="course-types">
			<option value="">所有课程类别</option>
			<?php foreach ( $courseTypes as $courseType ) { ?>
			<option value="<?php echo $courseType->course_type_slug; ?>"><?php echo $courseType->course_type_name; ?></option>
			<?php } ?>
		</select>
		<input name="keyword" type="text" />
		<input type="submit" class="btn" value="搜索" />
	</div> <!-- #filter -->
	<div id="main-content">
		<div id="courses">
			<?php
				foreach ( $courses as $course ) {
			?>
			<div class="section">
				<div class="left">
					<?php if ( strtotime($course->create_time) > strtotime('-7 day', time()) ):?>
					<div class="brand brand-new"></div>
					<?php endif ?>
					<div class="fieldset">
						<div class="title">
							<a href="<?php echo $this->basePath("courses/course/detail/$course->course_id"); ?>">
								<?php echo $course->course_name; ?>
							</a>
						</div> <!-- .fieldset -->
						<div class="brief"><?php echo $course->course_brief; ?></div> <!-- .brief -->
					</div> <!-- .fieldset -->
					<div class="details">
						<ul class="inline">
							<li><strong>培训周期: </strong><?php echo $course->course_cycle; ?>天</li>
							<li><strong>讲师: </strong><?php echo $course->teacher_name; ?></li>
							<li><strong>听众范围: </strong><?php echo $course->course_audience; ?></li>
						</ul>
					</div> <!-- details -->
				</div> <!-- .left -->
				<div class="right">
					<img src="<?php echo $this->basePath("img/courses/$course->course_type_slug-small.jpg") ?>" alt="Thumbnail" />
				</div> <!-- .right -->
			</div> <!-- .section -->
			<?php } ?>
		</div> <!-- #courses -->
		<div id="pagination" class="pagination pagination-centered">
			<ul>
			<?php
				$basePath = $this->basePath().'/courses/course/page/';
			?>
			<?php if ( $currentPageNumber > 1 ): ?>
                <li><a href="<?php echo $basePath.($currentPageNumber - 1); ?>">&lt;</a></li>
            <?php else: ?>
                <li class="disabled"><a>&lt;</a></li>
            <?php endif; ?>
            <?php
                $lowerBound = $currentPageNumber - 5;
                $lowerBound = ( $lowerBound > 0 ) ? $lowerBound : 1;
                $upperBound = $currentPageNumber + 4;
                $upperBound = ( $upperBound <= $numberOfPages ) ? $upperBound : $numberOfPages;

                for ( $i = $lowerBound; $i <= $upperBound; ++ $i ) {
                    if ( $i == $currentPageNumber ) {
                        echo "<li class=\"active\"><a>$i</a></li>";
                    } else {
                        echo "<li><a href=\"$basePath$i\">$i</a></li>";
                    }
                }
            ?>
            <?php if ( $currentPageNumber < $numberOfPages ): ?>
                <li><a href="<?php echo $basePath.($currentPageNumber + 1); ?>">&gt;</a></li>
            <?php else: ?>
                <li class="disabled"><a>&gt;</a></li>
            <?php endif; ?>
			</ul>
		</div> <!-- #pagination-->
	</div> <!-- #main-content -->
</div> <!-- #content -->