<div style="padding:0;margin:0;background:#e9e9e9;font-family:'Segoe UI', 'Microsoft YaHei'">
<table width="625" style="background:#e9e9e9" cellspacing="0" cellpadding="0" border="0">
	<tbody>
		<tr>
			<td>
				<div style="color:#1b1b1b;background:#fff;border:1px solid #aaa;border-radius:5px;margin:15px">
					<table cellspacing="0" cellpadding="0" border="0">
						<tbody>
							<tr>
								<td style="padding:15px 15px 0 15px;background:#fff;border-radius:4px 4px 0 0">
									<div>
										<img src="http://itp.zjhzxhz.com/img/logo.png" alt="IT培训平台" height="85" width="290">
									</div>
								</td>
							</tr>
							<tr>
								<td style="padding:15px; background:#fff; border-radius:0 0 4px 4px;font-size:12px">
									<?=$this->username?>, 你好: <br><br>
									我们收到了重设 IT培训平台 账户密码的请求.<br><br>
									如果您未发出请求, 请不要担心, 只需忽略此电子邮件, 任何内容均不会更改.<br><br>
									如果确实是您请求重设 IT培训平台 账户密码，点击以下链接即可：<br>
									<a href="http://itp.zjhzxhz.com/accounts/resetPassword?email=<?=$this->email?>&keycode=<?=$this->keycode?>" target="_blank"style="color: #005399;text-decoration: none;">http://itp.zjhzxhz.com/accounts/resetPassword?email=<?=$this->email?>&keycode=<?=$this->keycode?></a><br><br>
									此致, <br>
									IT培训平台.<br><br>
									<div style="border-top:3px solid #eee;color:#999;font-size:11px;line-height:1.2">
										<br>Powered by <a href="http://itp.zjhzxhz.com" target="_blank" style="color: #005399;text-decoration: none;">IT培训平台</a>. All rights reserved.<br>
									</div>
								</td>
							</tr>
						</tbody>
					</table>            
				</div>
			</td>
		</tr>
	</tbody>
</table>
</div>