<?php 
    echo $this->headTitle('登录 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/login.css');
?>

<div id="content">
    <div id="login-container">
        <div id="login-error" class="alert alert-error hide"></div>
        <div id="login-form">
            <h4>用户登录</h4>
            <div class="field">
                <label for="username">用户名或电子邮件地址</label>
                <input type="text" id="username" name="username" maxlength="48" />
            </div> <!-- .field -->
            <div class="field">
                <label for="password">密码</label>
                <span id="forgot-password"><a href="#">忘记密码?</a></span>
                <input type="password" id="password" name="password" maxlength="16" />
            </div> <!-- .field -->
            <div class="field">
                <div id="remember-me" class="field">
                    <span><input type="checkbox" name="remember-me" /></span>
                    <span>保持登录状态</span>
                </div> <!-- #remember-me -->
                <div id="login-control">
                    <button id="login" class="btn btn-primary">登录</button>
                </div> <!-- #login-control -->
            </div> <!-- .field -->
        </div> <!-- #login-form -->
    </div> <!-- #login-container -->
    <div id="register-container">
        <div id="register-form">
            没有帐号? <a href="<?php echo $this->basePath(); ?>/accounts/register">立即注册</a>
        </div> <!-- #register-form -->
    </div> <!-- #register-container -->
</div> <!-- #content -->

<?php $this->inlineScript()->captureStart(); ?>
    $('#login').click(function() {
        var username    = $('input[name=username]').val(),
            password    = $('input[name=password]').val(),
            rememberMe  = $('input[name=remember-me]').val();

        setButtonStyle(true);
        doLoginAction(username, password);
        setButtonStyle(false);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setButtonStyle(isLoading) {
        var loginButtonObject = $('#login');
        if ( isLoading ) {
            loginButtonObject.html('正在登录...');
            loginButtonObject.attr('disabled', 'disabled');
        } else {
            loginButtonObject.html('登录');
            loginButtonObject.removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doLoginAction(username, password, rememberMe) {
        var postData = 'username=' + username + '&password=' + password +
                       '&remember_me=' + rememberMe;
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/login/process',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processResult(result);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            window.location.href='<?php echo $redirectUrl; ?>';
        } else {
            if ( result['isUsernameEmpty'] && result['isPasswordEmpty'] ) {
                displayErrorMessage('请输入用户名或电子邮件地址.<br />请输入密码.');
            } else if ( result['isUsernameEmpty'] ) {
                displayErrorMessage('请输入用户名或电子邮件地址.');
            } else if ( result['isPasswordEmpty'] ) {
                displayErrorMessage('请输入密码.');
            } else if ( !result['isAccountValid'] ) {
                displayErrorMessage('用户名或密码不正确.');
            }
            $('input[name=password]').val('');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayErrorMessage(message) {
        var errorMessageBox = $('#login-error');
        errorMessageBox.html(message);
        errorMessageBox.removeClass('hide');
    }
<?php $this->inlineScript()->captureEnd(); ?>
