<?= $this->headTitle('课程库 | '); ?>
<?= $this->headLink()->appendStylesheet($this->basePath('/css/training/style.css'))
                     ->appendStylesheet($this->basePath('/css/training/courses.css')); ?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?= $this->basePath('/'); ?>">
                <img src="<?= $this->basePath('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?= $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?= $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?= $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?= $this->basePath('/accounts/dashboard#requirements'); ?>">需求定制</a></li>
                <li><a href="<?= $this->basePath('/training/posts'); ?>">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?= $this->basePath('/accounts/login'); ?>"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?= $this->basePath('/accounts/register'); ?>'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?= $this->basePath('/accounts/dashboard'); ?>"><?= $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?= $this->basePath('/accounts/logout'); ?>">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?= $this->basePath('/search'); ?>">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div id="sub-header">
            <h2>课程库</h2>
            <p>海量课程供您选择! 选择适合您的培训课程.</p>
            <button class="btn btn-orange" onclick="window.location.href='<?= $this->basePath('/training/lectures'); ?>'">查看近期培训</button>
            <img src="<?= $this->basePath('/img/training/course-header.jpg'); ?>" alt="Header Image">
            <div class="border-bottom"></div> <!-- .border-bottom -->
        </div> <!-- #sub-header -->
        <div id="content" class="row-fluid">
            <div class="span3">
                <h4>筛选课程</h4>
                <h5>授课领域</h5>
                <ul id="course-types" class="inline">
                    <li class="active"><a href="#all">全部领域</a></li>
                    <?php foreach ( $courseTypes as $courseType ): ?>
                    <li><a href="#<?= $courseType->courseTypeSlug; ?>"><?= $courseType->courseTypeName; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div> <!-- .span3 -->
            <div class="span9">
                <div class="alert alert-warning hide">未找到符合要求的课程.</div>
                <ul id="courses"></ul>
                <div id="pagination" class="pagination pagination-centered">
                    <ul></ul>
                </div> <!-- #pagination-->
            </div> <!-- .span9 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #container -->

<?php $this->inlineScript()->captureStart(); ?>
    $('ul#course-types > li').click(function() {
        $('ul#course-types > li.active').removeClass('active');
        $(this).addClass('active');

        var category   = $('a', this).attr('href').substring(1),
            pageNumber = 1;
        getCourses(category, pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getCourses(category, pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?= $this->basePath('/training/getCourses'); ?>?category=' + category + '&page=' + pageNumber,
            dataType: 'JSON',
            success: function(result) {
                $('#courses').empty();
                $('div#pagination > ul').empty();
                if ( result['isSuccessful'] ) {
                    $('.alert-warning').addClass('hide');
                    $('div#pagination').removeClass('hide');
                    displayCourses(result['courses']);
                    displayPagination(pageNumber, result['totalPages']);
                } else {
                    $('.alert-warning').removeClass('hide');
                    $('div#pagination').addClass('hide');
                }
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayCourses(courses) {
        var numberOfCourses = courses.length;
        for ( var i = 0; i < numberOfCourses; ++ i ) {
            $('#courses').append('<li class="course row-fluid">'
                                + '    <div class="span3">'
                                + '        <img src="<?= $this->basePath('/img/categories/'); ?>' + courses[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                + '    </div>'
                                + '    <div class="span9">'
                                + '        <h4><a href="<?= $this->basePath('/training/course'); ?>?courseId=' + courses[i]['courseId'] + '">' + courses[i]['courseName'] + '</a></h4>'
                                + '        <p class="introduction">' + courses[i]['brief'] + '</p>'
                                + '        <ul class="inline meta">'
                                + '            <li><i class="fa fa-user"></i> <a href="<?= $this->basePath('/training/teacher'); ?>?teacherId=' + courses[i]['teacherId'] + '">' + courses[i]['teacherName'] + '</a></li>'
                                + '            <li><i class="fa fa-tasks"></i> ' + courses[i]['courseTypeName'] + '</li>'
                                + '        </ul>'
                                + '    </div>'
                                + '</li>');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('#pagination > ul').delegate('li', 'click', function(e) {
        e.preventDefault();
        if ( $(this).hasClass('disabled') ) {
            return;
        }
        var currentPage = parseInt($('li.active > a', 'div#pagination > ul').html());
        
        $('#pagination > li.active').removeClass('active');
        $(this).addClass('active');
        var category    = $('ul#course-types > li.active > a').attr('href').substring(1),
            pageNumber  = $('a', this).html();

        if ( pageNumber == '&lt;' ) {
            pageNumber  = currentPage - 1;
        } else if ( pageNumber == '&gt;' ) {
            pageNumber  = currentPage + 1;
        }
        getCourses(category, pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayPagination(currentPage, totalPages) {
        var lowerBound = ( currentPage - 5 > 0 ? currentPage - 5 : 1 ),
            upperBound = ( currentPage + 5 < totalPages ? currentPage + 5 : totalPages );
        var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="#">&gt;</a></li>';
        $('#pagination > ul').append(paginationString);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(function() {
        getCourses('all', 1);
    });
<?php $this->inlineScript()->captureEnd(); ?>