<?= $this->headTitle('培训动态 | '); ?>
<?= $this->headLink()->appendStylesheet($this->cdn('/css/training/style.css'))
                          ->appendStylesheet($this->cdn('/css/training/post.css')); ?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?= $this->basePath('/'); ?>">
                <img src="<?= $this->cdn('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?= $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?= $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?= $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?= $this->basePath('/accounts/dashboard#requirements'); ?>">需求定制</a></li>
                <li><a href="<?= $this->basePath('/training/posts'); ?>">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?= $this->basePath('/accounts/login'); ?>"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?= $this->basePath('/accounts/register'); ?>'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?= $this->basePath('/accounts/dashboard'); ?>"><?= $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?= $this->basePath('/accounts/logout'); ?>">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?= $this->basePath('/search'); ?>">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container row-fluid">
        <div class="span9">
            <div id="overview">
                <h3><?= $post->postTitle; ?></h3>
                <ul class="inline">
                    <li><i class="fa fa-th-list"></i> <?= $post->postCategoryName; ?></li>
                    <li><i class="fa fa-calendar"></i> <?= date('Y-m-d H:i', strtotime($post->postDate)); ?></li>
                </ul>
            </div> <!-- #overview -->
            <div id="detail">
                <?= $post->postContent; ?>
            </div> <!-- #detail -->
        </div> <!-- .span9 -->
        <div class="span3">
            <h4>培训动态</h4>
            <ul id="posts">
            <?php foreach ( $posts as $p ): ?>
                <?php if ( $p['postId'] == $post->postId ): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <li><a href="<?= $this->basePath('/training/post'); ?>?postId=<?= $p['postId']; ?>"><?= $p['postTitle']; ?></a></li>
            <?php endforeach; ?>
            </ul>
        </div> <!-- .span3 -->
    </div> <!-- .container -->
</div> <!-- #container -->