<?php 
    echo $this->headTitle('培训动态 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/training/style.css');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/training/posts.css');
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath(); ?>">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath(); ?>/training/lectures">近期开课</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/courses">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/teachers">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#requirement">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/posts">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('itp_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/accounts/register'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?php echo $this->basePath(); ?>/home/search">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div id="sub-header">
            <h2>培训动态</h2>
            <p>最及时的培训资讯, 让您了解行业风向标!</p>
            <button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/training/lectures'">查看近期开课</button>
            <img src="<?php echo $this->basePath(); ?>/img/training/course-header.jpg" alt="Header Image">
            <div class="border-bottom"></div> <!-- .border-bottom -->
        </div> <!-- #sub-header -->
        <div id="content" class="row-fluid">
            <div class="span3">
                <h4>分类目录</h4>
                <ul id="category">
                    <li><a href="#all">全部分类</a></li>
                <?php foreach ( $postCategories as $postCategory ): ?>
                    <li><a href="#<?php echo $postCategory->postCategorySlug; ?>"><?php echo $postCategory->postCategoryName; ?></a></li>
                <?php endforeach; ?>
                </ul>
            </div> <!-- .span3 -->
            <div class="span9">
                <div class="alert alert-warning hide">此分类下没有文章.</div>
                <ul id="posts"></ul>
                <div id="pagination" class="pagination pagination-centered">
                    <ul></ul>
                </div> <!-- #pagination-->
            </div> <!-- .span9 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #container -->

<?php $this->inlineScript()->captureStart(); ?>
    $('ul#category > li').click(function() {
        var category = $('a', this).attr('href').substring(1);
        getPosts(category, 1);
        getTotalPages(category, 1);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getPosts(category, pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/training/getPosts?category=' + category + '&page=' + pageNumber,
            dataType: 'JSON',
            success: function(result) {
                $('#posts').empty();
                if ( result['isSuccessful'] ) {
                    $('.alert-warning').addClass('hide');
                    displayPosts(result['posts']);
                } else {
                    $('.alert-warning').removeClass('hide');
                }
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayPosts(posts) {
        var numberOfPosts = posts.length;
        for ( var i = 0; i < numberOfPosts; ++ i ) {
            $('#posts').append('<li class="post row-fluid">'
                                + '    <div class="span2">'
                                + '        <img src="<?php echo $this->basePath(); ?>/img/training/icon-news.png" alt="Icon News" />'
                                + '    </div>'
                                + '    <div class="span10">'
                                + '        <h4><a href="<?php echo $this->basePath(); ?>/training/post?postId=' + posts[i]['postId'] + '">' + posts[i]['postTitle'] + '</a></h4>'
                                + '        <p class="introduction">' + posts[i]['postContent'] + '</p>'
                                + '        <ul class="inline meta">'
                                + '            <li><i class="icon-th-list"></i> ' + posts[i]['postCategoryName'] + '</li>'
                                + '            <li><i class="icon-calendar"></i> ' + getDateTime(posts[i]['postDate']) + '</li>'
                                + '        </ul>'
                                + '    </div>'
                                + '</li>');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getDateTime(dateTimeString) {
        var year    = dateTimeString.substring(0, 4),
            month   = dateTimeString.substring(5, 7),
            day     = dateTimeString.substring(8, 10),
            time    = dateTimeString.substring(11, 16);

        return year + '年' + month + '月' + day + '日 ' + time;
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('#pagination > ul').delegate('li', 'click', function(e) {
        e.preventDefault();
        if ( $(this).hasClass('disabled') ) {
            return;
        }
        var currentPage = $('li.active > a', '#pagination').html();
        
        $('#pagination > li.active').removeClass('active');
        $(this).addClass('active');
        var category    = $('ul#course-types > li.active > a').attr('href').substring(1),
            pageNumber  = $('a', this).html();

        if ( pageNumber === '&lt;' ) {
            pageNumber  = currentPage - 1;
        } else if ( pageNumber === '&gt;' ) {
            pageNumber  = currentPage + 1;
        }
        getTeachers(category, pageNumber);
        getTotalPages(category, pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getTotalPages(category, pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/training/getPostTotalPages?category=' + category,
            dataType: 'JSON',
            success: function(result) {
                $('div#pagination > ul').empty();
                if ( result['isSuccessful'] ) {
                    $('div#pagination').removeClass('hide');
                    displayPagination(pageNumber, result['totalPages']);
                } else {
                    $('div#pagination').addClass('hide');
                }
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayPagination(currentPage, totalPages) {
        var lowerBound = ( currentPage - 5 > 0 ? currentPage - 5 : 1 ),
            upperBound = ( currentPage + 5 < totalPages ? currentPage + 5 : totalPages );
        var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="#">&gt;</a></li>';
        $('#pagination > ul').append(paginationString);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function() {
        getPosts('all', 1);
        getTotalPages('all', 1);
    });
<?php $this->inlineScript()->captureEnd(); ?>