<?php
use Zend\Mvc\Application;
?>
<?= $this->headTitle('页面未找到 | '); ?>
<?= $this->headLink()->appendStylesheet($this->cdn('/css/training/style.css'))
                          ->appendStylesheet($this->cdn('/css/404.css')); ?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?= $this->basePath('/'); ?>">
                <img src="<?= $this->cdn('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div>
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?= $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?= $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?= $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?= $this->basePath('/accounts/dashboard#requirements'); ?>">需求定制</a></li>
                <li><a href="<?= $this->basePath('/training/posts'); ?>">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?= $this->basePath('/accounts/login'); ?>"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?= $this->basePath('/accounts/register'); ?>'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?= $this->basePath('/accounts/dashboard'); ?>"><?= $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?= $this->basePath('/accounts/logout'); ?>">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?= $this->basePath('/search'); ?>">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container row-fluid">
        <div class="span6">
            <img src="<?= $this->cdn('/img/404.png'); ?>" alt="Error Image">
        </div> <!-- .span6 -->
        <div class="span6">
            <h2>页面未找到</h2>
            <p>很抱歉, 我们无法为您加载您所请求的页面..</p>
            <button class="btn btn-orange" onclick="history.go(-1);">返回</button>
        </div> <!-- .span6 -->
    </div> <!-- .container -->
    <?php if (isset($this->reason) && $this->reason): ?>
    <div id="debug" class="container row-fluid">
        <h4>A 404 error occurred</h4>
        <h5><?= $this->message ?></h5>
        <?php
        $reasonMessage= '';
        switch ($this->reason) {
            case Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
                $reasonMessage = 'The requested controller was unable to dispatch the request.';
                break;
            case Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH:
                $reasonMessage = 'The requested middleware was unable to dispatch the request.';
                break;
            case Application::ERROR_CONTROLLER_NOT_FOUND:
                $reasonMessage = 'The requested controller could not be mapped to an existing controller class.';
                break;
            case Application::ERROR_CONTROLLER_INVALID:
                $reasonMessage = 'The requested controller was not dispatchable.';
                break;
            case Application::ERROR_ROUTER_NO_MATCH:
                $reasonMessage = 'The requested URL could not be matched by routing.';
                break;
            default:
                $reasonMessage = 'We cannot determine at this time why a 404 was generated.';
                break;
        }
        ?>
        <p><?= $reasonMessage ?></p>

        <?php if ( !empty($this->controller) ) : ?>
        <dl>
            <dt>Controller:</dt>
            <dd>
                <?= $this->escapeHtml($this->controller) ?>
                <?php
                if (! empty($this->controller_class) && $this->controller_class != $this->controller) {
                    printf('(resolves to %s)', $this->escapeHtml($this->controller_class));
                }
                ?>
            </dd>
        </dl>
        <?php endif ?>

        <?php if (! empty($this->display_exceptions)) : ?>
            <?php if (isset($this->exception)
                && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
        <hr/>

        <h2>Additional information:</h2>
        <h3><?= get_class($this->exception) ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
            </dd>
        </dl>
        
        <?php if ($ex = $this->exception->getPrevious()) : ?>
        <hr/>
        <h2>Previous exceptions:</h2>
        <ul class="list-unstyled">
            <?php $icount = 0 ?>
            <?php while ($ex) : ?>
                <li>
                    <h3><?= get_class($ex) ?></h3>
                    <dl>
                        <dt>File:</dt>
                        <dd>
                            <pre><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
                        </dd>
                        <dt>Message:</dt>
                        <dd>
                            <pre><?= $this->escapeHtml($ex->getMessage()) ?></pre>
                        </dd>
                        <dt>Stack trace:</dt>
                        <dd>
                            <pre><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
                        </dd>
                    </dl>
                </li>
                <?php
                $ex = $ex->getPrevious();
                if (++$icount >= 50) {
                    echo '<li>There may be more exceptions, but we do not have enough memory to process it.</li>';
                    break;
                }
                ?>
            <?php endwhile ?>
        </ul>
                <?php endif ?>
            <?php else : ?>
        <h3>No Exception available</h3>
            <?php endif ?>
        <?php endif ?>
    </div> <!-- #debug -->
    <?php endif ?>
</div> <!-- #container -->
