<?php 
	echo $this->headTitle('培训动态 | ');
	echo $this->headLink()->appendStylesheet($this->basePath().'/css/courses/news.css');
?>

<div id="content">
	<div id="banner">
		<div id="title">
			<h1>培训动态</h1>
			<h2>掌握培训的风向标</h2>
		</div> <!-- #title -->
	</div> <!-- #banner -->
	<div id="main-content">
		<div id="sidebar">
			<ul>
				<li>分类名称1</li>
				<li>分类名称2</li>
				<li>分类名称3</li>
			</ul>
		</div> <!-- #sidebar -->
		<div id="news">
			<div class="section">
				<div class="avatar">
					<img src="" alt="" />
				</div> <!-- .avatar -->
				<div class="content">
					<h2><a href="#">World Economic Forum Launches "Forum Academy" MOOC Portal Using edX Platform</a></h2>
					<p class="meta">2014年2月3日</p>
					<p>For decades, the World Economic Forum has enabled leaders in business, policy and academia to meet and learn from one another at events held in Davos, Switzerland and many other locations around the world. These gatherings have provided the setting for an exchange of ideas that have helped set the direction for solutions to critical global problems. Now, with the creation of Forum Academy, the World Economic Forum (WEF) will provide a much wider audience with the opportunity to participate in a discussion addressing global, regional and industry challenges through courses created using the cutting-edge platform and tools innovated by edX.</p>
				</div> <!-- .content -->
			</div> <!-- .section -->
		</div> <!-- #news -->
	</div> <!-- #main-content -->
</div> <!-- #content -->