<?php 
    echo $this->headTitle('近期开课 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/datepicker.css')
                          ->appendStylesheet($this->basePath().'/css/courses/recently.css');
    echo $this->headScript()->appendFile($this->basePath().'/js/stick-up.min.js')
                            ->appendFile($this->basePath().'/js/datepicker.min.js')
                            ->appendFile($this->basePath().'/js/citypicker.js');
?>

<div id="content">
    <div id="banner">
        <div id="title">
            <h1>近期开课</h1>
            <h2>提供最适合您的培训</h2>
        </div> <!-- #title -->
    </div> <!-- #banner -->
    <div id="main-content">
        <div id="sidebar">
            <div id="search">
                <h2>查找适合您的课程</h2>
                <div class="field">
                    <label for="keyword">关键词</label>
                    <input type="text" name="keyword" />
                </div> <!-- .field -->
                <div class="field">
                    <label for="course-types">课程类型</label>
                    <select name="course-types">
                        <option value="">所有课程类型</option>
                        <?php foreach ( $courseTypes as $courseType ) { ?>
                        <option value="<?php echo $courseType->course_type_slug; ?>"><?php echo $courseType->course_type_name; ?></option>
                        <?php } ?>
                    </select>
                </div> <!-- .field -->
                <div class="field">
                    <label for="time">开课时间</label>
                    <div class="input-append date" id="datepicker" data-date-format="yyyy-mm-dd">
                        <input size="16" type="text" value="任意时间" style="width: 179px;" disabled="disabled"/>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div>
                </div> <!-- .field -->
                <form class="field">
                    <label for="place">开课地点</label>
                    <select class="place" name="region" onchange="setProvince(this, province, city)">
                        <option value="" selected>任意地区</option>
                        <script type="text/javascript">
                            setRegions();
                        </script>
                    </select>
                    <select class="place" name="province" disabled="disabled" onchange="setCity(this, city)">
                    </select>
                    <select class="place" name="city" disabled="disabled">
                    </select>
                </form> <!-- .field -->
                <div class="field">
                    <button class="btn">搜索</button>
                </div> <!-- .field -->
            </div> <!-- #search -->
        </div> <!-- #sidebar -->
        <div id="recently">
        <?php 
            foreach ( $lectures as $lecture ) {
        ?>
            <div class="section">
                <div class="title">
                    <a href="<?php echo $this->basePath("courses/recently/detail/$lecture->lecture_id"); ?>">
                        <span><?php echo $lecture->course_name; ?></span>
                    </a>
                </div> <!-- #title -->
                <div class="meta">
                    <span><i class="icon-th-list"></i> <?php echo $lecture->course_type_name; ?></span>
                    <span><i class="icon-calendar"></i> <?php echo date('Y年m月d日', strtotime($lecture->start_time)); ?>~<?php echo date('Y年m月d日', strtotime($lecture->end_time)); ?></span>
                    <span><i class="icon-user"></i> <?php echo $lecture->real_name; ?></span>
                    <span><i class="icon-tag"></i> <?php echo $lecture->expense; ?>元</span>
                </div> <!-- .meta -->
                <div class="introduction">
                    <?php echo $lecture->brief; ?>
                </div> <!-- .introduction -->
                <div class="detail">
                    <ul class="inline">
                        <li><strong>听众范围: </strong><?php echo $lecture->audience; ?></li>
                        <li><strong>地点: </strong>
                            <?php echo $lecture->place_province; ?>
                            <?php echo $lecture->place_city; ?>
                        </li>
                    </ul>
                </div> <!-- .detail -->
            </div> <!-- .section -->
        <?php } ?>
        </div> <!-- #recently -->
        <div id="pagination" class="pagination pagination-centered">
            <ul>
            <?php
                $basePath = $this->basePath().'/courses/recently/page/';
            ?>
            <?php if ( $currentPageNumber > 1 ): ?>
                <li><a href="<?php echo $basePath.($currentPageNumber - 1); ?>">&lt;</a></li>
            <?php else: ?>
                <li class="disabled"><a>&lt;</a></li>
            <?php endif; ?>
            <?php
                $lowerBound = $currentPageNumber - 5;
                $lowerBound = ( $lowerBound > 0 ) ? $lowerBound : 1;
                $upperBound = $currentPageNumber + 4;
                $upperBound = ( $upperBound <= $numberOfPages ) ? $upperBound : $numberOfPages;

                for ( $i = $lowerBound; $i <= $upperBound; ++ $i ) {
                    if ( $i == $currentPageNumber ) {
                        echo "<li class=\"active\"><a>$i</a></li>";
                    } else {
                        echo "<li><a href=\"$basePath$i\">$i</a></li>";
                    }
                }
            ?>
            <?php if ( $currentPageNumber < $numberOfPages ): ?>
                <li><a href="<?php echo $basePath.($currentPageNumber + 1); ?>">&gt;</a></li>
            <?php else: ?>
                <li class="disabled"><a>&gt;</a></li>
            <?php endif; ?>
            </ul>
        </div> <!-- #pagination-->
    </div> <!-- #main-content -->
</div> <!-- #content -->

<?php $this->inlineScript()->captureStart(); ?>
    jQuery(function($) {
        $(document).ready( function() {
            $('#search').stickUp();
            $('#datepicker').datepicker();
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(window).scroll(function() {
        $('#datepicker').datepicker('hide');
        setSearchVisibility();
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setSearchVisibility() {
        var searchBoxHeight = $('#search').outerHeight(),
            footerOffsetTop = $('#footer').offset().top - $(window).scrollTop(),
            offset          = footerOffsetTop - searchBoxHeight;
        if ( footerOffsetTop < searchBoxHeight ) {
            $('#search').css('top', offset);
        } else {
            $('#search').css('top', 0);
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>