<?php 
    echo $this->headTitle($lecture['course_name'].' | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/courses/detail.css');
?>

<div id="content">
    <div id="detail">
        <div id="banner">
            <img src="<?php echo $this->basePath('img/courses/'.$lecture['course_type_slug'].'-large.jpg'); ?>" alt="Banner" />
        </div> <!-- #banner -->
        <div id="main-content">
            <div id="course-name"><?php echo $lecture['course_name'] ?></div> <!-- #course-name -->
            <div id="brief" class="section"><?php echo $lecture['course_brief']; ?></div> <!-- #brief -->
            <?php if ( isset($lecture['course_objective']) ): ?>
                <div id="objective" class="section">
                    <div class="title">课程目标</div>
                    <div class="content"><?php echo $lecture['course_objective']; ?></div>
                </div> <!-- #purpose -->
            <?php endif; ?>
            <?php if ( isset($lecture['course_feature']) ): ?>
                <div id="feature" class="section">
                    <div class="title">课程特点</div>
                    <div class="content"><?php echo $lecture['course_feature']; ?></div>
                </div> <!-- #feature -->
            <?php endif; ?>
            <?php if ( isset($lecture['course_outline']) ): ?>
                <div id="outline" class="section">
                    <div class="title">课程大纲</div>
                    <div class="content"><?php echo $lecture['course_outline']; ?></div>
                </div> <!-- #outline -->
            <?php endif; ?>
            <?php if ( isset($lecture['lecture_guideline']) ): ?>
                <div id="outline" class="section">
                    <div class="title">注意事项</div>
                    <div class="content"><?php echo $lecture['lecture_guideline']; ?></div>
                </div> <!-- #guideline -->
            <?php endif; ?>
            <div id="teacher-introduction" class="section">
                <div class="title">讲师介绍</div>
                <div id="teacher">
                    <div id="avatar">
                        <?php if ( $teacher['teacher_avatar'] == null ): ?>
                            <img class="img-circle" src="<?php echo $this->basePath(); ?>/img/avatar.png" alt="Avatar" />
                        <?php else: ?>
                            <img class="img-circle" src="<?php echo $this->basePath($teacher['teacher_avatar']); ?>" alt="Avatar" />
                        <?php endif; ?>
                    </div> <!-- #avatar -->
                    <div id="introduction">
                        <div id="name"><?php echo $teacher['teacher_name']; ?></div>
                        <div><?php echo $teacher['teacher_brief']; ?></div>
                    </div> <!-- #introduction -->
                </div> <!-- #teacher -->
            </div> <!-- #teacher-introduction -->
        </div> <!-- #main-content -->
    </div> <!-- #detail -->
    <div id="summary">
        <div id="company">
            <img src="https://www.edx.org/sites/default/files/course/image/video/berkeley_no_video_320x211.png" alt="Company Logo">
        </div> <!-- company -->
        <div id="overview">
            <div id="info">
                <div class="item">
                    <div class="title">课程分类</div>
                    <div class="content"><?php echo $lecture['course_type_name']; ?></div>
                </div>
                <div class="item">
                    <div class="title">讲师</div>
                    <div class="content"><?php echo $teacher['teacher_name']; ?></div>
                </div>
                <div class="item">
                    <div class="title">培训时间</div>
                    <div class="content">
                        <strong>从 </strong><?php echo date('Y年m月d日', strtotime($lecture['lecture_start_time'])); ?><br />
                        <strong>至 </strong><?php echo date('Y年m月d日', strtotime($lecture['lecture_end_time'])); ?>
                    </div>
                </div>
                <div class="item">
                    <div class="title">培训地点</div>
                    <div class="content">
                        <?php if ( !$isAttended ): ?>
                        (报名后查看详细地址)
                        <?php else: ?>
                        <span><?php echo $lecture['lecture_province']; ?></span>
                        <span><?php echo $lecture['lecture_city']; ?></span>
                        <span><?php echo $lecture['lecture_address']; ?></span>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="item">
                    <div class="title">培训费用</div>
                    <div class="content"><?php echo $lecture['lecture_expense']; ?> 元</div>
                </div>
                <div class="item">
                    <div class="title">听众范围</div>
                    <div class="content"><?php echo $lecture['course_audience']; ?></div>
                </div>
            </div> <!-- #info -->
            <div id="attend-lecture">
                <?php if ( !$isAttended ): ?>
                <button id="attend-lecture" class="btn btn-danger" onclick="javascript:attendLecture()">我要报名</button>
                <?php else: ?>
                <button class="btn btn-danger" disabled="disabled">您已报名</button>
                <?php endif; ?>
            </div> <!-- #attend-lecture -->
        </div> <!-- #overview -->
        <div id="social">
            <ul class="inline">
                <li><a href="#"><img class="social-icon" src="<?php echo $this->basePath(); ?>/img/social-icons/sina.png" alt="Sina"></a></li>
                <li><a href="#"><img class="social-icon" src="<?php echo $this->basePath(); ?>/img/social-icons/wechat.png" alt="WeChat"></a></li>
                <li><a href="#"><img class="social-icon" src="<?php echo $this->basePath(); ?>/img/social-icons/laiwang.png" alt="LaiWang"></a></li>
            </ul>
        </div> <!-- #social -->
    </div> <!-- #summary -->
</div> <!-- #conetnt -->

<?php $this->inlineScript()->captureStart(); ?>
    function attendLecture() {
    <?php if ( isset($isLogined)  && $isLogined ): ?>
        var lectureID   = <?php echo $lecture['lecture_id']; ?>;
        setButtonStyle(true);
        doAttendLectureAction(lectureID);
        setButtonStyle(false);
    <?php else: ?>
        alert('您还没有登录!\n单击确定后将为您跳转至登录页面.');
        window.location.href="<?php echo $this->basePath('/accounts/login?lectureId='.$lecture['lecture_id']); ?>";
    <?php endif; ?>
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doAttendLectureAction(lectureID) {
        var postData = 'lectureID=' + lectureID;
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/courses/lecture/attendLecture',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processResult(result);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            window.location.reload();
        } else {
            alert("对不起, 报名未能成功.\n请稍候再试.");
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setButtonStyle(isLoading) {
        var attendButtonObject = $('#attend-lecture');
        if ( isLoading ) {
            attendButtonObject.html('正在处理...');
            attendButtonObject.attr('disabled', 'disabled');
        } else {
            attendButtonObject.html('我要报名');
            attendButtonObject.removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>