<?php 
    echo $this->headTitle('个人中心 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/dashboard.css');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/person.css');
?>

<div id="content">
    <div id="sidebar">
        <div id="username"><?php echo $profile['username']; ?></div>
        <div id="profile">
            <ul>
                <li>
                    <i class="icon-user"></i>
                    <span class="title">姓名</span>
                    <span class="data"><?php echo $profile['real_name']; ?></span>
                </li>
                <li>
                    <i class="icon-envelope"></i>
                    <span class="title">电子邮件</span>
                    <span class="data"><?php echo $profile['email']; ?></span>
                </li>
                <li>
                    <i class="icon-info-sign"></i>
                    <span class="title">联系电话</span>
                    <span class="data"><?php echo $profile['phone']; ?></span>
                </li>
                <li>
                    <i class="icon-time"></i>
                    <span class="title">上次登录</span>
                    <span class="data">
                        <?php if ( $profile['lastTimeSignIn'] == '0000-00-00 00:00:00' ): ?>
                            从未登录
                        <?php else: ?>
                            <?php echo date('Y年m月d日 H:i', strtotime($profile['lastTimeSignIn'])); ?>
                        <?php endif; ?>
                    </span>
                </li>
                <li>
                    <span><a href="javascript:openPasswordDialog()">修改密码</a></span>
                    <span><a href="javascript:openProfileDialog()">编辑个人资料</a></span>
                </li>
            </ul>
        </div>
    </div> <!-- #sidebar -->
    <div id="main-content">
        <ul id="tab" class="nav nav-tabs">
            <li class="active"><a href="#lectures">我的课程</a></li>
            <li><a href="#requirements">我的需求</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="lectures">
            </div> <!-- #lectures -->
            <div class="tab-pane" id="requirements">
                Requirements
            </div> <!-- #requirements -->
        </div>
    </div> <!-- #main-content -->
</div> <!-- #content -->

<!-- Edit Profile Dialog -->
<div id="mask"></div> <!-- #mask -->
<div id="dialog-container">
    <div id="profile-dialog" class="dialog">
        <div class="dialog-header">
            修改个人资料
        </div> <!-- .dialog-header -->
        <div class="dialog-content">
            <div id="profile-error" class="alert alert-error hide"></div>
            <div class="field">
                <div class="title">您的姓名</div>
                <div class="value"><input type="text" disabled="disabled" value="<?php echo $profile['real_name']; ?>" /></div>
            </div> <!-- .field -->
            <div class="field">
                <div class="title">电子邮件</div>
                <div class="value"><input type="text" name="email" value="<?php echo $profile['email']; ?>" /></div>
            </div> <!-- .field -->
            <div class="field">
                <div class="title">联系电话</div>
                <div class="value"><input type="text" name="phone" value="<?php echo $profile['phone']; ?>" /></div>
            </div> <!-- .field -->
            <div class="field">
                <button class="btn btn-primary" onclick="javascript:editProfile()">确认</button>
                <button class="btn btn-cancel"  onclick="javascript:closeProfileDialog()">取消</button>
            </div> <!-- .field -->
        </div> <!-- .dialog-content -->
    </div> <!-- #profile-dialog -->
    <div id="password-dialog" class="dialog">
        <div class="dialog-header">
            修改密码
        </div> <!-- .dialog-header -->
        <div class="dialog-content">
            <div id="password-error" class="alert alert-error hide"></div>
            <div class="field">
                <div class="title">旧密码</div>
                <div class="value"><input type="password" name="old-password" maxlength="16" /></div>
            </div> <!-- .field -->
            <div class="field">
                <div class="title">新密码</div>
                <div class="value"><input type="password" name="new-password" maxlength="16" /></div>
            </div> <!-- .field -->
            <div class="field">
                <div class="title">确认新密码</div>
                <div class="value"><input type="password" name="password-again" maxlength="16" /></div>
            </div> <!-- .field -->
            <div class="field">
                <button class="btn btn-primary" onclick="javascript:changePassword()">确认</button>
                <button class="btn btn-cancel"  onclick="javascript:closePasswordDialog()">取消</button>
            </div> <!-- .field -->
        </div> <!-- .dialog-content -->
    </div> <!-- #password-dialog -->
</div> <!-- #dialog-container -->

<?php $this->inlineScript()->captureStart(); ?>
    $('#tab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    })
<?php $this->inlineScript()->captureEnd(); ?>

<?php $this->inlineScript()->captureStart(); ?>
    function openProfileDialog() {
        setProfileDialogVisibility(true);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function closeProfileDialog() {
        setProfileDialogVisibility(false);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setProfileDialogVisibility(isVisible) {
        if ( isVisible ) {
            $('#mask').css('display', 'block');
            $('#profile-dialog').css('display', 'block');
        } else {
            $('#mask').css('display', 'none');
            $('#profile-dialog').css('display', 'none');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function editProfile() {
        var email = $('input[name=email]').val(),
            phone = $('input[name=phone]').val();

        setInputStyle(true);
        doEditProfileAction(email, phone);
        setInputStyle(false);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doEditProfileAction(email, phone) {
        var postData = 'email=' + email + '&phone=' + phone;
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/dashboard/editPersonProfile',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processProfileResult(result);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processProfileResult(result) {
        if ( result['isSuccessful'] ) {
            window.location.reload();
        } else {
            var errorMessage = '';
            if ( !result['isUserGroupLegal'] ) {
                errorMessage += '发生未知错误<br />';
            }
            if ( result['isEmailEmpty'] ) {
                errorMessage += '请填写您的电子邮件地址<br />';
            } else if ( !result['isEmailLegal'] ) {
                errorMessage += '请填写合法的电子邮件地址<br />';
            } else if ( result['isEmailExists'] ) {
                errorMessage += '该电子邮件地址已被使用, 请使用其他电子邮件地址<br />';
            } 
            if ( result['isPhoneEmpty'] ) {
                errorMessage += '请填写您的联系电话<br />';
            } else if ( !result['isPhoneLegal'] ) {
                errorMessage += '联系电话必须由数字和-组成, 且长度在7~24个字符之间<br />';
            }
            $('#profile-error').html(errorMessage);
            $('#profile-error').fadeIn();
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>

<?php $this->inlineScript()->captureStart(); ?>
    function openPasswordDialog() {
        setPasswordDialogVisibility(true);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function closePasswordDialog() {
        setPasswordDialogVisibility(false);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setPasswordDialogVisibility(isVisible) {
        if ( isVisible ) {
            $('#mask').css('display', 'block');
            $('#password-dialog').css('display', 'block');
        } else {
            $('#mask').css('display', 'none');
            $('#password-dialog').css('display', 'none');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function changePassword() {
        var oldPassword     = $('input[name=old-password]').val(),
            newPassword     = $('input[name=new-password]').val(),
            confirmPassword = $('input[name=password-again]').val();
        
        setInputStyle(true);
        doChangePasswordAction(oldPassword, newPassword, confirmPassword);
        setInputStyle(false);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doChangePasswordAction(oldPassword, newPassword, confirmPassword) {
        var postData = 'old-password=' + oldPassword + '&new-password=' + newPassword +
                       '&password-again=' + confirmPassword;
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/dashboard/changePassword',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processPasswordResult(result);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processPasswordResult(result) {
        if ( result['isSuccessful'] ) {
            closePasswordDialog();
        } else {
            var errorMessage = '';
            if ( result['isOldPasswordEmpty'] ) {
                errorMessage += '请输入您的旧密码<br />';
            } else if ( !result['isOldPasswordCorrect'] ) {
                errorMessage += '您输入的旧密码不正确<br />';
            }
            if ( result['isNewPasswordEmpty'] ) {
                errorMessage += '请输入您的新密码<br />';
            } else if ( !result['isNewPasswordLegal'] ) {
                errorMessage += '新密码的长度必须在6~16个字符之间<br />';
            }
            if ( result['isConfirmPasswordEmpty'] ) {
                errorMessage += '请确认您使用的新密码<br />';
            } else if ( !result['isConfirmPasswordMatched'] ) {
                errorMessage += '新密码与确认密码输入不一致<br />';
            }
            
            $('#password-error').html(errorMessage);
            $('#password-error').fadeIn();
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>

<?php $this->inlineScript()->captureStart(); ?>
    function setInputStyle(isLoading) {
        var processButtonObject = $('.btn-primary');
        if ( isLoading ) {
            processButtonObject.html('正在处理...');
            $('input').attr('disabled', 'disabled');
            $('button').attr('disabled', 'disabled');
        } else {
            processButtonObject.html('确认');
            $('input').removeAttr('disabled');
            $('button').removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>