<?php 
    echo $this->headTitle('注册 | ');
    echo $this->headLink()->appendStylesheet($this->cdn('/css/accounts/style.css'))
                          ->appendStylesheet($this->cdn('/css/accounts/register.css'));
?>

<div id="wrapper" class="container">
    <div id="header" class="row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath('/'); ?>">
                <img src="<?php echo $this->cdn('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="accounts" class="offset4 span4">
            <ul class="inline">
            <?php
                $session    = new Zend\Session\Container('co_session');
                if ( !$session->offsetExists('isLogined') ):
            ?>
                <li><a href="<?php echo $this->basePath('/accounts/register'); ?>">注册</a></li>
                <li>|</li>
                <li><a href="<?php echo $this->basePath('/accounts/login'); ?>">登录</a></li>
            <?php else: ?>
                <li>您好, <?php echo $session->OffsetGet('username'); ?></li>
                <li>|</li>
                <li><a href="<?php echo $this->basePath('/accounts/logout'); ?>">注销</a></li>
            <?php endif; ?>
            </ul>
        </div> <!-- #accounts -->
    </div> <!-- #header -->
    <div id="container">
        <div id="navigation">
            <ul class="inline right">
                <li><a href="<?php echo $this->basePath('/accounts/dashboard#mailbox'); ?>">收件箱</a></li>
                <li><a href="<?php echo $this->basePath('/accounts/dashboard#profile'); ?>">个人信息</a></li>
                <li><a href="<?php echo $this->basePath('/accounts/dashboard'); ?>">我的账户</a></li>
            </ul>
            <ul class="inline left">
                <li><a href="<?php echo $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?php echo $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?php echo $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath('/accounts/dashboard#requirement'); ?>">需求定制</a></li>
                <li><a href="<?php echo $this->basePath('/training/posts'); ?>">培训动态</a></li>
            </ul>
        </div> <!-- #navigation -->
        <form id="search" action="<?php echo $this->basePath('/home/search'); ?>">
            <input name="keyword" type="text" placeholder="搜索课程或讲师" />
            <button class="btn btn-success" type="submit">搜索</button>
        </form>
        <div id="content" class="row-fluid">
            <div id="register-container" class="offset1 span3">
                <form method="post" onsubmit="onSubmit(); return false;">
                    <h3>开始IT培训之旅</h3>
                    <div id="register-error" class="alert alert-error hide"></div>
                    <p>
                        <label for="username">用户名</label>
                        <input type="text" id="username" name="username" maxlength="16" />
                    </p>
                    <p>
                        <label for="email">电子邮件地址</label>
                        <input type="text" id="email" name="email" maxlength="64" />
                    </p>
                    <p>
                        <label for="password">密码</label>
                        <input type="password" id="password" name="password" maxlength="16" />
                    </p>
                    <p>
                        <label for="user-group">用户类型</label>
                        <select id="user-group" name="user-group">
                            <option value="person">个人用户</option>
                            <option value="teacher">讲师用户</option>
                            <option value="company">企业用户</option>
                        </select>
                    </p>
                    <p>
                        <label for="agree-terms">
                            <input id="agree-terms" name="agree-terms" type="checkbox" />同意<a href="<?php echo $this->basePath(); ?>/about/term">网站服务条款</a>
                        </label>
                        <button id="register-button" class="btn btn-success btn-block" type="submit">创建账户</button>
                    </p>
                </form> <!-- #login-form -->
                <p>已有账号? <a href="<?php echo $this->basePath(); ?>/accounts/login">立即登录</a></p>
            </div> <!-- #login-container -->
        </div> <!-- #content -->
    </div> <!-- #container -->
</div> <!-- #wrapper -->

<?php $this->inlineScript()->captureStart(); ?>
    function onSubmit() {
        var username    = $('input[name=username]').val(),
            email       = $('input[name=email]').val(),
            password    = $('input[name=password]').val(),
            userGroup   = $('select[name=user-group]').val(),
            isAgreeTerms= $('input[name=agree-terms]').is(':checked');

        if ( !isAgreeTerms ) {
            alert('请先同意网站服务条款!');
            return;
        }
        setButtonStyle(true);
        doRegisterAction(username, email, password, userGroup);
    };
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setButtonStyle(isLoading) {
        var registerButtonObject = $('#register-button');
        if ( isLoading ) {
            registerButtonObject.html('正在处理...');
            registerButtonObject.attr('disabled', 'disabled');
        } else {
            registerButtonObject.html('创建账户');
            registerButtonObject.removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doRegisterAction(username, email, password, userGroup) {
        var postData = {
            'username': username,
            'email': email,
            'password': password,
            'userGroup': userGroup
        };
        
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/doRegister',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processResult(result);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            window.location.href='<?php echo $this->basePath(); ?>/accounts/login';
        } else {
            var errorMessage = '';
            if ( result['isUsernameEmpty'] ) {
                errorMessage += '请填写您的用户名.<br>';
            } else if ( !result['isUsernameLegal'] ) {
                errorMessage += '用户名必须由6-16个字符的字母数字或下划线组成, 且以字母开头.<br>';
            } else if ( result['isUsernameExists'] ) {
                errorMessage += '该用户名已经存在.<br>';
            }
            if ( result['isEmailEmpty'] ) {
                errorMessage += '请填写您的电子邮件地址.<br>';
            } else if ( !result['isEmailLegal'] ) {
                errorMessage += '请填写合法的电子邮件地址.<br>';
            } else if ( result['isEmailExists'] ) {
                errorMessage += '该电子邮件地址已经存在.<br>';
            }
            if ( result['isPasswordEmpty'] ) {
                errorMessage += '请填写您的密码.<br>';
            } else if ( !result['isPasswordLegal'] ) {
                errorMessage += '密码的长度必须为6-16个字符.<br>';
            } 
            if ( !result['isUserGroupLegal'] ) {
                errorMessage += '请选择您的用户类型.<br>';
            }

            displayErrorMessage(errorMessage);
            setButtonStyle(false);
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayErrorMessage(message) {
        var errorMessageBox = $('#register-error');
        errorMessageBox.html(message);
        errorMessageBox.removeClass('hide');
    }
<?php $this->inlineScript()->captureEnd(); ?>