<?php 
    echo $this->headTitle('首页 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/home/homepage.css');
?>

<div id="header">
    <ul class="inline">
    <?php
        $session    = new Zend\Session\Container('itp_session');
        if ( !$session->offsetExists('isLogined') ):
    ?>
        <li><a href="<?php echo $this->basePath(); ?>/accounts/register">注册</a></li>
        <li>|</li>
        <li><a href="<?php echo $this->basePath(); ?>/accounts/login">登录</a></li>
    <?php else: ?>
        <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->OffsetGet('username'); ?></a></li>
        <li>|</li>
        <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
    <?php endif; ?>
    </ul>
</div> <!-- #header -->
<div id="guide">
    <div id="introduction">
        <div id="logo">
            <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
        </div> <!-- #logo -->
        <div id="slogan">
            <h3>提供最及时、最便捷的IT培训服务!</h3>
            <h4>————朱少民, 曾任思科网讯QA总监</h4>
        </div> <!-- #slogan -->
    </div> <!-- #introduction -->
    <div id="selector">
        <div id="selector-inner" class="row-fluid">
            <h4>选择课程或讲师</h4>
            <div id="course" class="span6">
                <div class="block">
                    <h4>我有心仪的<span>课程</span></h4>
                    <p>在课程库中选择适合您的课程</p>
                    <button class="btn btn-success" onclick="window.location.href='<?php echo $this->basePath(); ?>/training/courses'">查看课程库</button>
                </div> <!-- .block -->
            </div> <!-- #course -->
            <div id="teacher" class="span6">
                <div class="block">
                    <h4>我有心仪的<span>讲师</span></h4>
                    <p>在讲师团队中选择适合您的讲师</p>
                    <button class="btn btn-success" onclick="window.location.href='<?php echo $this->basePath(); ?>/training/teachers'">查看讲师团队</button>
                </div> <!-- .block -->
            </div> <!-- #teacher -->
        </div>
    </div> <!-- #selector -->
</div> <!-- #guide -->
<div id="navigation">
    <ul class="inline">
        <li>热门课程</li>
        <li>杰出讲师</li>
        <li>培训动态</li>
    </ul>
</div> <!-- #navigation -->
<div id="content">
    
</div> <!-- #content -->