<?php 
    echo $this->headTitle('搜索结果 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/training/style.css');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/training/search.css');
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath(); ?>">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath(); ?>/training/lectures">近期开课</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/courses">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/teachers">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#requirements">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/posts">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('itp_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/accounts/register'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?php echo $this->basePath(); ?>/home/search">
                <input type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div id="sub-header">
            <h2>搜索结果: 软件测试</h2>
            <p>使用搜索可以帮助您更快地查找您所需要的信息.</p>
            <button class="btn btn-orange">创建账户</button>
            <img src="<?php echo $this->basePath(); ?>/img/training/course-header.jpg" alt="Header Image">
            <div class="border-bottom"></div> <!-- .border-bottom -->
        </div> <!-- #sub-header -->
        <div id="content" class="row-fluid">
            <div class="span3">
                
            </div> <!-- .span3 -->
            <div class="span9">
                <ul id="results">
                    <li class="result row-fluid">
                        <div class="span3">
                            <img src="" alt="">
                        </div> <!-- .span3 -->
                        <div class="span9">
                            <h4><a href="#">[课程]大型软件的测试与分析</a></h4>
                            <p class="introduction">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                        </div> <!-- .span9 -->
                    </li>
                </ul>
            </div> <!-- .span8 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #container -->