<?php 
    echo $this->headTitle('搜索结果 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/training/style.css');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/home/search.css');
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath(); ?>">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath(); ?>/training/lectures">近期开课</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/courses">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/teachers">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#requirement">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/posts">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('itp_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/accounts/register'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?php echo $this->basePath(); ?>/home/search">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div id="sub-header">
            <h2>搜索结果: <?php echo $keyword; ?></h2>
            <p>使用搜索可以帮助您更快地查找您所需要的信息.</p>
            <button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/training/courses'">查看课程库</button>
            <img src="<?php echo $this->basePath(); ?>/img/training/course-header.jpg" alt="Header Image">
            <div class="border-bottom"></div> <!-- .border-bottom -->
        </div> <!-- #sub-header -->
        <div id="content" class="row-fluid">
            <div class="span3">
                <h4>筛选结果</h4>
                <ul id="category">
                    <li><a href="#all">所有结果</a></li>
                    <li><a href="#course">课程</a></li>
                    <li><a href="#teacher">讲师</a></li>
                </ul>
            </div> <!-- .span3 -->
            <div class="span9">
            <?php if ( $keyword == null ): ?>
                <div class="alert alert-error">请输入搜索的关键词.</div>
            <?php else: ?>
                <div class="alert alert-error hide">未找到相关的结果.</div>
                <ul id="results"></ul>
                <div id="pagination" class="pagination pagination-centered">
                    <ul></ul>
                </div> <!-- #pagination-->
            <?php endif; ?>
            </div> <!-- .span8 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #container -->

<script type="text/javascript">
    function getSearchResult(keyword, category, pageNumber) {

    }
</script>
<script type="text/javascript">
    function displaySearchResult(searchResult) {

    }
</script>
<script type="text/javascript">
    $('#pagination > ul').delegate('li', 'click', function(e) {
        e.preventDefault();
        if ( $(this).hasClass('disabled') ) {
            return;
        }
        var currentPage = $('li.active > a', '#pagination').html();
        
        $('#pagination > li.active').removeClass('active');
        $(this).addClass('active');
        var category    = $('ul#course-types > li.active > a').attr('href').substring(1),
            pageNumber  = $('a', this).html();

        if ( pageNumber === '&lt;' ) {
            pageNumber  = currentPage - 1;
        } else if ( pageNumber === '&gt;' ) {
            pageNumber  = currentPage + 1;
        }
        getTeachers(category, pageNumber);
        getTotalPages(category, pageNumber);
    });
</script>
<script type="text/javascript">
    function getTotalPages(keyword, category, pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/home/getSearchResultTotalPages?keyword=' + keyword + '&category=' + category,
            dataType: 'JSON',
            success: function(result) {
                $('div#pagination > ul').empty();
                if ( result['isSuccessful'] ) {
                    $('div#pagination').removeClass('hide');
                    displayPagination(pageNumber, result['totalPages']);
                } else {
                    $('div#pagination').addClass('hide');
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function displayPagination(currentPage, totalPages) {
        var lowerBound = ( currentPage - 5 > 0 ? currentPage - 5 : 1 ),
            upperBound = ( currentPage + 5 < totalPages ? currentPage + 5 : totalPages );
        var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="#">&gt;</a></li>';
        $('#pagination > ul').append(paginationString);
    }
</script>
<script type="text/javascript">
    $(document).ready(function() {
        var keyword     = <?php echo $keyword; ?>,
            category    = 'all';
        getSearchResult(keyword, category, 1);
        getTotalPages(keyword, category, 1);
    });
</script>