<?php 
    echo $this->headTitle('搜索结果 | ');
    echo $this->headLink()->appendStylesheet($this->basePath('/css/training/style.css'))
                          ->appendStylesheet($this->basePath('/css/search.css'));
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?= $this->basePath('/'); ?>">
                <img src="<?= $this->basePath('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?= $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?= $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?= $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?= $this->basePath('/accounts/dashboard#requirements'); ?>">需求定制</a></li>
                <li><a href="<?= $this->basePath('/training/posts'); ?>">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?= $this->basePath('/accounts/login'); ?>"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?= $this->basePath('/accounts/register'); ?>'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?= $this->basePath('/accounts/dashboard'); ?>"><?= $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?= $this->basePath('/accounts/logout'); ?>">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?= $this->basePath('/search'); ?>">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div id="sub-header">
            <h2>搜索结果: <?= $keyword; ?></h2>
            <p>使用搜索可以帮助您更快地查找您所需要的信息.</p>
            <button class="btn btn-orange" onclick="window.location.href='<?= $this->basePath('/training/courses'); ?>'">查看课程库</button>
            <img src="<?= $this->basePath('/img/training/search-header.jpg'); ?>" alt="Header Image">
            <div class="border-bottom"></div> <!-- .border-bottom -->
        </div> <!-- #sub-header -->
        <div id="content" class="row-fluid">
            <div class="span3">
                <h4>筛选结果</h4>
                <ul id="category">
                    <li><a href="#all">所有结果</a></li>
                    <li><a href="#course">课程</a></li>
                    <li><a href="#teacher">讲师</a></li>
                </ul>
            </div> <!-- .span3 -->
            <div class="span9">
            <?php if ( $keyword == null ): ?>
                <div class="alert alert-error">请输入搜索的关键词.</div>
            <?php else: ?>
                <div class="alert alert-warning hide">未找到相关的结果.</div>
                <ul id="results">
                </ul>
                <button id="more-button" class="btn btn-block">查看更多结果</button>
            <?php endif; ?>
            </div> <!-- .span8 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #container -->

<?php $this->inlineScript()->captureStart(); ?>
    function getSearchResult(keyword, category, pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?= $this->basePath('/getSearchResult'); ?>?keyword=' + keyword + '&page=' + pageNumber,
            dataType: 'JSON',
            success: function(result) {
                if ( result['isSuccessful'] ) {
                    $('.alert-warning').addClass('hide');
                    $('#more-button').removeClass('hide');
                    displaySearchResult(result['searchResult']);
                } else {
                    $('.alert-warning').removeClass('hide');
                    $('#more-button').addClass('hide');
                }
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displaySearchResult(result) {
        var numberOfTeachers            = result['teachers'].length,
            numberOfCourses             = result['courses'].length,
            NUMBER_OF_RECORDS_PER_PAGE  = 10;
        for ( var i = 0; i < numberOfTeachers; ++ i ) {
            $('ul#results').append('<li class="teacher row-fluid">' +
                                   '    <div class="span3">' + 
                                   '        <img src="<?= $this->basePath('/img/avatars/'); ?>' + 
                                                ( result['teachers'][i]['avatar'] === null ? 'avatar-wide.jpg' : result['teachers'][i]['avatar'] ) + '" alt="avatar" />' +
                                   '    </div>' +
                                   '    <div class="span9">' + 
                                   '        <h4>[讲师] <a href="<?= $this->basePath('/training/teacher')?>?teacherId=' + result['teachers'][i]['uid'] + '">' + result['teachers'][i]['teacherName'] + '</a></h4>' +
                                   '        <p class="introduction">' + result['teachers'][i]['brief'] + '</p>' +
                                   '        <ul class="inline meta">' + 
                                   '            <li><i class="fa fa-share-sign"></i> ' + result['teachers'][i]['teachingField'] + '</li>' + 
                                   '            <li><i class="fa fa-home"></i> ' + result['teachers'][i]['company'] + '</li>' + 
                                   '        </ul>' +
                                   '    </div>' +
                                   '</li>');
        }
        for ( var i = 0; i < numberOfCourses; ++ i ) {
            $('ul#results').append('<li class="course row-fluid">' +
                                   '    <div class="span3">' + 
                                   '        <img src="<?= $this->basePath('/img/categories/'); ?>' + result['courses'][i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />' +
                                   '    </div>' +
                                   '    <div class="span9">' + 
                                   '        <h4>[课程] <a href="<?= $this->basePath('/training/course')?>?courseId=' + result['courses'][i]['courseId'] + '">' + result['courses'][i]['courseName'] + '</a></h4>' +
                                   '        <p class="introduction">' + result['courses'][i]['brief'] + '</p>' +
                                   '        <ul class="inline meta">' + 
                                   '            <li><i class="fa fa-user"></i> <a href="<?= $this->basePath('/training/teacher'); ?>?teacherId=' + result['courses'][i]['teacherId'] + '">' + result['courses'][i]['teacherName'] + '</a></li>' +
                                   '            <li><i class="fa fa-tasks"></i> ' + result['courses'][i]['courseTypeName'] + '</li>' +
                                   '        </ul>' +
                                   '    </div>' +
                                   '</li>');
        }
        if ( numberOfTeachers + numberOfCourses < NUMBER_OF_RECORDS_PER_PAGE ) {
            $('#more-button').html('已加载全部结果');
            $('#more-button').attr('disabled', 'disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(function() {
        var keyword     = '<?= $keyword == '\'' ? '\'' : $keyword ; ?>',
            category    = 'all';
        getSearchResult(keyword, category, 1);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('ul#category a').click(function() {
        var category            = $(this).attr('href').substring(1),
            numberOfRecords     = $('ul#results > li').length,
            numberOfTeachers    = $('li.teacher').length,
            numberOfCourses     = $('li.course').length;

        $('.alert-warning').addClass('hide');

        if ( category == 'all' ) {
            $('li.teacher').css('display', 'block');
            $('li.course').css('display', 'block');
        } else if ( category == 'teacher' ) {
            $('li.teacher').css('display', 'block');
            $('li.course').css('display', 'none');

            if ( numberOfRecords == numberOfCourses ) {
                $('.alert-warning').removeClass('hide');
            }
        } else if ( category == 'course' ) {
            $('li.teacher').css('display', 'none');
            $('li.course').css('display', 'block');

            if ( numberOfRecords == numberOfTeachers ) {
                $('.alert-warning').removeClass('hide');
            }
        }
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('#more-button').click(function() {
        var keyword     = '<?= $keyword == '\'' ? '\'' : $keyword ; ?>',
            category    = 'all',
            NUMBER_OF_RECORDS_PER_PAGE  = 10,
            currentRecords              = $('ul#results > li').length - 1,
            currentPage                 = Math.floor(currentRecords / NUMBER_OF_RECORDS_PER_PAGE),
            pageNumber                  = currentPage + 1;
        getSearchResult(keyword, category, pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>