<?php 
    echo $this->headTitle('需求定制 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/solutions/requirement.css')
                          ->appendStylesheet($this->basePath().'/css/datetimepicker.min.css');
    echo $this->headScript()->appendFile($this->basePath().'/js/stick-up.min.js')
                            ->appendFile($this->basePath().'/js/datetimepicker.min.js')
                            ->appendFile($this->basePath().'/js/datetimepicker.zh-CN.js');
?>

<div id="content">
    <div id="banner">
        <div id="banner-content">
            <div id="slogan">
                <h2>需求定制</h2>
                <h4>为您量身定制的培训</h4>
            </div> <!-- #slogan -->
            <form id="search" class="navbar-search pull-right">
                <input type="text" class="search-query" />
                <button type="submit" class="btn btn-success">搜索</button>
            </form>
        </div> <!-- #banner-content -->
    </div> <!-- #banner -->
    <div id="main-container">
        <div id="main-content">
            <div id="sidebar">
                <h4>分类目录</h4>
                <ul class="nav nav-pills nav-stacked">

                </ul>
            </div> <!-- #sidebar -->
            <div id="requirement-content">
                <h4>请填写如下表单, 我们将会尽快与您联系</h4>
                <div class="alert alert-error hide"></div> <!-- .alert -->
                <div class="section">
                <?php if ( $profile['userGroupSlug'] == 'Company' ): ?>
                    <label for="name">公司名称</label>
                <?php else: ?>
                    <label for="name">您的姓名</label>
                <?php endif; ?>
                <input id="name" class="span6" disabled="disabled" type="text" value="<?php echo $profile['name']; ?>" />
                </div> <!-- .section -->
                <div class="section">
                    <label for="phone">联系电话</label>
                    <input id="phone" class="span6" disabled="disabled" type="text" value="<?php echo $profile['phone']; ?>" />
                </div> <!-- .section -->
                <div class="section">
                    <label for="teacher-name">讲师</label>
                    <input id="teacher-name" class="span6" type="text" /><br />
                    <input id="teacher-uid" type="hidden" value="0" />
                    <table id="teacher-list" class="span6">
                        <tbody></tbody>
                    </table>
                    <span>请填写心仪讲师的姓名; 您可以留空, 我们会为您联系合适的讲师.</span>
                </div> <!-- .section -->
                <div class="section">
                    <label for="participants">培训人数</label>
                    <div class="input-append">
                        <?php if ( $profile['userGroupSlug'] == 'Company' ): ?>
                        <input class="span3" id="participants" type="text" maxlength="4" />
                        <?php else: ?>
                        <input class="span3" id="participants" type="text" value="1" maxlength="4" />
                        <?php endif; ?>
                        <span class="add-on">人</span>
                    </div><br />
                    <span>请填写需要被培训的人数, 以便讲师准备合适的培训内容</span>
                </div> <!-- .section -->
                <div class="section">
                    <label for="start-time">培训起始时间</label>
                    <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">
                        <input id="start-time" size="16" type="text" value="" readonly>
                        <span class="add-on"><i class="icon-remove"></i></span>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div><br />
                </div> <!-- .section -->
                <div class="section">
                    <label for="end-time">培训结束时间</label>
                    <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">
                        <input id="end-time" size="16" type="text" value="" readonly>
                        <span class="add-on"><i class="icon-remove"></i></span>
                        <span class="add-on"><i class="icon-th"></i></span>
                    </div><br />
                </div> <!-- .section -->
                <div class="section">
                    <label for="place">培训地点</label>
                    <input id="place" class="span6" type="text" maxlength="256" /><br />
                    <span>请填写您心仪的培训地点</span>
                </div> <!-- .section -->
                <div class="section">
                    <label for="requirement">需求描述</label>
                    <textarea id="requirement" class="span6" rows="10"></textarea>
                </div> <!-- .section -->
                <div class="section">
                    <button id="submit" class="btn btn-primary">提交</button>
                    <button class="btn">重置</button>
                </div>                
            </div> <!-- #requirement-content -->
        </div> <!-- #main-content -->
    </div> <!-- #main-container -->
</div> <!-- #content -->

<?php $this->inlineScript()->captureStart(); ?>
    jQuery(function($) {
        $(document).ready( function() {
            $('#sidebar').stickUp();
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(window).scroll(function() {
        setSidebarVisibility();
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setSidebarVisibility() {
        var sidebarHeight   = $('#sidebar').outerHeight(),
            headerHeight    = $('#header').outerHeight(),
            footerOffsetTop = $('#footer').offset().top - $(window).scrollTop() - headerHeight,
            offset          = footerOffsetTop - sidebarHeight - headerHeight;
        if ( footerOffsetTop < sidebarHeight ) {
            $('#sidebar').css('top', offset);
        } else {
            if ( $('#sidebar').hasClass('isStuck') ) {
                $('#sidebar').css('top', 96);
            } else {
                $('#sidebar').css('top', 0);
            }
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<script type="text/javascript">
    $('.form_datetime').datetimepicker({
        language:  'zh-CN',
        weekStart: 1,
        todayBtn:  1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1
    });
</script>
<script type="text/javascript">
    $('#teacher-name').on("input",function(e) {
        var keyword = $(this).val();
        return getTeacherList(keyword);
    });
</script>
<script type="text/javascript">
    function getTeacherList(keyword) {
        if ( keyword == '' ) {
            $('#teacher-list').css('display', 'none');
            return;
        }

        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/solutions/requirement/getTeachers?keyword=' + keyword,
            dataType: 'JSON',
            success: function(teacherList) {
                processTeacherList(teacherList);
            }
        })
    }
</script>
<script type="text/javascript">
    function processTeacherList(teacherList) {
        $('#teacher-list tbody').empty();

        if ( teacherList.length == 0 ) {
            $('#teacher-list tbody').append('<tr><td>未找到相关讲师</td></tr>');
        } else {
            for ( var i = 0; i < teacherList.length; ++ i ) {
                var teacher     = teacherList[i],
                    avatarUrl   = '';
                
                if ( teacher['teacher_avatar'] == null ) {
                    avatarUrl = '/img/avatars/silhouette.png';
                } else {
                    avatarUrl = teacher['teacher_avatar'];
                }
                $('#teacher-list tbody').append(
                    '<tr class=uid-' + teacher['uid'] + '>' + 
                    '<td class="span1"><img src="<?php echo $this->basePath(); ?>' + avatarUrl + '" alt="avatar" /></td>' +
                    '<td>' + teacher['teacher_name'] + '</td>' +
                    '</tr>'
                );
            }
        }
        $('#teacher-list').css('display', 'table');
    }
</script>
<script type="text/javascript">
    $('#teacher-list').delegate('tr', 'click', function() {
        var teacher             = $(this).attr('class'),
            teacherNameField    = $(this).find('td').last();
        
        $('#teacher-name').val('');
        $('#teacher-uid').val('0');
        if ( teacher != null ) {
            var teacherUid      = teacher.substring(4),
                teacherName     = teacherNameField.text();

            $('#teacher-name').val(teacherName);
            $('#teacher-uid').val(teacherUid);
        }

        $('#teacher-list').css('display', 'none');
    });
</script>

<script type="text/javascript">
    $('#submit').click(function() {
        var requirementObject = {
            teacherUid:     $('#teacher-uid').val(),
            participants:   $('#participants').val(),
            startTime:      $('#start-time').val(),
            endTime:        $('#end-time').val(),
            place:          $('#place').val(),
            detail:         $('#requirement').val()
        };

        setInputStyle(true);
        doSubmitAction(requirementObject);
    });
</script>
<?php $this->inlineScript()->captureStart(); ?>
    function setInputStyle(isLoading) {
        var submitButtonObject = $('#submit');
        if ( isLoading ) {
            submitButtonObject.html('正在处理您的需求...');
            $('input').attr('disabled', 'disabled');
            $('textarea').attr('disabled', 'disabled');
            $('select').attr('disabled', 'disabled');
            $('button').attr('disabled', 'disabled');
        } else {
            submitButtonObject.html('提交');
            $('input').removeAttr('disabled');
            $('textarea').removeAttr('disabled');
            $('select').removeAttr('disabled');
            $('button').removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<script type="text/javascript">
    function doSubmitAction(requirementObject) {
        var postData = getPostData(requirementObject);
        
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/solutions/requirement/process',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processResult(result);
            }
        });
    }
</script>
<script type="text/javascript">
    function getPostData(requirementObject) {
        var postData = 'teacher-uid=' + requirementObject['teacherUid'] +
                      '&participants=' + requirementObject['participants'] +
                      '&start-time=' + requirementObject['startTime'] + 
                      '&end-time=' + requirementObject['endTime'] + 
                      '&place=' + requirementObject['place'] + 
                      '&detail=' + requirementObject['detail'];
        return postData;
    }
</script>
<script type="text/javascript">
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            window.location.href='<?php echo $this->basePath(); ?>/accounts/dashboard'
        } else {
            var errorMessage = '';

            if ( !result['isTeacherUidLegal'] ) {
                errorMessage += '所选择的教师不存在<br />';
            }
            if ( result['isParticipantsEmpty'] ) {
                errorMessage += '请填写培训人数<br />';
            } else if ( !result['isParticipantsLegal'] ) {
                errorMessage += '培训人数必须是一个数字<br />';
            }
            if ( result['isStartTimeEmpty'] ) {
                errorMessage += '请选择培训开始时间<br />';
            } else if ( !result['isStartTimeLegal'] ) {
                errorMessage += '培训开始时间不得早于当前时间<br />';
            }
            if ( result['isEndTimeEmpty'] ) {
                errorMessage += '请选择培训结束时间<br />';
            } else if ( !result['isEndTimeLegal'] ) {
                errorMessage += '培训结束时间不得早于开始时间<br />';
            }
            if ( result['isPlaceEmpty'] ) {
                errorMessage += '请填写培训地点<br />';
            } else if ( !result['isPlaceLegal'] ) {
                errorMessage += '培训地点不得超过256个字符<br />';
            }
            if ( result['isDetailEmpty'] ) {
                errorMessage += '请填写培训需求<br />';
            }

            $('.alert-error').html(errorMessage);
            $('.alert-error').fadeIn();
            scrollToTop();
        }
        setInputStyle(false);

        $('input#name').attr('disabled', 'disabled');
        $('input#phone').attr('disabled', 'disabled');
    }
</script>