<?php 
    echo $this->headTitle('个人中心 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/style.css');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/dashboard.css');
?>

<div id="wrapper" class="container">
    <div id="header" class="row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath(); ?>">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="accounts" class="offset4 span4">
            <ul class="inline">
            <?php
                $session    = new Zend\Session\Container('itp_session');
                if ( !$session->offsetExists('isLogined') ):
            ?>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/register">注册</a></li>
                <li>|</li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/login">登录</a></li>
            <?php else: ?>
                <li>您好, <?php echo $session->OffsetGet('username'); ?></li>
                <li>|</li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
            <?php endif; ?>
            </ul>
        </div> <!-- #accounts -->
    </div> <!-- #header -->
    <div id="container">
        <div id="navigation">
            <ul class="inline left">
                <li><a href="<?php echo $this->basePath(); ?>/training/lectures">近期开课</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/courses">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/teachers">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#requirements">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/posts">培训动态</a></li>
            </ul>
            <ul class="inline right">
                <li><a href="<?php echo $this->basePath(); ?>/accounts#mailbox">收件箱</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#profile">个人信息</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard">我的账户</a></li>
            </ul>
        </div> <!-- #navigation -->
        <form id="search" action="<?php echo $this->basePath(); ?>/home/search">
            <input name="keyword" type="text" placeholder="搜索课程或讲师" />
            <button class="btn btn-success" type="submit">搜索</button>
        </form>
        <div id="content" class="row-fluid">
            <div id="sidebar" class="span3">
                <div id="profile">
                    <img src="<?php echo $this->basePath(); ?>/img/avatars/avatar.png" alt="avatar" class="img-circle" />
                    <span>您好, 谢浩哲</span>
                </div> <!-- #profile -->
                <div id="sidebar-nav">
                    <ul id="nav">
                        <li class="active"><a href="#lectures">我的培训课</a></li>
                        <li><a href="#comments">我的评价</a></li>
                        <li><a href="#requirements">我的需求</a></li>
                    </ul>
                </div> <!-- #sidebar-nav -->
            </div> <!-- #sidebar -->
            <div id="main-content" class="span9">
                456
            </div> <!-- .main-content -->
        </div> <!-- #content -->
    </div> <!-- #container -->
</div> <!-- #wrapper -->