<?= $this->headTitle('登录 | '); ?>
<?= $this->headLink()->appendStylesheet($this->basePath('/css/accounts/style.css'))
                     ->appendStylesheet($this->basePath('/css/accounts/login.css')); ?>
<?= $this->headScript()->appendFile($this->basePath('/js/md5.js')); ?>

<div id="wrapper" class="container">
    <div id="header" class="row-fluid">
        <div id="logo" class="span4">
            <a href="<?= $this->basePath('/'); ?>">
                <img src="<?= $this->basePath('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="accounts" class="offset4 span4">
            <ul class="inline">
            <?php
                $session    = new Zend\Session\Container('co_session');
                if ( !$session->offsetExists('isLogined') ):
            ?>
                <li><a href="<?= $this->basePath('/accounts/register'); ?>">注册</a></li>
                <li>|</li>
                <li><a href="<?= $this->basePath('/accounts/login'); ?>">登录</a></li>
            <?php else: ?>
                <li>您好, <?= $session->offsetGet('username'); ?></li>
                <li>|</li>
                <li><a href="<?= $this->basePath('/accounts/logout'); ?>">注销</a></li>
            <?php endif; ?>
            </ul>
        </div> <!-- #accounts -->
    </div> <!-- #header -->
    <div id="container">
        <div id="navigation">
            <ul class="inline right">
                <li><a href="<?= $this->basePath('/accounts/dashboard#mailbox'); ?>">收件箱</a></li>
                <li><a href="<?= $this->basePath('/accounts/dashboard#profile'); ?>">个人信息</a></li>
                <li><a href="<?= $this->basePath('/accounts/dashboard'); ?>">我的账户</a></li>
            </ul>
            <ul class="inline left">
                <li><a href="<?= $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?= $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?= $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?= $this->basePath('/accounts/dashboard#requirement'); ?>">需求定制</a></li>
                <li><a href="<?= $this->basePath('/training/posts'); ?>">培训动态</a></li>
            </ul>
        </div> <!-- #navigation -->
        <form id="search" action="<?= $this->basePath('/search'); ?>">
            <input name="keyword" type="text" placeholder="搜索课程或讲师" />
            <button class="btn btn-success" type="submit">搜索</button>
        </form>
        <div id="content" class="row-fluid">
            <div id="login-container" class="offset1 span3">
                <form method="post" onsubmit="onSubmit(); return false;">
                    <h3>用户登录</h3>
                    <div id="login-error" class="alert alert-error hide"></div>
                    <p>
                        <label for="username">用户名或电子邮件地址</label>
                        <input type="text" id="username" name="username" maxlength="48" />
                    </p>
                    <p>
                        <label for="password"><span id="forget-password"><a href="<?= $this->basePath(); ?>/accounts/resetPassword">忘记密码?</a></span>密码</label>
                        <input type="password" id="password" name="password" maxlength="16" />
                    </p>
                    <p>
                        <label for="remember-me">
                            <input id="remember-me" name="remember-me" type="checkbox" />保持登录状态
                        </label>
                        <button id="login-button" class="btn btn-success btn-block" type="submit">登录</button>
                    </p>
                </form> <!-- #login-form -->
                <p>还没有账号? <a href="<?= $this->basePath(); ?>/accounts/register">立即注册</a></p>
            </div> <!-- #login-container -->
        </div> <!-- #content -->
    </div> <!-- #container -->
</div> <!-- #wrapper -->

<?php $this->inlineScript()->captureStart(); ?>
    function onSubmit() {
        var username    = $('input[name=username]').val(),
            password    = md5($('input[name=password]').val()),
            rememberMe  = $('input[name=remember-me]').is(':checked');

        setButtonStyle(true);
        $('input[name=password]').val(password);
        doLoginAction(username, password, rememberMe);
    };
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setButtonStyle(isLoading) {
        var loginButtonObject = $('#login-button');
        if ( isLoading ) {
            loginButtonObject.html('正在登录...');
            loginButtonObject.attr('disabled', 'disabled');
        } else {
            loginButtonObject.html('登录');
            loginButtonObject.removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doLoginAction(username, password, rememberMe) {
        var postData = {
            'username': username,
            'password': password,
            'rememberMe': rememberMe
        };
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?= $this->basePath(); ?>/accounts/doLogin',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processResult(result);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            window.location.href='<?= $this->basePath($forwardUrl); ?>';
        } else {
            if ( result['isUsernameEmpty'] && result['isPasswordEmpty'] ) {
                displayErrorMessage('请输入用户名或电子邮件地址.<br />请输入密码.');
            } else if ( result['isUsernameEmpty'] ) {
                displayErrorMessage('请输入用户名或电子邮件地址.');
            } else if ( result['isPasswordEmpty'] ) {
                displayErrorMessage('请输入密码.');
            } else if ( !result['isAccountValid'] ) {
                displayErrorMessage('用户名或密码不正确.');
            }
            $('input[name=password]').val('');

            setButtonStyle(false);
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayErrorMessage(message) {
        var errorMessageBox = $('#login-error');
        errorMessageBox.html(message);
        errorMessageBox.removeClass('hide');
    }
<?php $this->inlineScript()->captureEnd(); ?>
