<?php 
    echo $this->headTitle('重置密码 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/style.css');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/reset-password.css');
?>

<div id="wrapper" class="container">
    <div id="header" class="row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath(); ?>">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="accounts" class="offset4 span4">
            <ul class="inline">
            <?php
                $session    = new Zend\Session\Container('itp_session');
                if ( !$session->offsetExists('isLogined') ):
            ?>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/register">注册</a></li>
                <li>|</li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/login">登录</a></li>
            <?php else: ?>
                <li>您好, <?php echo $session->OffsetGet('username'); ?></li>
                <li>|</li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
            <?php endif; ?>
            </ul>
        </div> <!-- #accounts -->
    </div> <!-- #header -->
    <div id="container">
        <div id="navigation">
            <ul class="inline right">
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#mailbox">收件箱</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#profile">个人信息</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard">我的账户</a></li>
            </ul>
            <ul class="inline left">
                <li><a href="<?php echo $this->basePath(); ?>/training/lectures">近期开课</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/courses">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/teachers">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#requirement">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/posts">培训动态</a></li>
            </ul>
        </div> <!-- #navigation -->
        <form id="search" action="<?php echo $this->basePath(); ?>/home/search">
            <input name="keyword" type="text" placeholder="搜索课程或讲师" />
            <button class="btn btn-success" type="submit">搜索</button>
        </form>
        <div id="content" class="row-fluid">
            <div id="logo-sidebar" class="span4 text-right">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo">
            </div> <!-- .logo-sidebar -->
            <div id="reset-container" class="span8">
            <?php if ( !$isConfidentialSetted ): ?>
                <form id="reset-form" method="post" onsubmit="onSubmit(); return false;">
                    <h3>忘记密码?</h3>
                    <p>请告诉我们您的用户名和电子邮件地址, 我们会将重设密码说明发送给您.</p>
                    <div class="alert alert-error hide">无效的用户信息. 请确认您的用户名和电子邮件是否正确.</div>
                    <p>
                        <label for="username">用户名</label>
                        <input type="text" id="username" name="username" maxlength="16" />
                    </p>
                    <p>
                        <label for="username">电子邮件地址</label>
                        <input type="text" id="email" name="email" maxlength="64" />
                    </p>
                    <p>
                        <button id="reset-button" class="btn btn-success" type="submit">重置密码</button>
                    </p>
                </form> <!-- #reset-form -->
                <div id="email-sent" class="hide">
                    <h2>电子邮件已发出</h2>
                    <div class="alert alert-success">请查看收件箱, 我们已向您发出重设密码说明. 如果您未在两小时内收到此邮件, 请与我们联系.</div>
                </div> <!-- #email-sent -->
            <?php else: ?>
                <?php if ( !$isConfidentialValid ): ?>
                    <div id="invalid-confidential">
                        <h3>重置密码</h3>
                        <div class="alert alert-error">无效用户信息. 请确保您输入的网址与重置通知电邮中的网址完全一致.</div>
                    </div> <!-- #invalid-confidential -->
                <?php else: ?>
                    <form id="reset-form" method="post" onsubmit="onSubmit(); return false;">
                        <h3>重置密码</h3>
                        <div class="alert alert-error hide"></div> <!-- .alert-error -->
                        <p>
                            <label for="new-password">新密码</label>
                            <input type="password" id="new-password" name="new-password" maxlength="16" />
                        </p>
                        <p>
                            <label for="confirm-password">确认新密码</label>
                            <input type="password" id="confirm-password" name="confirm-password" maxlength="16" />
                        </p>
                        <button id="reset-button" class="btn btn-success" type="submit">重置密码</button>
                    </form> <!-- #reset-form -->
                    <div id="password-resetted" class="hide">
                        <h3>密码已重置</h3>
                        <div class="alert alert-success">我们已重置您的密码. 单击<a href="<?php echo $this->basePath(); ?>/accounts/login">此处</a>登录您的账户.</div>
                    </div> <!-- #password-resetted -->
                <?php endif; ?>
            <?php endif; ?>
            </div> <!-- #reset-container -->
        </div> <!-- #content -->
    </div> <!-- #container -->
</div> <!-- #wrapper -->

<?php $this->inlineScript()->captureStart(); ?>
    function setButtonStyle(isLoading) {
        var resetButtonObject = $('#reset-button');
        if ( isLoading ) {
            $('.alert-error').addClass('hide');
            resetButtonObject.html('正在处理...');
            resetButtonObject.attr('disabled', 'disabled');
        } else {
            resetButtonObject.html('重置密码');
            resetButtonObject.removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>

<?php if ( !$isConfidentialSetted ): ?>
<?php $this->inlineScript()->captureStart(); ?>
    function onSubmit() {
        var username    = $('input[name=username]').val(),
            email       = $('input[name=email]').val();

        setButtonStyle(true);
        doConfirmConfidentialAction(username, email);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doConfirmConfidentialAction(username, email) {
        var postData = 'username=' + username + '&email=' + email;
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/doConfirmConfidential',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processResult(result);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            $('#reset-form').addClass('hide');
            $('#email-sent').removeClass('hide');
        } else {
            $('.alert-error').removeClass('hide');
            setButtonStyle(false);
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php elseif ( $isConfidentialValid ): ?>
<?php $this->inlineScript()->captureStart(); ?>
    function onSubmit() {
        var email           = '<?php echo $this->email; ?>',
            keycode         = '<?php echo $this->keycode; ?>',
            newPassword     = $('#new-password').val(),
            confirmPassword = $('#confirm-password').val();

        setButtonStyle(true);
        doResetPasswordAction(email, keycode, newPassword, confirmPassword);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doResetPasswordAction(email, keycode, newPassword, confirmPassword) {
        var postData = 'email=' + email + '&keycode=' + keycode + 
                      '&newPassword=' + newPassword + '&confirmPassword=' + confirmPassword;
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->basePath(); ?>/accounts/doResetPassword',
            data: postData,
            dataType: 'JSON',
            success: function(result){
                return processResetResult(result);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processResetResult(result) {
        if ( result['isSuccessful'] ) {
            $('#reset-form').addClass('hide');
            $('#password-resetted').removeClass('hide');
        } else {
            var errorMessage = '';

            if ( result['isPasswordEmpty'] ) {
                errorMessage += '请输入新密码.<br />'
            }
            if ( !result['isPasswordLegal'] ) {
                errorMessage += '新密码的长度必须在6~16个字符之间.<br />'
            }
            if ( !result['isPasswordMatched'] ) {
                errorMessage += '新密码和确认新密码输入不匹配.<br />'
            }
            if ( !result['isKeyCodeValid'] ) {
                errorMessage += '您无权修改该账户的密码.<br />'
            }
            
            $('.alert-error').removeClass('hide');
            $('.alert-error').html(errorMessage);
            setButtonStyle(false);
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php endif; ?>