<?php 
    echo $this->headTitle($lecture['lecture_name'].' | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/solutions/style.css');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/solutions/lecture.css');
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath(); ?>">
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath(); ?>/solutions/lecture">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/solutions/teacher">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard/requirement">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/solutions/news">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('itp_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/accounts/register'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?php echo $this->basePath(); ?>/solutions/search">
                <input type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div class="span9">
            General
        </div> <!-- .span9 -->
        <div class="span3">
            Meta
        </div> <!-- .span3 -->
        <p><?php var_dump($teacher); ?></p>
        <p><?php var_dump($lecture); ?></p>
        <p><?php var_dump($comments); ?></p>
    </div> <!-- .container -->
</div> <!-- #container -->