<h3>培训动态管理</h3>
<div class="row-fluid">
    <div class="span6">
        <form class="row-fluid" onSubmit="getFilters(1); return false;">
            <select name="post-category" class="span3">
                <option value="all">全部培训动态分类</option>
            <?php foreach ( $postCategories as $postCategory ): ?>
				<option value="<?php echo $postCategory['postCategorySlug']; ?>"><?php echo $postCategory['postCategoryName']; ?></option>
        	<?php endforeach; ?>
            </select>
            <select name="publish-time" class="span3">
                <option value="all">全部时间段</option>
            <?php 
                foreach ( $publishMonths as $publishMonth ): 
                    $date  = explode(', ', $publishMonth->postDate);
                    $year  = $date[0];
                    $month = $date[1];
            ?>
                <option value="<?php echo $year; ?>-<?php echo sprintf("%02d", $month); ?>"><?php echo $year ?>年<?php echo $month ?>月</option>
            <?php endforeach; ?>
            </select>
            <button class="btn" type="submit">筛选</button>
        </form>
    </div> <!-- .span6 -->
    <div class="span6 text-right">
        <form onSubmit="getPostsUsingKeyword(); return false;">
            <input id="keyword" type="text" />
            <button class="btn">搜索培训动态</button>
        </form>
    </div> <!-- .span6 -->
</div> <!-- .row-fluid -->
<div class="row-fluid">
    <div class="span6">
        <ul id="controls" class="inline">
            <li><a href="javascript:newPost();"><i class="fa fa-plus"></i> 新培训动态</a></li>
        </ul>
    </div> <!-- .span6 -->
    <div id="pagination" class="span6 text-right">
        <div class="pagination">
            <ul></ul>
        </div> <!-- .pagination -->
    </div> <!-- #pagination -->
</div> <!-- .row-fluid -->
<table id="posts" class="table table-striped">
    <thead>
        <th>#</th>
        <th>标题</th>
        <th>分类</th>
        <th>发布日期</th>
    </thead>
    <tbody></tbody>
</table>

<!-- Modals -->
<div id="post-editor" class="modal hide fade">
    <div class="modal-header">
        <h4>新培训动态</h4>
    </div> <!-- .modal-header -->
    <div class="modal-body">
        <div class="alert alert-error hide"></div> <!-- .alert-error -->
        <div class="row-fluid">
            <div class="span4">
                <label for="post-title">培训动态标题</label>
            </div> <!-- .span4 -->
            <div class="span8">
                <input id="post-id" type="hidden" />
                <input id="post-title" class="span12" type="text" />
            </div> <!-- .span8 -->
        </div> <!-- .row-fluid -->
        <div class="row-fluid">
            <div class="span4">
                <label for="post-category">培训动态分类</label>
            </div> <!-- .span4 -->
            <div class="span8">
                <select id="post-category" class="span12">
                <?php foreach ( $postCategories as $postCategory ): ?>
                    <option value="<?php echo $postCategory['postCategorySlug']; ?>"><?php echo $postCategory['postCategoryName']; ?></option>
                <?php endforeach; ?>
                </select>
            </div> <!-- .span8 -->
        </div> <!-- .row-fluid -->
        <div class="row-fluid">
            <div class="span4">
                <label for="post-content">培训动态内容</label>
            </div> <!-- .span4 -->
            <div class="span8">
                <textarea id="post-content" class="span12" rows="10"></textarea>
            </div> <!-- .span8 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .modal-body -->
    <div class="modal-footer">
        <button class="btn btn-primary">确认</button>
        <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
    </div> <!-- .modal-footer -->
</div> <!-- modal -->

<script type="text/javascript">
    function getFilters(pageNumber) {
        var category     = $('select[name=post-category]').val(),
            publishMonth = $('select[name=publish-time]').val();

        getPosts(pageNumber, category, publishMonth);
        getPostTotalPages(pageNumber, category, publishMonth);
    }
</script>
<script type="text/javascript">
    function getPosts(pageNumber, category, publishMonth) {
        $.ajax({
            type: 'GET',
            url: "<?php echo $this->basePath(); ?>/administration/getPosts?page=" + pageNumber + '&category=' + category + 
                 '&publishMonth=' + publishMonth,
            dataType: 'JSON',
            success: function(result) {
                $('#posts tbody').empty();

                if ( result['isSuccessful'] ) {
                    displayPosts(result['posts']);
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function displayPosts(posts) {
        var totalPosts = posts.length;
        for ( var i = 0; i < totalPosts; ++ i ) {
            $('#posts tbody').append('<tr>'
                                  + '    <td>' + posts[i]['postId'] + '</td>'
                                  + '    <td>' + posts[i]['postTitle'] + '</td>'
                                  + '    <td>' + posts[i]['postCategoryName'] + '</td>'
                                  + '    <td>' + posts[i]['postDate'] + '</td>'
                                  + '</tr>');
        }
    }
</script>
<script type="text/javascript">
    function getPostTotalPages(pageNumber, category, publishMonth) {
        $.ajax({
            type: 'GET',
            url: '<?php echo $this->basePath(); ?>/administration/getPostTotalPages?category=' + category + '&publishMonth=' + publishMonth,
            dataType: 'JSON',
            success: function(result) {
                $('div.pagination > ul').empty();
                if ( result['isSuccessful'] ) {
                    $('div.pagination').removeClass('hide');
                    displayPagination(pageNumber, result['totalPages']);
                } else {
                    $('div.pagination').addClass('hide');
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function displayPagination(currentPage, totalPages, filterUrl) {
        var lowerBound = ( currentPage - 3 > 0 ? currentPage - 3 : 1 ),
            upperBound = ( currentPage + 3 < totalPages ? currentPage + 3 : totalPages );
        var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="#">&gt;</a></li>';
        $('.pagination > ul').append(paginationString);
    }
</script>
<script type="text/javascript">
    $('.pagination > ul').delegate('li', 'click', function(e) {
        e.preventDefault();
        if ( $(this).hasClass('disabled') ) {
            return;
        }
        var currentPage = parseInt($('li.active > a', '.pagination').html(), 10),
            pageNumber  = $('a', this).html();
        
        $('.pagination > li.active').removeClass('active');
        $(this).addClass('active');

        if ( pageNumber === '&lt;' ) {
            pageNumber  = currentPage - 1;
        } else if ( pageNumber === '&gt;' ) {
            pageNumber  = currentPage + 1;
        }
        return getFilters(pageNumber);
    });
</script>
<script type="text/javascript">
    $(function() {
        return getFilters(1);
    });
</script>
<script type="text/javascript">
    function getPostsUsingKeyword() {
        var keyword = $('#keyword').val().trim();

        if ( keyword.length == 0 ) {
            alert('请输入搜索关键词');
            return;
        }

        $.ajax({
            type: 'GET',
            url: "<?php echo $this->basePath(); ?>/administration/getPostsUsingKeyword?keyword=" + keyword,
            dataType: 'JSON',
            success: function(result) {
                $('#posts tbody').empty();
                $('div.pagination').addClass('hide');

                if ( result['isSuccessful'] ) {
                    displayPosts(result['posts']);
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function newPost() {
        $('#post-editor h4').html('新培训动态');
        $('#post-editor input').val('');
        $('#post-editor textarea').val('');

        $('#post-editor').modal();
    }
</script>
<script type="text/javascript">
    $('#posts').delegate('tr', 'click', function() {
        var postId = $(this).find('td:first').html();
        return editPost(postId);
    });
</script>
<script type="text/javascript">
    function editPost(postId) {
        $('#post-editor h4').html('编辑培训动态');
        
        $.ajax({
            type: 'GET',
            async: false,
            url: "<?php echo $this->basePath(); ?>/training/getPost?postId=" + postId,
            dataType: 'JSON',
            success: function(result) {
                if ( result['isSuccessful'] ) {
                    $('#post-editor input#post-id').val(result['post']['postId']);
                    $('#post-editor input#post-title').val(result['post']['postTitle']);
                    $('#post-editor select#post-category').val(result['post']['postCategorySlug']);
                    $('#post-editor textarea#post-content').val(result['post']['postContent']);
                } else {
                    alert('发生了未知错误, 请联系技术支持人员.');
                }
            }
        });

        $('#post-editor').modal();
    }
</script>
<script type="text/javascript">
    $('#post-editor button.btn-primary').click(function() {
        var postId          = $('#post-editor input#post-id').val(),
            postTitle       = $('#post-editor input#post-title').val(),
            postCategory    = $('#post-editor select#post-category').val(),
            postContent     = $('#post-editor textarea#post-content').val();            

        if ( $('#post-editor input#post-id').val() == '' ) {
            return newPostAction(postTitle, postCategory, postContent);
        } else {
            return editPostAction(postId, postTitle, postCategory, postContent);
        }
    });
</script>
<script type="text/javascript">
    function newPostAction(postTitle, postCategory, postContent) {
        var postData = {
            'postTitle': postTitle,
            'postCategory': postCategory,
            'postContent': postContent
        };

        $('#post-editor button.btn-primary').html('正在处理...');
        $('#post-editor button.btn-primary').attr('disabled', 'disabled');

        $.ajax({
            type: 'POST',
            async: false,
            url: "<?php echo $this->basePath(); ?>/administration/newPost",
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                return processResult(result);
            }
        });
    }
</script>
<script type="text/javascript">
    function editPostAction(postId, postTitle, postCategory, postContent) {
        var postData = {
            'postId': postId,
            'postTitle': postTitle,
            'postCategory': postCategory,
            'postContent': postContent
        };

        $('#post-editor button.btn-primary').html('正在处理...');
        $('#post-editor button.btn-primary').attr('disabled', 'disabled');

        $.ajax({
            type: 'POST',
            async: false,
            url: "<?php echo $this->basePath(); ?>/administration/editPost",
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                return processResult(result);
            }
        });
    }
</script>
<script type="text/javascript">
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            $('#post-editor').modal('hide');
            getFilters(1);
        } else {
            var errorMessage = '';

            if ( result['isPostTitleEmpty'] ) {
                errorMessage += '请填写培训动态的标题<br />';
            } else if ( !result['isPostTitleLegal'] ) {
                errorMessage += '培训动态的标题不得超过128个字符<br />';
            }
            if ( result['isPostCategoryEmpty'] ) {
                errorMessage += '请选择培训动态的分类<br />';
            } else if ( !result['isPostCategoryLegal'] ) {
                errorMessage += '请选择培训动态的分类<br />';
            }
            if ( result['isPostContentEmpty'] ) {
                errorMessage += '请填写培训动态的内容<br />';
            }

            $('#post-editor .alert-error').removeClass('hide');
            $('#post-editor .alert-error').html(errorMessage);
        }

        $('#post-editor button.btn-primary').html('确认');
        $('#post-editor button.btn-primary').removeAttr('disabled');
    }
</script>