<?php echo $this->doctype(); ?>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <?php echo $this->headTitle('IT培训平台') ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- CSS -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath('/img/favicon.png')))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
                    ->appendStylesheet($this->basePath() . '/css/font-awesome.min.css')
    ; ?>
    <!-- Java Script -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery-1.11.1.min.js')
    ; ?>
    <!--[if lte IE 7]>
        <link rel="stylesheet" type="text/css" href="public/css/font-awesome-ie7.min.css">
        <script type="text/javascript" sec="public/js/icon-font-ie7.js"></script>
    <![endif]-->
</head>
<body>
    <?php echo $this->content; ?>
    <div id="footer">
        <div class="container row-fluid">
            <div class="span8">
                <ul class="inline">
                    <li><a href="#">关于我们</a></li>
                    <li><a href="#">合作伙伴</a></li>
                    <li><a href="#">诚招英才</a></li>
                    <li><a href="#">联系我们</a></li>
                    <li><a href="#">网站地图</a></li>
                </ul>
                <div id="introduction">
                    <img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="Logo">
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div> <!-- #introduction -->
            </div> <!-- .span8 -->
            <div class="span4">
                <ul class="inline">
                    <li><a href="#"><img src="<?php echo $this->basePath(); ?>/img/social/weibo.png" alt="WeiBo"></a></li>
                    <li><a href="#"><img src="<?php echo $this->basePath(); ?>/img/social/wechat.png" alt="WeChat"></a></li>
                </ul>
                <p id="copyright">Copyright&copy; <?php echo date('Y'); ?> IT培训平台. All rights reserved.</p>
                <ul>
                    <li><a href="#">服务条款</a></li>
                    <li><a href="#">隐私声明</a></li>
                </ul>
            </div> <!-- .span4 -->
        </div> <!-- .container -->
    </div> <!-- #footer -->
    <!-- JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript">
        function scrollToTop() {
            $('html, body').animate({ scrollTop: 0 }, 'slow');
        }
    </script>
    <?php echo $this->inlineScript() ?>
</body>
</html>
