<div style="padding:0;margin:0;background:#e9e9e9;font-family:'Segoe UI', 'Microsoft YaHei'">
<table align="center" width="625" style="background:#e9e9e9" cellspacing="0" cellpadding="0" border="0">
	<tbody>
		<tr>
			<td>
				<div style="color:#1b1b1b;background:#fff;border:1px solid #aaa;border-radius:5px;margin:15px">
					<table cellspacing="0" cellpadding="0" border="0">
						<tbody>
							<tr>
								<td style="padding:15px 15px 0 15px;background:#fff;border-radius:4px 4px 0 0">
									<div>
										<img src="https://lab.testzilla.org/CourseOcean/img/logo.png" alt="CourseOcean" style="max-width:160px">
									</div>
								</td>
							</tr>
							<tr>
								<td style="padding:15px; background:#fff; border-radius:0 0 4px 4px;font-size:12px">
									<?=$this->username?>, 你好: <br><br>
									我们收到了重设 学海无涯 账户密码的请求.<br><br>
									如果您未发出请求, 请不要担心, 只需忽略此电子邮件, 任何内容均不会更改.<br><br>
									如果确实是您请求重设 学海无涯 账户密码，点击以下按钮即可:<br>
									<a href="https://lab.testzilla.org/CourseOcean/accounts/resetPassword?email=<?=$this->email?>&keycode=<?=$this->keycode?>" target="_blank"style="background-color:#5cb85c;border-color:#4cae4c;border-radius:4px;color: #fff;display:block;padding: 6px 12px;margin:10px auto;text-align:center;text-decoration:none;width:100px;">重置密码</a>
									若将以下链接复制至浏览器的地址栏中:<br>
									https://lab.testzilla.org/CourseOcean/accounts/resetPassword?email=<?=$this->email?>&keycode=<?=$this->keycode?><br><br>
									此致, <br>
									学海无涯.<br><br>
									<div style="border-top:3px solid #eee;color:#999;font-size:11px;line-height:1.2">
										<br>Powered by <a href="http://www.courseocean.com" target="_blank" style="color: #005399;text-decoration: none;">学海无涯(CourseOcean)</a>. All rights reserved.<br>
									</div>
								</td>
							</tr>
						</tbody>
					</table>            
				</div>
			</td>
		</tr>
	</tbody>
</table>
</div>