<?php 
    echo $this->headTitle('完成注册 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/complete.css');
?>

<div id="content">
    <div id="banner">
        <div id="banner-content">
            <h2>完成注册</h2>
            <h4>请完善您的个人资料以完成注册</h4>
        </div> <!-- #banner-content -->
    </div> <!-- #banner -->
    <div id="main-container" class="row">
    	<div class="span8">
        </div> <!-- .span8 -->
        <div class="span4">
        </div>
    </div> <!-- #main-container -->
</div> <!-- #content -->