<?php 
    echo $this->headTitle('注册 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/register.css');
?>

<div id="content">
    <div id="banner">
        <div id="banner-content">
            <h2>从这里开启您的IT培训之旅</h2>
            <h4>为您提供最及时、最便捷的IT培训</h4>
            <button class="btn btn-danger" onclick="javascript:addFavorite()">收藏本站</button>
        </div> <!-- #banner-content -->
    </div> <!-- #banner -->
    <div id="main-container" class="row">
        <div id="introduction" class="span7">
            <div id="features">
                <div class="row">
                    <div class="feature span3">
                        <div class="icon">
                            <img src="<?php echo $this->basePath(); ?>/img/features/feature-teachers.png" alt="Feature" />
                        </div> <!-- .icon -->
                        <div class="content">
                            <p class="title">最好的讲师</p>
                            <p>我们的讲师大部分都来自于知名企业, 如思科、淘宝等, 可以提供最优质的培训.</p>
                        </div> <!-- .content -->
                    </div> <!-- .feature -->
                    <div class="feature offset1 span3">
                        <div class="icon">
                            <img src="<?php echo $this->basePath(); ?>/img/features/feature-bridge.png" alt="Feature" />
                        </div> <!-- .icon -->
                        <div class="content">
                            <p class="title">讲师和用户的桥梁</p>
                            <p>我们为讲师和用户提供了沟通的平台, 使用户可以选择适合自己的培训课.</p>
                        </div> <!-- .content -->
                    </div> <!-- .feature -->
                </div>
                <div class="row">
                    <div class="feature span3">
                        <div class="icon">
                            <img src="<?php echo $this->basePath(); ?>/img/features/feature-money.png" alt="Feature" />
                        </div> <!-- .icon -->
                        <div class="content">
                            <p class="title">最优惠的价格</p>
                            <p>用户和讲师可以线下交易, 我们不会收取任何中间费用.</p>
                        </div> <!-- .content -->
                    </div> <!-- .feature -->
                    <div class="feature offset1 span3">
                        <div class="icon">
                            <img src="<?php echo $this->basePath(); ?>/img/features/feature-service.png" alt="Feature" />
                        </div> <!-- .icon -->
                        <div class="content">
                            <p class="title">倾听用户需求</p>
                            <p>您可以在平台上向任何一位讲师提出自己的培训需求, 使培训更具针对性.</p>
                        </div> <!-- .content -->
                    </div> <!-- .feature -->
                </div>
            </div> <!-- #features -->
        </div> <!-- #introduction -->
        <div id="register-container" class="span5">
            <div id="register-form">
                <h3>创建您的账户</h3>
                <div id="register-error" class="alert alert-error hide"></div>
                <div class="field">
                    <label for="username"><strong>用户名</strong> <small>(6~16个字符, 须以字母开始, 由数字和字母组成)</small></label>
                    <input type="text" id="username" name="username" maxlength="16" />
                </div> <!-- .field -->
                <div class="field">
                    <label for="email"><strong>电子邮件地址</strong></label>
                    <input type="text" id="email" name="email" maxlength="48" />
                </div> <!-- .field -->
                <div class="field">
                    <label for="password"><strong>密码 <small>(6~16个字符, 建议采用强度高的密码)</small></strong></label>
                    <input type="password" id="password" name="password" maxlength="16" />
                </div> <!-- .field -->
                <div class="field">
                    <label for="password-again"><strong>确认密码</strong></label>
                    <input type="password" id="password-again" name="password-again" maxlength="16" />
                </div> <!-- .field -->
                <div class="field">
                    <label for="user-group"><strong>用户类型</strong> <small>(用户类型提交后将不能修改)</small></label>
                    <select id="user-group" name="user-group" id="user-group-selector">
                        <option value="person">个人用户</option>
                        <option value="teacher">讲师用户</option>
                        <option value="company">企业用户</option>
                    </select>
                </div> <!-- .field -->
                <div id="agreement" class="field">
                    <span><strong>创建账户</strong>表示您同意"<a href="#">服务条款</a>"和"<a href="#">隐私声明</a>"</span>
                </div> <!-- #agreement -->
                <div id="controls">
                    <button id="register" class="btn btn-success btn-block">创建您的账户</button>
                </div> <!-- #controls -->
            </div> <!-- #register-form -->
        </div> <!-- #register-container -->
    </div> <!-- #main-container -->
</div> <!-- #content -->

<?php $this->inlineScript()->captureStart(); ?>
    function addFavorite(){ 
        var title   = 'IT自助培训平台',
            url     = '<?php echo $this->basePath(); ?>';
        if (window.sidebar) {
            // Mozilla Firefox
            window.sidebar.addPanel(title, url, "");
        } else if(window.opera && window.print){
            // Opera
            var elem = document.createElement('a');
            elem.setAttribute('href',url);
            elem.setAttribute('title',title);
            elem.setAttribute('rel','sidebar');
            elem.click();
        }  else if(document.all) {
            // Internet Explorer
            window.external.AddFavorite(url, title);
        } else {
            // Other Browsers
            alert('请按下Ctrl+D添加至收藏夹');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('#register').click(function() {
        var postData = getPostData();
        setInputStyle(true);
        doRegisterAction(postData);
        setInputStyle(false);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setInputStyle(isLoading) {
        var registerButtonObject = $('#register');
        if ( isLoading ) {
            registerButtonObject.html('正在创建您的账户...');
            $('input').attr('disabled', 'disabled');
            $('select').attr('disabled', 'disabled');
            $('button').attr('disabled', 'disabled');
        } else {
            registerButtonObject.html('登录');
            $('input').removeAttr('disabled');
            $('select').removeAttr('disabled');
            $('button').removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getPostData() {
        var postData    = '';
        $(':input').each(function() {
            var key     = $(this).attr('name'),
                value   = $(this).val();
            if ( typeof key != 'undefined' && value != '' ) {
                postData += '&' + key + '=' + value;
            }
        });

        return postData;
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doRegisterAction(postData) {
        var userGroup   = $('select#user-group-selector').val();
        if ( userGroup == '' ) {
            return;
        }

        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/register/process',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processResult(result, userGroup);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processResult(result, userGroup) {
        if ( result['isSuccessful'] ) {
            
        }

        var errorMessage = '';
        errorMessage     = onErrorHandler(result, userGroup);

        $('#register-error').html(errorMessage);
        $('#register-error').fadeIn();
        $('html, body').animate({ scrollTop: 0 }, 'slow');
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doVerifyEmailAction() {
        window.location.href='<?php echo $this->basePath(); ?>/accounts/register/verifyEmail';
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function onErrorHandler(result, userGroup) {
        var errorMessage  = '';
        if ( result['isUsernameEmpty'] ) {
            errorMessage += '用户名为必填字段<br />';
        } else if ( !result['isUsernameLegal'] ) {
            errorMessage += '用户名必须以字母开头, 长度须在6-16个字符之间<br />';
        } else if ( result['isUsernameExists'] ) {
            errorMessage += '用户名已被他人占用, 请使用其他用户名<br />';
        }
        if ( result['isEmailEmpty'] ) {
            errorMessage += '电子邮件地址为必填字段<br />';
        } else if ( !result['isEmailLegal'] ) {
            errorMessage += '请填写合法的电子邮件地址<br />';
        } else if ( result['isEmailExists'] ) {
            errorMessage += '该电子邮件地址已被使用, 请使用其他电子邮件地址<br />';
        }
        if ( result['isPasswordEmpty'] ) {
            errorMessage += '请填写您的密码<br />';
        } else if ( !result['isPasswordLegal'] ) {
            errorMessage += '密码必须在6-16个字符之间<br />';
        }
        if ( result['isConfirmPasswordEmpty'] ) {
            errorMessage += '请确认您的密码<br />';
        } else if ( !result['isConfirmPasswordMatched'] ) {
            errorMessage += '密码与确认密码输入不一致<br />';
        }
        if ( !result['isUserGroupLegal'] ) {
            errorMessage += '您所选择的用户组不合法<br />';
        }

        return errorMessage;
    }
<?php $this->inlineScript()->captureEnd(); ?>