<?php 
	echo $this->headTitle('注册 | ');
	echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/register.css');
?>

<div id="content">
	<div id="introduction">
		<div id="title">
			<h1>欢迎</h1>
			<h2>请填写如下表单以完成注册</h2>
		</div> <!-- #title -->
	</div> <!-- #introduction -->
	<div id="register-container">
		<div id="main">
			<div id="register-error" class="alert alert-error hide"></div>
			<div id="username" class="field">
				<label for="username">用户名</label>
				<input type="text" name="username" maxlength="16" />
				<span class="tip">6~18个字符, 可使用字母、数字、下划线，需以字母开头</span>
			</div> <!-- #username -->
			<div id="email" class="field">
				<label for="email">电子邮件地址</label>
				<input type="text" name="email" maxlength="48" />
				<span class="tip">请填写有效的电子邮件地址, 以便用于找回密码</span>
			</div> <!-- #email -->
			<div id="password" class="field">
				<label for="password">密码</label>
				<input type="password" name="password" maxlength="16" />
				<span class="tip">建议采用密码强度高的密码, 长度在6~16个字符之间</span>
			</div> <!-- #password -->
			<div id="password-again" class="field">
				<label for="password-again">确认密码</label>
				<input type="password" name="password-again" maxlength="16" />
				<span class="tip">请确认您所使用的密码</span>
			</div> <!-- #password-again -->
			<div id="user-group" class="field">
				<label for="user-group">用户类型</label>
				<select name="user-group" id="user-group-selector">
					<option value="person">个人</option>
					<option value="teacher">讲师</option>
					<option value="enterprise">企业</option>
				</select>
			</div> <!-- #user-group -->
			<div id="for-person" class="question-group">
				<div id="real-name" class="field">
					<label for="real-name">真实姓名</label>
					<input type="text" name="real-name" maxlength="32" />
					<span class="tip"></span>
				</div> <!-- #real-name -->
				<div id="phone" class="field">
					<label for="phone">联系电话</label>
					<input type="text" name="phone" maxlength="24" />
					<span class="tip">请填写您的联系方式, 以便我们与您取得联系</span>
				</div> <!-- #phone -->
			</div> <!-- #for-person -->
			<div id="for-teacher" class="question-group" style="display: none;">
				<div id="real-name" class="field">
					<label for="real-name">真实姓名</label>
					<input type="text" name="real-name" maxlength="32" />
					<span class="tip"></span>
				</div> <!-- #real-name -->
				<div id="company" class="field">
					<label for="company">所在单位</label>
					<input type="text" name="company" maxlength="64" />
					<span class="tip"></span>
				</div> <!-- #company -->
				<div id="field" class="field">
					<label for="field">擅长领域</label>
					<input type="text" name="field" maxlength="128" />
					<span class="tip">填写您所擅长的领域, 用分号(;)分割</span>
				</div> <!-- #company -->
				<div id="phone" class="field">
					<label for="phone">联系电话</label>
					<input type="text" name="phone" maxlength="24" />
					<span class="tip">请填写您的联系方式, 以便我们与您取得联系</span>
				</div> <!-- #phone -->
			</div> <!-- #for-teacher -->
			<div id="for-enterprise" class="question-group" style="display: none;">
				<div id="company-name" class="field">
					<label for="company-name">公司名称</label>
					<input type="text" name="company-name" maxlength="64" />
					<span class="tip"></span>
				</div> <!-- #company-name -->
				<div id="address" class="field">
					<label for="address">公司地址</label>
					<input type="text" name="address" maxlength="256" />
					<span class="tip"></span>
				</div> <!-- #address -->
				<div id="phone" class="field">
					<label for="phone">联系电话</label>
					<input type="text" name="phone" maxlength="24" />
					<span class="tip">请填写您的联系方式, 以便我们与您取得联系</span>
				</div> <!-- #phone -->
			</div> <!-- #for-enterprise -->
			<div id="agreement" class="field">
				<input type="checkbox" name="agree" />
				<span>同意"服务条款"和"用户须知"、"隐私权相关政策"</span>
			</div> <!-- #agreement -->
			<div id="controls">
				<button id="submit" class="btn btn-primary">提交</button>
				<button id="cancel" class="btn">重置</button>
			</div> <!-- #controls -->
		</div> <!-- #main -->
		<div id="complementary">
			<div id="register-now" class="section">
				<h2>已有账号?</h2>
				<p><a href="<?php echo $this->basePath(); ?>/accounts/login">立即登录</a></p>
			</div>
			<div id="welcome" class="section">
				<h2>欢迎使用</h2>
				<p>欢迎使用IT自助培训平台, 我们将为您提供最及时最便捷的培训.</p>
			</div>
			<div id="need-help" class="section">
				<h2>需要帮助?</h2>
				<p>若您在注册过程中遇到问题, 您可以<a href="#">单击此处</a>查看相关问题的文档.</p>
			</div>
		</div> <!-- #complementary -->
	</div> <!-- #login-container -->
</div> <!-- #content -->

<?php $this->inlineScript()->captureStart(); ?>
	$('select#user-group-selector').change(function() {
		var user_group = $(this).val();
		$('.question-group').css('display', 'none');
		$('#for-' + user_group).css('display', 'block');
	});
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
	$('#cancel').click(function() {
		if ( confirm('你确定要重置吗?') ) {
			$(':input').val('');
		}
	});
<?php $this->inlineScript()->captureEnd(); ?>
<script type="text/javascript">
	$('#submit').click(function() {
		if ( !isAgree() ) {
			alert('请先同意服务条款');
			return;	
		}
		
		var postData = getPostData();
		return doRegisterAction(postData);
	});
</script>
<script type="text/javascript">
	function isAgree() {
		return $('input[name=agree]').is(':checked');
	}
</script>
<script type="text/javascript">
	function getPostData() {
		var postData 	= '';
		$(':input').each(function() {
			var key 	= $(this).attr('name'),
				value	= $(this).val();
			if ( typeof key != 'undefined' && value != '' ) {
				postData += '&' + key + '=' + value;
			}
		});

		return postData;
	}
</script>
<script type="text/javascript">
	function doRegisterAction(postData) {
		$.ajax({
			type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/register/process',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
            	
            },
		});
	}
</script>