<?php 
    echo $this->headTitle('注册 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/register.css');
    echo $this->headScript()->appendFile($this->basePath().'/js/citypicker.js');
?>

<div id="content">
    <div id="introduction">
        <div id="title">
            <h1>欢迎</h1>
            <h2>请填写如下表单以完成注册</h2>
        </div> <!-- #title -->
    </div> <!-- #introduction -->
    <div id="register-container">
        <div id="main">
            <div id="register-error" class="alert alert-error hide"></div>
            <div id="username" class="field">
                <label for="username">用户名</label>
                <input type="text" name="username" maxlength="16" />
                <span class="tip">6~18个字符, 可使用字母、数字、下划线，需以字母开头</span>
            </div> <!-- #username -->
            <div id="email" class="field">
                <label for="email">电子邮件地址</label>
                <input type="text" name="email" maxlength="48" />
                <span class="tip">请填写有效的电子邮件地址, 以便用于找回密码</span>
            </div> <!-- #email -->
            <div id="password" class="field">
                <label for="password">密码</label>
                <input type="password" name="password" maxlength="16" />
                <span class="tip">建议采用密码强度高的密码, 长度在6~16个字符之间</span>
            </div> <!-- #password -->
            <div id="password-again" class="field">
                <label for="password-again">确认密码</label>
                <input type="password" name="password-again" maxlength="16" />
                <span class="tip">请确认您所使用的密码</span>
            </div> <!-- #password-again -->
            <div id="user-group" class="field">
                <label for="user-group">用户类型</label>
                <select name="user-group" id="user-group-selector" class="full-width">
                    <option value="person">个人</option>
                    <option value="teacher">讲师</option>
                    <option value="company">企业</option>
                </select>
            </div> <!-- #user-group -->
            <div id="for-person" class="question-group">
                <div id="person-name" class="field">
                    <label for="person-name">真实姓名</label>
                    <input type="text" name="person-name" maxlength="32" />
                    <span class="tip">请填写您的真实姓名, 以便我们与您取得联系</span>
                </div> <!-- #person-name -->
                <div id="person-phone" class="field">
                    <label for="person-phone">联系电话</label>
                    <input type="text" name="person-phone" maxlength="24" />
                    <span class="tip">请填写您的联系方式, 以便我们与您取得联系</span>
                </div> <!-- #person-phone -->
            </div> <!-- #for-person -->
            <div id="for-teacher" class="question-group" style="display: none;">
                <div id="teacher-name" class="field">
                    <label for="teacher-name">真实姓名</label>
                    <input type="text" name="teacher-name" maxlength="32" />
                    <span class="tip"></span>
                </div> <!-- #teacher-name -->
                <div id="teacher-phone" class="field">
                    <label for="teacher-phone">联系电话</label>
                    <input type="text" name="teacher-phone" maxlength="24" />
                    <span class="tip">请填写您的联系方式, 以便我们与您取得联系</span>
                </div> <!-- #teacher-phone -->
            </div> <!-- #for-teacher -->
            <div id="for-company" class="question-group" style="display: none;">
                <div id="company-name" class="field">
                    <label for="company-name">公司名称</label>
                    <input type="text" name="company-name" maxlength="64" />
                    <span class="tip"></span>
                </div> <!-- #company-name -->
                <div id="company-address" class="field">
                    <label for="company-address">公司地址</label>
                    <input type="text" name="company-address" maxlength="256" />
                    <span class="tip"></span>
                </div> <!-- #address -->
                <div id="company-phone" class="field">
                    <label for="company-phone">联系电话</label>
                    <input type="text" name="company-phone" maxlength="24" />
                    <span class="tip">请填写您的联系方式, 以便我们与您取得联系</span>
                </div> <!-- #phone -->
            </div> <!-- #for-company -->
            <div id="agreement" class="field">
                <input type="checkbox" name="agree" />
                <span>同意"服务条款"和"用户须知"、"隐私权相关政策"</span>
            </div> <!-- #agreement -->
            <div id="controls">
                <button id="register" class="btn btn-primary">提交</button>
                <button id="cancel" class="btn">重置</button>
            </div> <!-- #controls -->
        </div> <!-- #main -->
        <div id="complementary">
            <div id="login-now" class="section">
                <h2>已有账号?</h2>
                <p><a href="<?php echo $this->basePath(); ?>/accounts/login">立即登录</a></p>
            </div>
            <div id="welcome" class="section">
                <h2>欢迎使用</h2>
                <p>欢迎使用IT自助培训平台, 我们将为您提供最及时最便捷的培训.</p>
            </div>
            <div id="need-help" class="section">
                <h2>需要帮助?</h2>
                <p>若您在注册过程中遇到问题, 您可以<a href="#">单击此处</a>查看相关问题的文档.</p>
            </div>
        </div> <!-- #complementary -->
    </div> <!-- #login-container -->
</div> <!-- #content -->

<?php $this->inlineScript()->captureStart(); ?>
    $('select#user-group-selector').change(function() {
        var user_group = $(this).val();
        $('.question-group').css('display', 'none');
        $('#for-' + user_group).css('display', 'block');
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('#cancel').click(function() {
        if ( confirm('你确定要重置吗?') ) {
            $(':input').val('');
        }
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('#register').click(function() {
        if ( !isAgree() ) {
            alert('请先同意服务条款');
            return; 
        }
        
        var postData = getPostData();
        setInputStyle(true);
        doRegisterAction(postData);
        setInputStyle(false);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function isAgree() {
        return $('input[name=agree]').is(':checked');
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setInputStyle(isLoading) {
        var registerButtonObject = $('#register');
        if ( isLoading ) {
            registerButtonObject.html('正在处理...');
            $('input').attr('disabled', 'disabled');
            $('select').attr('disabled', 'disabled');
            $('button').attr('disabled', 'disabled');
        } else {
            registerButtonObject.html('登录');
            $('input').removeAttr('disabled');
            $('select').removeAttr('disabled');
            $('button').removeAttr('disabled');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getPostData() {
        var postData    = '';
        $(':input').each(function() {
            var key     = $(this).attr('name'),
                value   = $(this).val();
            if ( typeof key != 'undefined' && value != '' ) {
                postData += '&' + key + '=' + value;
            }
        });

        return postData;
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doRegisterAction(postData) {
        var userGroup   = $('select#user-group-selector').val();
        if ( userGroup == '' ) {
            return;
        }

        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/register/process',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                processResult(result, userGroup);
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function processResult(result, userGroup) {
        if ( result['isSuccessful'] ) {
            var username = $('input[name=username]').val(),
                password = $('input[name=password]').val();
            doLoginAction(username, password);
        }

        var errorMessage = '';
        errorMessage     = onErrorHandler(result, userGroup);

        $('#register-error').html(errorMessage);
        $('#register-error').fadeIn();
        $('html, body').animate({ scrollTop: 0 }, 'slow');
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function doLoginAction(username, password) {
        var postData = 'username=' + username + '&password=' + password;
        $.ajax({
            type: 'POST',
            async: false,
            url: '<?php echo $this->basePath(); ?>/accounts/login/process',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                if ( result['isSuccessful'] ) {
                    window.location.href = '<?php echo $this->basePath(); ?>/accounts/dashboard';
                } else {
                    window.location.href = '<?php echo $this->basePath(); ?>/accounts/login';
                }
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function onErrorHandler(result, userGroup) {
        var errorMessage  = getCommonErrorMessage(result);

        if ( userGroup == 'person' ) {
            errorMessage += getPersonErrorMessage(result);
        } else if ( userGroup == 'teacher' ) {
            errorMessage += getTeacherErrorMessage(result);
        } else if ( userGroup == 'company' ) {
            errorMessage += getCompanyErrorMessage(result);
        }
        return errorMessage;
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getCommonErrorMessage(result) {
        var errorMessage  = '';
        if ( result['isUsernameEmpty'] ) {
            errorMessage += '用户名为必填字段<br />';
        } else if ( !result['isUsernameLegal'] ) {
            errorMessage += '用户名必须以字母开头, 长度须在6-16个字符之间<br />';
        } else if ( result['isUsernameExists'] ) {
            errorMessage += '用户名已被他人占用, 请使用其他用户名<br />';
        }
        if ( result['isEmailEmpty'] ) {
            errorMessage += '电子邮件地址为必填字段<br />';
        } else if ( !result['isEmailLegal'] ) {
            errorMessage += '请填写合法的电子邮件地址<br />';
        } else if ( result['isEmailExists'] ) {
            errorMessage += '该电子邮件地址已被使用, 请使用其他电子邮件地址<br />';
        }
        if ( result['isPasswordEmpty'] ) {
            errorMessage += '请填写您的密码<br />';
        } else if ( !result['isPasswordLegal'] ) {
            errorMessage += '密码必须在6-16个字符之间<br />';
        }
        if ( result['isConfirmPasswordEmpty'] ) {
            errorMessage += '请确认您的密码<br />';
        } else if ( !result['isConfirmPasswordMatched'] ) {
            errorMessage += '密码与确认密码输入不一致<br />';
        }

        return errorMessage;
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getPersonErrorMessage(result) {
        var errorMessage  = '';
        if ( result['isPersonNameEmpty'] ) {
            errorMessage += '请填写您的真实姓名<br />';
        } else if ( !result['isPersonNameLegal'] ) {
            errorMessage += '真实姓名的长度不能超过32个字符<br />';
        }
        if ( result['isPersonPhoneEmpty'] ) {
            errorMessage += '请填写您的联系电话<br />';
        } else if ( !result['isPersonPhoneLegal'] ) {
            errorMessage += '联系电话必须由数字和-组成, 且长度在7~24个字符之间<br />';
        }

        return errorMessage;
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getTeacherErrorMessage(result) {
        var errorMessage  = '';
        if ( result['isTeacherNameEmpty'] ) {
            errorMessage += '请填写您的真实姓名<br />';
        } else if ( !result['isTeacherNameLegal'] ) {
            errorMessage += '真实姓名的长度不能超过32个字符<br />';
        }
        if ( result['isTeacherPhoneEmpty'] ) {
            errorMessage += '请填写您的联系电话<br />';
        } else if ( !result['isTeacherPhoneLegal'] ) {
            errorMessage += '联系电话必须由数字和-组成, 且长度在7~24个字符之间<br />';
        }

        return errorMessage;
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getCompanyErrorMessage(result) {
        var errorMessage  = '';
        if ( result['isCompanyNameEmpty'] ) {
            errorMessage += '请填写您公司的名称<br />';
        } else if ( !result['isCompanyNameLegal'] ) {
            errorMessage += '公司名称的长度不能超过64个字符<br />';
        }
        if ( result['isCompanyAddressEmpty'] ) {
            errorMessage += '请填写您公司的地址<br />';
        } else if ( !result['isCompanyAddressLegal'] ) {
            errorMessage += '公司地址的长度不能超过256个字符<br />';
        }
        if ( result['isCompanyPhoneEmpty'] ) {
            errorMessage += '请填写您的联系电话<br />';
        } else if ( !result['isCompanyPhoneLegal'] ) {
            errorMessage += '联系电话必须由数字和-组成, 且不超过24个字符<br />';
        }

        return errorMessage;
    }
<?php $this->inlineScript()->captureEnd(); ?>