<?php 
    echo $this->headTitle('验证邮箱 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/accounts/email.css');
?>

<div id="content">
    <div id="dialog-container" class="row">
        <div id="dialog-header">
            请确认您的Email地址
        </div> <!-- #dialog-header -->
        <div id="dialog-content">
            <p>尊敬的用户您好:</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;为了确认您的身份, 防止恶意注册, 我们需要您验证电子邮件地址. 现在, 我们已经将含有验证信息的电子邮件发至您的邮箱. 单击电子邮件上的地址以完成账户验证.</p>
        </div> <!-- #dialog-content -->
        <div id="dialog-footer">
            <button class="btn btn-danger" onclick="javascript:editEmail();">修改电子邮件地址</button>
            <button class="btn btn-primary" onclick="javascript:redirectToMailbox();">查看邮箱</button>
        </div> <!-- #dialog-footer -->
    </div> <!-- #dialog-container -->
</div> <!-- #content -->

<div id="email-dialog">
</div> <!-- #email-dialog -->

<script type="text/javascript">
    function editEmail() {

    }
</script>
<script type="text/javascript">
    function redirectToMailbox() {
        <?php 
            preg_match('/@.*$/', $email, $domains);
            $domain         = ltrim ($domains[0], '@');

            if ( $domain == 'gmail.com' ) {
                $domain     = 'http://mail.google.com';
            } else if ( preg_match('/@hotmail\..*$/', $domain) ) {
                $domain     = 'http://mail.live.com';
            }else {
                $domain     = 'http://mail.'.$domain;
            }
        ?>
        var domain = '<?php echo $domain; ?>';
        window.location.href=domain;
    }
</script>