<?php 
    echo $this->headTitle('培训动态 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/courses/requirement.css');
    echo $this->headScript()->appendFile($this->basePath().'/js/stick-up.min.js');
?>

<div id="content">
    <div id="banner">
        <div id="banner-content">
            <div id="slogan">
                <h2>需求定制</h2>
                <h4>为您量身定制的培训</h4>
            </div> <!-- #slogan -->
            <form id="search" class="navbar-search pull-right">
                <input type="text" class="search-query" />
                <button type="submit" class="btn btn-success">搜索</button>
            </form>
        </div> <!-- #banner-content -->
    </div> <!-- #banner -->
    <div id="main-container">
        <div id="main-content">
            <div id="sidebar">
                <h4>分类目录</h4>
                <ul class="nav nav-pills nav-stacked">

                </ul>
            </div> <!-- #sidebar -->
            <div id="requirement-content">
            123
                <div id="pagination" class="pagination pagination-centered">
                    <ul>
                    <?php
                        $basePath = $this->basePath().'/courses/reqirement/page/';
                        $currentPageNumber  = 10;
                        $numberOfPages      = 20;
                    ?>
                    <?php if ( $currentPageNumber > 1 ): ?>
                        <li><a href="<?php echo $basePath.($currentPageNumber - 1); ?>">&lt;</a></li>
                    <?php else: ?>
                        <li class="disabled"><a>&lt;</a></li>
                    <?php endif; ?>
                    <?php
                        $lowerBound = $currentPageNumber - 5;
                        $lowerBound = ( $lowerBound > 0 ) ? $lowerBound : 1;
                        $upperBound = $currentPageNumber + 4;
                        $upperBound = ( $upperBound <= $numberOfPages ) ? $upperBound : $numberOfPages;

                        for ( $i = $lowerBound; $i <= $upperBound; ++ $i ) {
                            if ( $i == $currentPageNumber ) {
                                echo "<li class=\"active\"><a>$i</a></li>";
                            } else {
                                echo "<li><a href=\"$basePath$i\">$i</a></li>";
                            }
                        }
                    ?>
                    <?php if ( $currentPageNumber < $numberOfPages ): ?>
                        <li><a href="<?php echo $basePath.($currentPageNumber + 1); ?>">&gt;</a></li>
                    <?php else: ?>
                        <li class="disabled"><a>&gt;</a></li>
                    <?php endif; ?>
                    </ul>
                </div> <!-- #pagination-->
            </div> <!-- #requirement-content -->
        </div> <!-- #main-content -->
    </div> <!-- #main-container -->
</div> <!-- #content -->

<?php $this->inlineScript()->captureStart(); ?>
    jQuery(function($) {
        $(document).ready( function() {
            $('#sidebar').stickUp();
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(window).scroll(function() {
        setSidebarVisibility();
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function setSidebarVisibility() {
        var sidebarHeight   = $('#sidebar').outerHeight(),
            headerHeight    = $('#header').outerHeight(),
            footerOffsetTop = $('#footer').offset().top - $(window).scrollTop() - headerHeight,
            offset          = footerOffsetTop - sidebarHeight - headerHeight;
        console.log( 'OffsetTop = ' + footerOffsetTop + "\n" + 'sidebarHeight = ' + sidebarHeight );
        if ( footerOffsetTop < sidebarHeight ) {
            $('#sidebar').css('top', offset);
        } else {
            if ( $('#sidebar').hasClass('isStuck') ) {
                $('#sidebar').css('top', 96);
            } else {
                $('#sidebar').css('top', 0);
            }
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>