<?php 
    echo $this->headTitle('近期培训 | ');
    echo $this->headLink()->appendStylesheet($this->cdn('/css/training/style.css'))
                          ->appendStylesheet($this->cdn('/css/training/courses.css'))
                          ->appendStylesheet($this->cdn('/css/bootstrap.datetimepicker.min.css'));
    echo $this->headScript()->appendFile($this->cdn('/js/bootstrap.datetimepicker.min.js'))
                            ->appendFile($this->cdn('/js/bootstrap.datetimepicker.zh-CN.js'))
                            ->appendFile($this->cdn('/js/jquery.citypicker.js'));
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath('/'); ?>">
                <img src="<?php echo $this->cdn('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?php echo $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?php echo $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath('/accounts/dashboard#requirements'); ?>">需求定制</a></li>
                <li><a href="<?php echo $this->basePath('/training/posts'); ?>">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath('/accounts/register'); ?>'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath('/accounts/dashboard'); ?>"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath('/accounts/logout'); ?>">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?php echo $this->basePath('/home/search'); ?>">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div id="sub-header">
            <h2>近期培训</h2>
            <p>海量课程供您选择! 选择适合您的培训课程.</p>
            <button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/training/courses'">查看课程库</button>
            <img src="<?php echo $this->cdn('/img/training/lecture-header.jpg'); ?>" alt="Header Image">
            <div class="border-bottom"></div> <!-- .border-bottom -->
        </div> <!-- #sub-header -->
        <div id="content" class="row-fluid">
            <div id="sidebar" class="span3">
                <h4>筛选课程</h4>
                <h5>授课领域</h5>
                <ul id="course-types" class="inline">
                    <li class="active"><a href="#all">全部领域</a></li>
                    <?php foreach ( $courseTypes as $courseType ): ?>
                    <li><a href="#<?php echo $courseType->courseTypeSlug; ?>"><?php echo $courseType->courseTypeName; ?></a></li>
                    <?php endforeach; ?>
                </ul>
                <h5>授课时间</h5>
                <ul>
                    <li>
                        <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">
                            <input id="start-time" class="span12" type="text" value="" readonly>
                            <span class="add-on"><i class="icon-th"></i></span>
                        </div> <!-- .input-append -->
                    </li>
                    <li>
                        <div class="controls input-append date form_datetime" data-date-format="yyyy-mm-dd hh:ii">
                            <input id="end-time" class="span12" type="text" value="" readonly>
                            <span class="add-on"><i class="icon-th"></i></span>
                        </div> <!-- .input-append -->
                    </li>
                </ul>
                <h5>授课地点</h5>
                <ul class="city-picker">
                    <li><select class="region"></select></li>
                    <li><select class="province"></select></li>
                    <li><select class="city"></select></li>
                </ul>
            </div> <!-- .span3 -->
            <div class="span9">
                <div class="alert alert-warning hide">未找到符合要求的课程.</div>
                <ul id="courses"></ul>
                <div id="pagination" class="pagination pagination-centered">
                    <ul></ul>
                </div> <!-- #pagination-->
            </div> <!-- .span9 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #container -->

<?php $this->inlineScript()->captureStart(); ?>
    function getFilters(pageNumber) {
        var category    = $('a', 'ul#course-types > li.active').attr('href').substring(1),
            startTime   = $('input#start-time').val(),
            endTime     = $('input#end-time').val(),
            region      = $('select.region').val() || '',
            province    = $('select.province').val() || '',
            city        = $('select.city').val() || '';

        getCourses(category, startTime, endTime, region, province, city, pageNumber);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('ul#course-types > li').click(function() {
        $('ul#course-types > li.active').removeClass('active');
        $(this).addClass('active');

        var pageNumber = 1;
        return getFilters(pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('input#start-time').change(function() {
        var pageNumber = 1;
        return getFilters(pageNumber);
    });
    $('input#end-time').change(function() {
        var pageNumber = 1;
        return getFilters(pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('select.region').change(function() {
        var pageNumber = 1;
        return getFilters(pageNumber);
    });
    $('select.province').change(function() {
        var pageNumber = 1;
        return getFilters(pageNumber);
    });
    $('select.city').change(function() {
        var pageNumber = 1;
        return getFilters(pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getCourses(category, startTime, endTime, region, province, city, pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/training/getLectures?category=' + category + '&startTime=' + startTime + '&endTime=' + endTime + '&region=' + region + '&province=' + province + '&city=' + city + '&page=' + pageNumber,
            dataType: 'JSON',
            success: function(result) {
                $('#courses').empty();
                $('div#pagination > ul').empty();
                if ( result['isSuccessful'] ) {
                    $('.alert-warning').addClass('hide');
                    $('div#pagination').removeClass('hide');
                    displayCourses(result['lectures']);
                    displayPagination(pageNumber, result['totalPages']);
                } else {
                    $('.alert-warning').removeClass('hide');
                    $('div#pagination').addClass('hide');
                }
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayCourses(lectures) {
        var numberOfCourses = lectures.length;
        for ( var i = 0; i < numberOfCourses; ++ i ) {
            $('#courses').append('<li class="course row-fluid">'
                                + '    <div class="span3">'
                                + '        <img src="<?php echo $this->cdn('/img/categories/'); ?>' + lectures[i]['courseTypeSlug'] + '-small.jpg" alt="Course Image" />'
                                + '    </div>'
                                + '    <div class="span9">'
                                + '        <h4><a href="<?php echo $this->basePath(); ?>/training/lecture?lectureId=' + lectures[i]['lectureId'] + '">' + lectures[i]['courseName'] + '</a></h4>'
                                + '        <p class="introduction">' + lectures[i]['brief'] + '</p>'
                                + '        <ul class="inline meta">'
                                + '            <li><i class="fa fa-user"></i> <a href="<?php echo $this->basePath(); ?>/training/teacher?teacherId=' + lectures[i]['teacherId'] + '">' + lectures[i]['teacherName'] + '</a></li>'
                                + '            <li><i class="fa fa-tasks"></i> ' + lectures[i]['courseTypeName'] + '</li>'
                                + '            <li><i class="fa fa-calendar"></i> ' + getDateTime(lectures[i]['startTime']) + '~' + getDateTime(lectures[i]['endTime']) + '</li>'
                                + '            <li><i class="fa fa-map-marker"></i> ' + lectures[i]['lectureProvince'] + ' ' + ( lectures[i]['lectureCity'] || '' ) + '</li>'
                                + '        </ul>'
                                + '    </div>'
                                + '</li>');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getDateTime(dateTimeString) {
        var year    = dateTimeString.substring(0, 4),
            month   = dateTimeString.substring(5, 7),
            day     = dateTimeString.substring(8, 10),
            time    = dateTimeString.substring(11, 16);

        return month + '月' + day + '日 ' + time;
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('#pagination > ul').delegate('li', 'click', function(e) {
        e.preventDefault();
        if ( $(this).hasClass('disabled') ) {
            return;
        }
        var currentPage = parseInt($('li.active > a', 'div#pagination > ul').html());
        
        $('#pagination > li.active').removeClass('active');
        $(this).addClass('active');
        var category    = $('ul#course-types > li.active > a').attr('href').substring(1),
            pageNumber  = $('a', this).html();

        if ( pageNumber === '&lt;' ) {
            pageNumber  = currentPage - 1;
        } else if ( pageNumber === '&gt;' ) {
            pageNumber  = currentPage + 1;
        }
        return getFilters(pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayPagination(currentPage, totalPages) {
        var lowerBound = ( currentPage - 5 > 0 ? currentPage - 5 : 1 ),
            upperBound = ( currentPage + 5 < totalPages ? currentPage + 5 : totalPages );
        var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="#">&gt;</a></li>';
        $('#pagination > ul').append(paginationString);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function initializeDateTimePicker() {
        $('.form_datetime').datetimepicker({
            language:  'zh-CN',
            weekStart: 1,
            todayBtn:  1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            startDate: '<?php echo date('Y-m-d H:i'); ?>',
            endDate: '2099-12-31 23:59',
            forceParse: 0,
            showMeridian: 1
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(function() {
        initializeDateTimePicker();
        $('.city-picker').cityPicker({
            required: false
        });

        var pageNumber = 1;
        return getFilters(pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
