<?php 
    echo $this->headTitle('讲师团队 | ');
    echo $this->headLink()->appendStylesheet($this->cdn('/css/training/style.css'))
                          ->appendStylesheet($this->cdn('/css/training/teachers.css'));
?>

<div class="border-top"></div> <!-- .border-top -->
<div id="header">
    <div class="container row-fluid">
        <div id="logo" class="span4">
            <a href="<?php echo $this->basePath('/'); ?>">
                <img src="<?php echo $this->cdn('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div id="navigation" class="span8">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath('/training/lectures'); ?>">近期培训</a></li>
                <li><a href="<?php echo $this->basePath('/training/courses'); ?>">课程库</a></li>
                <li><a href="<?php echo $this->basePath('/training/teachers'); ?>">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath('/accounts/dashboard#requirements'); ?>">需求定制</a></li>
                <li><a href="<?php echo $this->basePath('/training/posts'); ?>">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath('/accounts/register'); ?>'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath('/accounts/dashboard'); ?>"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath('/accounts/logout'); ?>">注销</a></li>
                <?php endif; ?>
            </ul>
            <form id="search" action="<?php echo $this->basePath('/home/search'); ?>">
                <input name="keyword" type="text" placeholder="搜索课程或讲师" />
                <button class="btn" type="submit">搜索</button>
            </form>
        </div> <!-- #navigation -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="container">
    <div class="container">
        <div id="sub-header">
            <h2>讲师团队</h2>
            <p>卓越的讲师团队! 选择适合您的培训讲师.</p>
            <img src="<?php echo $this->cdn('/img/training/teacher-header.jpg'); ?>" alt="Header Image">
            <div class="border-bottom"></div> <!-- .border-bottom -->
        </div> <!-- #sub-header -->
        <div id="content" class="row-fluid">
            <div class="span3">
                <h4>筛选讲师</h4>
                <h5>授课领域</h5>
                <ul id="course-types" class="inline">
                    <li class="active"><a href="#all">全部领域</a></li>
                    <?php foreach ( $courseTypes as $courseType ): ?>
                    <li><a href="#<?php echo $courseType->courseTypeSlug; ?>"><?php echo $courseType->courseTypeName; ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div> <!-- .span3 -->
            <div class="span9">
                <div class="alert alert-warning hide">未找到符合要求的讲师.</div>
                <ul id="teachers"></ul> <!-- .thumbnails -->
                <div id="pagination" class="pagination pagination-centered">
                    <ul></ul>
                </div> <!-- #pagination-->
            </div> <!-- .span9 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #container -->

<?php $this->inlineScript()->captureStart(); ?>
    $('ul#course-types > li').click(function() {
        $('ul#course-types > li.active').removeClass('active');
        $(this).addClass('active');

        var category   = $('a', this).attr('href').substring(1),
            pageNumber = 1;
        getTeachers(category, pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function getTeachers(category, pageNumber) {
        $.ajax({
            type: 'GET',
            async: true,
            url: '<?php echo $this->basePath(); ?>/training/getTeachers?category=' + category + '&page=' + pageNumber,
            dataType: 'JSON',
            success: function(result) {
                $('#teachers').empty();
                $('div#pagination > ul').empty();
                if ( result['isSuccessful'] ) {
                    $('.alert-warning').addClass('hide');
                    $('div#pagination').removeClass('hide');
                    displayTeachers(result['teachers']);
                    displayPagination(pageNumber, result['totalPages']);
                } else {
                    $('.alert-warning').removeClass('hide');
                    $('div#pagination').addClass('hide');
                }
            }
        });
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayTeachers(teachers) {
        var colors = ['#427fed', '#f4b400', '#53a93f', '#e94d20'],
            numberOfTeachers = teachers.length;
        for ( var i = 0; i < numberOfTeachers; ++ i ) {
            $('#teachers').append('<li class="teacher">'
                                + '<div class="thumbnail">'
                                + '    <div class="avatar" style="background-color: ' + colors[Math.floor(Math.random() * 4)] + '">'
                                + '       <img data-src="holder.js/150x150" src="<?php echo $this->basePath(); ?>/img/avatars/' + 
                                              ( teachers[i]['avatar'] === null ? 'silhouette.png' : teachers[i]['avatar'] ) + '" alt="Avatar" />'
                                + '    </div>' 
                                + '    <a href="<?php echo $this->basePath(); ?>/training/teacher?teacherId=' + teachers[i]['uid'] + '">'
                                + '        <h5>' + teachers[i]['teacherName'] + '</h5>'
                                + '    </a>'
                                + '    <div class="company">' + teachers[i]['company'] + '</div>'
                                + '    <div class="field">' + teachers[i]['teachingField'] + '</div>'
                                + '    <div class="reserve">'
                                + '        <button class="btn btn-orange btn-block" ' 
                                + '                onclick="window.location.href=\'<?php echo $this->basePath(); ?>/accounts/dashboard#requirement?teacherUid=' + teachers[i]['uid'] + '\'">' +'预约</button>'
                                + '    </div>'
                                + '</div>'
                                + '</li>');
        }
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $('#pagination > ul').delegate('li', 'click', function(e) {
        e.preventDefault();
        if ( $(this).hasClass('disabled') ) {
            return;
        }
        var currentPage = parseInt($('li.active > a', 'div#pagination > ul').html());
        
        $('#pagination > li.active').removeClass('active');
        $(this).addClass('active');
        var category    = $('ul#course-types > li.active > a').attr('href').substring(1),
            pageNumber  = $('a', this).html();

        if ( pageNumber === '&lt;' ) {
            pageNumber  = currentPage - 1;
        } else if ( pageNumber === '&gt;' ) {
            pageNumber  = currentPage + 1;
        }
        getTeachers(category, pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    function displayPagination(currentPage, totalPages) {
        var lowerBound = ( currentPage - 5 > 0 ? currentPage - 5 : 1 ),
            upperBound = ( currentPage + 5 < totalPages ? currentPage + 5 : totalPages );
        var paginationString  = '<li' + ( currentPage > 1 ? '>' : ' class="disabled">') + '<a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li' + ( currentPage < totalPages ? '>' : ' class="disabled">') + '<a href="#">&gt;</a></li>';
        $('#pagination > ul').append(paginationString);
    }
<?php $this->inlineScript()->captureEnd(); ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(function() {
        var pageNumber = 1;
        getTeachers('all', pageNumber);
    });
<?php $this->inlineScript()->captureEnd(); ?>