<?php 
    echo $this->headTitle('帮助中心 | ');
    echo $this->headLink()->appendStylesheet($this->cdn('/css/about/style.css'))
                          ->appendStylesheet($this->cdn('/css/about/support.css'));
?>

<div id="header" class="container">
    <div class="row-fluid">
        <div id="logo" class="span3">
            <a href="<?php echo $this->basePath('/'); ?>">
                <img src="<?php echo $this->cdn('/img/logo.png'); ?>" alt="Logo" />
            </a>
        </div> <!-- #logo -->
        <div class="span9">
            <ul class="inline">
                <li><a href="<?php echo $this->basePath(); ?>/training/lectures">近期培训</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/courses">课程库</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/teachers">讲师团队</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/accounts/dashboard#requirement">需求定制</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/training/posts">培训动态</a></li>
                <?php
                    $session    = new Zend\Session\Container('co_session');
                    if ( !$session->offsetExists('isLogined') ):
                ?>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/login"><strong>登录</strong></a></li>
                    <li><button class="btn btn-orange" onclick="window.location.href='<?php echo $this->basePath(); ?>/accounts/register'">创建账户</button></li>
                <?php else: ?>
                    <li>您好, <a href="<?php echo $this->basePath(); ?>/accounts/dashboard"><?php echo $session->offsetGet('username'); ?></a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/accounts/logout">注销</a></li>
                <?php endif; ?>
            </ul>
        </div> <!-- .span9 -->
    </div> <!-- #container -->
</div> <!-- #header -->
<div id="hero">
    <div class="container">
        <h1>帮助中心</h1>
        <p>答疑解惑, 只为更优质的服务.</p>
    </div> <!-- #container -->
</div> <!-- #hero -->
<div id="container" class="container">
    <div class="row-fluid">
        <div id="sidebar" class="span3">
            <ul class="nav nav-list">
                <li><a href="<?php echo $this->basePath(); ?>/about">关于我们</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/about/partner">合作伙伴</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/about/join">诚招英才</a></li>
                <li class="active"><a href="<?php echo $this->basePath(); ?>/about/support">帮助中心</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/about/feedback">意见反馈</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/about/term">服务条款</a></li>
            </ul>
        </div> <!-- .span3 -->
        <div id="content" class="span9">
            <div class="accordion">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent=".accordion" href="#collapse-item">Collapsible Group Item</a>
                    </div> <!-- .accordion-heading -->
                    <div id="collapse-item" class="accordion-body collapse">
                        <div class="accordion-inner">
                            Anim pariatur cliche...
                        </div> <!-- .accordion-inner -->
                    </div> <!-- .accordion-body -->
                </div> <!-- .accordion-group -->
            </div> <!-- .accordion -->
        </div> <!-- .span9 -->
    </div> <!-- .row-fluid -->
</div> <!-- #container -->