<?php 
    echo $this->headTitle('首页 | ');
    echo $this->headLink()->appendStylesheet($this->basePath().'/css/homepage.css');
?>

<div id="content">
    <div id="slider" class="carousel slide">
        <div class="carousel-inner">
            <div class="active item" style="background-color: #3eafe8;">
                <img src="<?php echo $this->basePath(); ?>/img/sliders/home-world.png" alt="Slider Image">
            </div>
            <div class="item" style="background-color: #4db66b;">
                <img src="<?php echo $this->basePath(); ?>/img/sliders/home-world.png" alt="Slider Image">
            </div>
            <div class="item" style="background-color: #7774bc;">
                <img src="<?php echo $this->basePath(); ?>/img/sliders/home-world.png" alt="Slider Image">
            </div>
        </div>
        <ol class="carousel-indicators">
            <li data-target="#slider" data-slide-to="0" class="active"></li>
            <li data-target="#slider" data-slide-to="1"></li>
            <li data-target="#slider" data-slide-to="2"></li>
        </ol>
    </div> <!-- #slider -->
    <div id="quotes">
        <div id="search-box">
            <div class="input-append">
                  <input class="span5" id="appendedInputButton" type="text" placeholder="搜索适合您的课程与讲师">
                  <button class="btn btn-success" type="button">搜索</button>
            </div>
        </div> <!-- #search-box -->
        <div id="quotes-content">
            <div class="row">
                <div class="span6">
                    <div class="avatar">
                        <img src="<?php echo $this->basePath(); ?>/img/avatars/ning-an.png" alt="Avatar" class="img-circle" />
                    </div> <!-- .avatar -->
                    <div class="quote">
                        <p class="blockquote">IT培训平台让我们不断学习, 推进卓越开发团队迈向巅峰!</p>
                        <p class="introduction">安宁, 曾任美国甲骨文公司空间数据部主任工程师</p>
                    </div> <!-- .quote -->
                </div> <!-- .span6 -->
                <div class="span6">
                    <div class="avatar">
                        <img src="<?php echo $this->basePath(); ?>/img/avatars/kerry.png" alt="Avatar" class="img-circle" />
                    </div> <!-- .avatar -->
                    <div class="quote">
                        <p class="blockquote">IT培训平台为我们提供最及时、最优质的培训!</p>
                        <p class="introduction">朱少民, 曾任思科—网迅软件有限公司资深QA总监</p>
                    </div> <!-- .quote -->
                </div> <!-- .span6 -->
            </div> <!-- .row -->
        </div> <!-- quotes-content -->
    </div> <!-- #quote -->
    <div id="lectures">
        <div id="lectures-content" class="row section">
            <h3>我们推荐的课程</h3>
            <div class="span6">
            <?php if ( isset( $lectures ) && $lectures ): ?>
            <?php foreach ( $lectures as $lecture ) { ?>
                <div class="block">
                    <div class="icon">
                    <?php if ( rand() % 3 == 0 ): ?>
                        <span class="label label-important">HOT</span>
                    <?php elseif ( rand() % 3 == 1 ): ?>
                        <span class="label label-success">NEW</span>
                    <?php endif; ?>
                    </div> <!-- .icon -->
                    <a href="<?php echo $this->basePath(); ?>/solution/lecture/detail/<?php echo $lecture->lecture_id; ?>">
                        <div class="content">
                            <h4><?php echo $lecture->course_name; ?></h4>
                            <span><i class="icon-calendar"></i> <?php echo date('Y年m月d日', strtotime($lecture->lecture_start_time)); ?>~<?php echo date('Y年m月d日', strtotime($lecture->lecture_end_time)); ?></span>
                            <span><i class="icon-user"></i> <?php echo $lecture->teacher_name; ?></span>
                            <p><?php echo mb_substr( $lecture->course_brief, 0, 80, "utf-8" ); ?>...</p>
                        </div> <!-- .content -->
                    </a>
                </div> <!-- .block -->
            <?php } ?>
            <?php endif; ?>
            </div> <!-- .span6 -->
            <div class="span6">
                <img src="<?php echo $this->basePath(); ?>/img/lectures.png" alt="Lectures" />
            </div> <!-- .span6 -->
        </div> <!-- #lectures-content -->
    </div> <!-- #lectures -->
    <div id="news">
        <div id="news-content" class="row section">
            <h3>培训动态</h3>
            <div class="span6">
                <img src="<?php echo $this->basePath(); ?>/img/news.png" alt="News" />
            </div> <!-- .span6 -->
            <div class="span6">
            <?php if ( isset( $news ) && $news ): ?>
            <?php foreach ( $news as $newsPost ) { ?>
                <div class="block">
                    <div class="icon">
                        <img src="<?php echo $this->basePath(); ?>/img/icons/post.png" alt="Post">
                    </div> <!-- .icon -->
                    <a href="<?php echo $this->basePath(); ?>/solution/news/detail/<?php echo $newsPost->news_id; ?>">
                        <div class="content">
                            <h4><?php echo $newsPost->news_title; ?></h4>
                            <span><i class="icon-th-list"></i> <?php echo $newsPost->news_category_name; ?></span>
                            <span><i class="icon-calendar"></i> <?php echo date('Y年m月d日', strtotime($newsPost->publish_date)); ?></span>
                            <p><?php echo mb_substr( $newsPost->news_content, 0, 150, "utf-8" ); ?></p>
                        </div> <!-- .content -->
                    </a>
                </div> <!-- .block -->
            <?php } ?>
            <?php endif; ?>
            </div> <!-- .span6 -->
        </div> <!-- #news-content -->
    </div> <!-- #news -->
    <div id="partners">
        <div id="partners-content">
            <h3>我们的合作伙伴</h3>
            <ul class="inline">
                <li><img src="<?php echo $this->basePath(); ?>/img/partners/cisco.png" alt="Cisco" /></li>
                <li><img src="<?php echo $this->basePath(); ?>/img/partners/webex.png" alt="WebEx" /></li>
                <li><img src="<?php echo $this->basePath(); ?>/img/partners/taobao.png" alt="TaoBao" /></li>
                <li><img src="<?php echo $this->basePath(); ?>/img/partners/sea-skylight.png" alt="Sea Skylight" /></li>
                <li><img src="<?php echo $this->basePath(); ?>/img/partners/jielan.png" alt="JieLan" /></li>
            </ul>
        </div> <!-- #partners-content -->
    </div> <!-- #partners -->
</div> <!-- #content -->

<script type="text/javascript">
    $(document).ready(function() {
        $('.carousel').carousel('cycle');
    });
</script>
<script type="text/javascript">
    $(window).scroll(function() {
        if ( $(window).scrollTop() >= 260 ) {
            $('#header').css('background-color', '#3eafe8');
        } else {
            $('#header').css('background-color', 'transparent');
        }
    });
</script>